### PR TITLE
Fix missing content change during consecutive didClose/didOpen

### LINKED ISSUE #2511: Stale diagnostics on file reload
When Neovim detects that a file has changed on disk (e.g., on `:checktime`), it reloads it and notifies the LSP server by `textDocument/didClose` followed by `textDocument/didOpen`. When this happens, `tsgo` diagnostics are not updated until the file is modified in the editor again.

### PR DESCRIPTION
**Pull request by jakebailey**
This fixes #2511, but the tests are flaky, I think because the events are not always combined.

Would love some feedback about this ☹️

### CODE REVIEW

**Comment by frangio** [comment]
I can confirm that this fixes #2511 for me.

File: internal/project/overlayfs.go [hunk 1]
```diff
@@ -300,6 +304,9 @@ func (fs *overlayFS) processChanges(changes []FileChange) (FileChangeSummary, ma
 				panic("can only process one file open event at a time")
 			}
 			result.Opened = uri
+			if events.reopened {
+				result.Changed.Add(uri)
```
Comment (andrewbranch) [inline internal/project/overlayfs.go:307]: We might need to see if the contents of the didOpen actually resulted in a change...

File: testdata/baselines/reference/fourslash/state/declarationMapsRenameWithDisableSourceOfProjectReferenceRedirect.baseline [hunk 2]
```diff
@@ -426,7 +435,7 @@ Projects::
     /myproject/decls/FnS.d.ts  
     /myproject/main/main.ts    
   [/myproject/tsconfig.json] *deleted*
-  [/random/tsconfig.json] 
+  [/random/tsconfig.json] *modified*
```
Comment (andrewbranch) [inline testdata/baselines/reference/fourslash/state/declarationMapsRenameWithDisableSourceOfProjectReferenceRedirect.baseline]: ...I'm guessing that would resolve all these changed baselines, but I'm not really sure what would have caused this.

File: internal/project/overlayfs.go (hunk 1 above)
Comment (jakebailey) [reply internal/project/overlayfs.go:307]: I think that worked!

Comment (jakebailey) [reply internal/project/overlayfs.go:307]: Though, I am a little unsure about the logistics of multiple changes within the same FileChange, so maybe the continue is wrong?

Comment (jakebailey) [reply internal/project/overlayfs.go:307]: Pushed something that I think is better

**Comment by andrewbranch** [comment]
Seems good in principle but I really want to know why all those server baselines changed 🤔

**Comment by jakebailey** [comment]
Yeah 🫤

**Comment by andrewbranch** [comment]
I think I fixed it

File: internal/project/overlayfs.go [hunk 3]
```diff
@@ -300,6 +304,9 @@ func (fs *overlayFS) processChanges(changes []FileChange) (FileChangeSummary, ma
 				panic("can only process one file open event at a time")
 			}
 			result.Opened = uri
+			if events.reopened && o != nil && o.Content() != events.openChange.Content {
```
Comment (andrewbranch) [inline internal/project/overlayfs.go]: Honestly we don't even need the `reopened` flag to do this... it's a little weird that we're saying this was opened at all... your last commit "fixed" that but still broke baselines, so maybe I don't fully understand what's going on yet after all

Comment (andrewbranch) [reply internal/project/overlayfs.go]: Ok, now I think it makes more sense and still passes tests

**Review by sheetalkamat — APPROVED** [review]
