### PR TITLE
fix(1250): fix bigint literal type declaration emit

### LINKED ISSUE #1250: bigint literal creates invalid type declaration
With the following setup:

tsgo compiled from commit `2aa0eb5d92ba30e24710a5fa95a8781ae8ef285a`

tsconfig.json
```json
{
    "compilerOptions": {
        "target": "ES2020",
        "outDir": "./dist",
        "declaration": true,
    }
}
```

bug.ts
```ts
export const X = 0n;
```

The emitted declarations are invalid:
```
> rm -rf dist && tsgo && cat dist/bug.d.ts
export declare const X = ;
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #1250

### CODE REVIEW

File: internal/checker/emitresolver.go [hunk 1]
```diff
@@ -915,15 +915,7 @@ func (r *emitResolver) CreateLiteralConstValue(emitContext *printer.EmitContext,
...
-		value := literalValue.(jsnum.PseudoBigInt)
-		if value.Negative {
-			// negative
-			return emitContext.Factory.NewPrefixUnaryExpression(
-				ast.KindMinusToken,
-				emitContext.Factory.NewBigIntLiteral(value.Base10Value),
-			)
-		}
-		return emitContext.Factory.NewNumericLiteral(value.Base10Value)
+		return emitContext.Factory.NewBigIntLiteral(pseudoBigIntToString(literalValue.(jsnum.PseudoBigInt)) + "n")
```
Comment (jakebailey) [inline internal/checker/emitresolver.go]: While here, can you change the switch to `literalValue := literalValue.(type)` and remove the double type assertions?

File: internal/checker/emitresolver.go [hunk 2]
```diff
@@ -901,11 +901,10 @@ func (r *emitResolver) CreateLiteralConstValue(emitContext *printer.EmitContext,
 		return nil // non-literal type
 	}
 	literalValue := t.AsLiteralType().value
-	switch literalValue.(type) {
+	switch value := literalValue.(type) {
 	case string:
 		return emitContext.Factory.NewStringLiteral(literalValue.(string))
 	case jsnum.Number:
```
Comment (jakebailey) [inline internal/checker/emitresolver.go:906]: This one's still redundant; you can just reuse the name "literalValue" and the linter should point these out.

Comment (jakebailey) [reply internal/checker/emitresolver.go:906]: Oops, I meant to comment on the line above with string.
