### PR TITLE
Watch directories and react to symlink directory creation

### LINKED ISSUE #2506: Stale module resolution error after linking pnpm workspace dependency due to watcher configuration/handling
### Extension Version

main

### VS Code Version

1.109.0-insider (Universal)

### Operating system Version

macOS Tahoe 26.2

### Steps to reproduce

1. Create a pnpm workspace with two packages, but do not `pnpm install` yet.
2. Make one package depend on the other and write an import that will eventually resolve through a node_modules symlink.
3. `pnpm install`

### Issue

`pnpm install` creating the node_modules link should make the error go away, but the file watcher doesn't trigger. VS Code sees the directory symlink creation, but doesn't send it to us because it doesn't match our watch glob pattern which ends with `**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json}` (unless the directory name happens to have one of those extensions). Dropping the extension alone is not sufficient, since we check the created files from the `didChangeWatchedFiles` notification against `failedLookupLocations` keys, which are full files.

This is somewhat related to our other known directory watch issue, which is missing events when deleting a directory, since VS Code only sends a deletion event for the directory, not for the files inside.

### PR DESCRIPTION
**Pull request by andrewbranch**
- Fixes #2506 
- Fixes the thing where deleting a directory doesn't get picked up (https://github.com/microsoft/vscode/issues/109754)
- Adds some follow-up from #3038

### CODE REVIEW

File: internal/project/snapshotfs.go [hunk 1]
```diff
@@ -398,13 +399,105 @@ func (s *snapshotFSBuilder) markDirtyFiles(change FileChangeSummary) {
...
+// hasRelevantWatchExtension returns true if the given path ends with a file
+// extension relevant to TypeScript compilation. This is used to quickly filter
+// out watch events for files that cannot affect the project.
+func hasRelevantWatchExtension(path string) bool {
+	i := strings.LastIndexByte(path, '.')
+	if i < 0 {
+		return false
+	}
+	switch path[i:] {
+	case ".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".mts", ".cts", ".json":
```
Comment (jakebailey) [inline internal/project/snapshotfs.go:416]: This is probably duplicative of `tspath`, but I assume it's here for perf?
