### PR TITLE
Fix multiple issues related to extreme symbol merging

### LINKED ISSUE #2697: Crash compiling TypeScript tests
## Stack trace

```
panic: runtime error: index out of range [2] with length 2

goroutine 51982 [running]:
github.com/microsoft/typescript-go/internal/checker.(*TupleNormalizer).normalize(0x140615c7510, 0x1403ea2cc08, {0x14052012390, 0x3, 0x0?}, {0x14052094f60, 0x2, 0x102297f7c?})
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:22803 +0x878
github.com/microsoft/typescript-go/internal/checker.(*Checker).createNormalizedTupleType(0x1403ea2cc08, 0x1025bcc90?, {0x14052012390?, 0x1404b6655e0?, 0x140521185b0?})
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:22775 +0xa8
github.com/microsoft/typescript-go/internal/checker.(*Checker).createNormalizedTypeReference(0x102e590e0?, 0x1403ea2cc08?, {0x14052012390?, 0x3?, 0x3?})
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:22740 +0x28
github.com/microsoft/typescript-go/internal/checker.(*Checker).instantiateTypeWorker(0x1403ea2cc08, 0x14052114540, 0x14052095000, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:21737 +0x148
github.com/microsoft/typescript-go/internal/checker.(*Checker).instantiateTypeWithAlias(0x1403ea2cc08, 0x14052114540, 0x14052095000, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:21639 +0x3e4
github.com/microsoft/typescript-go/internal/checker.(*Checker).instantiateType(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:21607
github.com/microsoft/typescript-go/internal/checker.(*Relater).reportErrorResults(0x14097600900, 0x1404b6655e0, 0x14052114540, 0x1404b6655e0, 0x14052114540, 0x1034ce260)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/relater.go:4677 +0x378
github.com/microsoft/typescript-go/internal/checker.(*Relater).isRelatedToEx(0x14097600900, 0x1404b6655e0, 0x14052114540, 0x3, 0x1, 0x1034ce260, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/relater.go:2662 +0x908
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkTypeRelatedToEx(0x1403ea2cc08, 0x1404b6655e0, 0x14052114540, 0x140302929c0, 0x140203dd7e8, 0x1034ce260, 0x140615c80c8)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/relater.go:371 +0x124
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkTypeAssignableToEx(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/relater.go:345
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkTypeArguments(0x1403ea2cc08, 0x140553bd200?, {0x140130d4048, 0x1, 0x1?}, 0x1, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:9111 +0x3c0
github.com/microsoft/typescript-go/internal/checker.(*Checker).getInstantiationExpressionType.func1.2(0x14055482100)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:10373 +0x40
github.com/microsoft/typescript-go/internal/core.SameMap[...]({0x1401f71e908, 0x88, 0x8f}, 0x140615c8200)
        /Users/andrew/Developer/microsoft/typescript-go/internal/core/core.go:131 +0x140
github.com/microsoft/typescript-go/internal/checker.(*Checker).getInstantiationExpressionType.func1({0x1404c93c008?, 0x1025fad84?, 0x140615c82b8?})
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:10372 +0x88
github.com/microsoft/typescript-go/internal/checker.(*Checker).getInstantiationExpressionType.func2.1(0x1404b939800)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:10388 +0x14c
github.com/microsoft/typescript-go/internal/checker.(*Checker).getInstantiationExpressionType.func2(0x1404b939800)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:10413 +0x6c
github.com/microsoft/typescript-go/internal/checker.(*Checker).getInstantiationExpressionType(0x1403ea2cc08, 0x1404b939800, 0x140203e26e0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:10422 +0x19c
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkExpressionWithTypeArguments(0x1403ea2cc08, 0x140203e26e0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:10354 +0x154
github.com/microsoft/typescript-go/internal/checker.(*Checker).getTypeFromTypeQueryNode(0x1403ea2cc08, 0x140203e26e0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:23542 +0x50
github.com/microsoft/typescript-go/internal/checker.(*Checker).getTypeFromTypeNodeWorker(0x140615c8568?, 0x1025b02d8?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:22368 +0x238
github.com/microsoft/typescript-go/internal/checker.(*Checker).getTypeFromTypeNode(0x1403ea2cc08, 0x140203e26e0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:22312 +0x24
github.com/microsoft/typescript-go/internal/checker.(*Checker).getReturnTypeFromAnnotation(0x1403ea2cc08, 0x14012f54f20)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:19571 +0x100
github.com/microsoft/typescript-go/internal/checker.(*Checker).hasTypePredicateOrNeverReturnType(0x1403ea2cc08, 0x1405515c400)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/flow.go:2177 +0x4c
github.com/microsoft/typescript-go/internal/core.Some[...](...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/core/core.go:164
github.com/microsoft/typescript-go/internal/checker.(*Checker).getEffectsSignature(0x1403ea2cc08, 0x14002a6f568)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/flow.go:2045 +0x214
github.com/microsoft/typescript-go/internal/checker.(*Checker).getTypeAtFlowCall(0x1403ea2cc08, 0x140111f2000, 0x1403e3f1048)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/flow.go:278 +0x2c
github.com/microsoft/typescript-go/internal/checker.(*Checker).getTypeAtFlowNode(0x1403ea2cc08, 0x140111f2000, 0x140614087d8?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/flow.go:149 +0x168
github.com/microsoft/typescript-go/internal/checker.(*Checker).getFlowTypeOfReferenceEx(0x1403ea2cc08, 0x1401f1b29e0, 0x14051e23440, 0x14051e23440, 0x1401f1c2708, 0x0?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/flow.go:97 +0x128
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkIdentifier(0x1403ea2cc08, 0x1401f1b29e0, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:10866 +0xc18
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkExpressionWorker(0x1403ea2cc08, 0x1401f1b29e0, 0x0?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:7522 +0x198
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkExpressionEx(0x1403ea2cc08, 0x1401f1b29e0, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:7352 +0x50
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkExpression(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:7345
github.com/microsoft/typescript-go/internal/checker.(*Checker).resolveCallExpression(0x1403ea2cc08, 0x140030efc68, 0x0, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:8347 +0xd8
github.com/microsoft/typescript-go/internal/checker.(*Checker).resolveSignature(0x1403ea2d3b0?, 0x102e60bc0?, 0x140030efc68?, 0x25e5a44?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:8310 +0x58
github.com/microsoft/typescript-go/internal/checker.(*Checker).getResolvedSignature(0x1403ea2cc08, 0x140030efc68, 0x0, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:8282 +0xd0
github.com/microsoft/typescript-go/internal/checker.(*Checker).getContextualTypeForArgumentAtIndex(0x1403ea2cc08, 0x140030efc68, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:28902 +0xc8
github.com/microsoft/typescript-go/internal/checker.(*Checker).getContextualTypeForArgument(0x1403ea2cc08, 0x140030efc68, 0x14002a6f808)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:28882 +0x80
github.com/microsoft/typescript-go/internal/checker.(*Checker).getContextualType(0x1403ea2cc08, 0x102ce06c0?, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:28484 +0x218
github.com/microsoft/typescript-go/internal/checker.(*Checker).inferTypeArguments(0x1403ea2cc08, 0x14002a6f808, 0x14060ec1d00, {0x1401ed23318, 0x1, 0x1}, 0xc, 0x14089f5f700)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:9278 +0xf8
github.com/microsoft/typescript-go/internal/checker.(*Checker).chooseOverload(0x1403ea2cc08, 0x140615c8e00, 0x14030292890)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:8916 +0x614
github.com/microsoft/typescript-go/internal/checker.(*Checker).resolveCall(0x1403ea2cc08, 0x14002a6f808, {0x140517f97c0, 0x4, 0x4}, 0x0, 0x0, 0x0, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:8768 +0x39c
github.com/microsoft/typescript-go/internal/checker.(*Checker).resolveCallExpression(0x1403ea2cc08, 0x14002a6f808, 0x0, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:8423 +0x4f8
github.com/microsoft/typescript-go/internal/checker.(*Checker).resolveSignature(0x1403ea2d3b0?, 0x102e60bc0?, 0x14002a6f808?, 0x25e5a44?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:8310 +0x58
github.com/microsoft/typescript-go/internal/checker.(*Checker).getResolvedSignature(0x1403ea2cc08, 0x14002a6f808, 0x0, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:8282 +0xd0
github.com/microsoft/typescript-go/internal/checker.(*Checker).getContextualTypeForArgumentAtIndex(0x1403ea2cc08, 0x14002a6f808, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:28902 +0xc8
github.com/microsoft/typescript-go/internal/checker.(*Checker).getContextualTypeForArgument(0x1403ea2cc08, 0x14002a6f808, 0x14004b1cfa0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:28882 +0x80
github.com/microsoft/typescript-go/internal/checker.(*Checker).getContextualType(0x1403ea2cc08, 0x10259fd9c?, 0x1)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:28484 +0x218
github.com/microsoft/typescript-go/internal/checker.(*Checker).getApparentTypeOfContextualType(0x1403ea2cc08, 0x14004b1cfa0, 0x1)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:29799 +0x78
github.com/microsoft/typescript-go/internal/checker.(*Checker).getContextualSignature(0x1403ea2cc08, 0x14004b1cfa0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:10077 +0x2c
github.com/microsoft/typescript-go/internal/checker.(*Checker).getContextuallyTypedParameterType(0x1403ea2cc08, 0x1401ed75958)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:28601 +0x8c
...6 frames elided...
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkIdentifier(0x1403ea2cc08, 0x1401f1b2ab8, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:10763 +0x1e0
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkExpressionWorker(0x1403ea2cc08, 0x1401f1b2ab8, 0x2c51140?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:7522 +0x198
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkExpressionEx(0x1403ea2cc08, 0x1401f1b2ab8, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:7352 +0x50
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkExpressionCachedEx(0x1403ea2cc08, 0x1401f1b2ab8, 0x1f1c2708?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:7321 +0xb0
github.com/microsoft/typescript-go/internal/checker.(*Checker).checkExpressionCached(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:7305
github.com/microsoft/typescript-go/internal/checker.(*Checker).markPropertyAliasReferenced(0x1403ea2cc08, 0x140022e3118, 0x0, 0x0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:27683 +0x1b0
github.com/microsoft/typescript-go/internal/checker.(*Checker).markLinkedReferences(0x1403ea2cc08, 0x140022e3118, 0x1f1a0049?, 0x140893b6cb8?, 0x14061409858?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/checker.go:27568 +0x3ec
github.com/microsoft/typescript-go/internal/checker.(*EmitResolver).MarkLinkedReferencesRecursively.func1(0x140022e3118)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/emitresolver.go:793 +0xac
github.com/microsoft/typescript-go/internal/ast.visit(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:22
github.com/microsoft/typescript-go/internal/ast.(*ArrowFunction).ForEachChild(0x14004b1cfa0, 0x140517d1ba8)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:6476 +0x168
github.com/microsoft/typescript-go/internal/ast.(*Node).ForEachChild(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:243
github.com/microsoft/typescript-go/internal/checker.(*EmitResolver).MarkLinkedReferencesRecursively.func1(0x14004b1cfa0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/emitresolver.go:794 +0xc4
github.com/microsoft/typescript-go/internal/ast.visitNodes(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:29
github.com/microsoft/typescript-go/internal/ast.visitNodeList(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:38
github.com/microsoft/typescript-go/internal/ast.(*CallExpression).ForEachChild(0x14002a6f808, 0x140517d1ba8)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:6867 +0x114
github.com/microsoft/typescript-go/internal/ast.(*Node).ForEachChild(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:243
github.com/microsoft/typescript-go/internal/checker.(*EmitResolver).MarkLinkedReferencesRecursively.func1(0x14002a6f808)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/emitresolver.go:794 +0xc4
github.com/microsoft/typescript-go/internal/ast.visitNodes(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:29
github.com/microsoft/typescript-go/internal/ast.visitNodeList(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:38
github.com/microsoft/typescript-go/internal/ast.(*CallExpression).ForEachChild(0x140030efc68, 0x140517d1ba8)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:6867 +0x114
github.com/microsoft/typescript-go/internal/ast.(*Node).ForEachChild(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:243
github.com/microsoft/typescript-go/internal/checker.(*EmitResolver).MarkLinkedReferencesRecursively.func1(0x140030efc68)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/emitresolver.go:794 +0xc4
github.com/microsoft/typescript-go/internal/ast.visitNodes(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:29
github.com/microsoft/typescript-go/internal/ast.visitNodeList(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:38
github.com/microsoft/typescript-go/internal/ast.(*CallExpression).ForEachChild(0x140030efcc8, 0x140517d1ba8)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:6867 +0x114
github.com/microsoft/typescript-go/internal/ast.(*Node).ForEachChild(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:243
github.com/microsoft/typescript-go/internal/checker.(*EmitResolver).MarkLinkedReferencesRecursively.func1(0x140030efcc8)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/emitresolver.go:794 +0xc4
github.com/microsoft/typescript-go/internal/ast.visit(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:22
github.com/microsoft/typescript-go/internal/ast.(*VariableDeclaration).ForEachChild(0x14002a6f8f0, 0x140517d1ba8)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:3786 +0xe4
github.com/microsoft/typescript-go/internal/ast.(*Node).ForEachChild(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:243
github.com/microsoft/typescript-go/internal/checker.(*EmitResolver).MarkLinkedReferencesRecursively.func1(0x14002a6f8f0)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/emitresolver.go:794 +0xc4
github.com/microsoft/typescript-go/internal/ast.visitNodes(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:29
github.com/microsoft/typescript-go/internal/ast.visitNodeList(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:38
github.com/microsoft/typescript-go/internal/ast.(*VariableDeclarationList).ForEachChild(0x1403ea2cc08?, 0x140517d1ba8)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:3836 +0x74
github.com/microsoft/typescript-go/internal/ast.(*Node).ForEachChild(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:243
github.com/microsoft/typescript-go/internal/checker.(*EmitResolver).MarkLinkedReferencesRecursively.func1(0x1401f19c840)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/emitresolver.go:794 +0xc4
github.com/microsoft/typescript-go/internal/ast.visit(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:22
github.com/microsoft/typescript-go/internal/ast.(*VariableStatement).ForEachChild(0x1403ea2cc08?, 0x1401ed36898?)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:3732 +0x68
github.com/microsoft/typescript-go/internal/ast.(*Node).ForEachChild(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:243
github.com/microsoft/typescript-go/internal/checker.(*EmitResolver).MarkLinkedReferencesRecursively.func1(0x1401ed36898)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/emitresolver.go:794 +0xc4
github.com/microsoft/typescript-go/internal/ast.visitNodes(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:29
github.com/microsoft/typescript-go/internal/ast.visitNodeList(...)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:38
github.com/microsoft/typescript-go/internal/ast.(*SourceFile).ForEachChild(0x1401f1c2708, 0x140517d1ba8)
        /Users/andrew/Developer/microsoft/typescript-go/internal/ast/ast.go:10887 +0xa4
github.com/microsoft/typescript-go/internal/checker.(*EmitResolver).MarkLinkedReferencesRecursively(0x14097134900, 0x1401f1c2708)
        /Users/andrew/Developer/microsoft/typescript-go/internal/checker/emitresolver.go:797 +0x114
github.com/microsoft/typescript-go/internal/compiler.getScriptTransformers(0x1409ad4bea0, {0x10df78760, 0x1409ac55530}, 0x1401f1c2708)
        /Users/andrew/Developer/microsoft/typescript-go/internal/compiler/emitter.go:90 +0x164
github.com/microsoft/typescript-go/internal/compiler.(*emitter).emitJSFile(0x1403bc97380, 0x1401f1c2708, {0x140016e6380, 0x69}, {0x0, 0x0})
        /Users/andrew/Developer/microsoft/typescript-go/internal/compiler/emitter.go:164 +0x100
github.com/microsoft/typescript-go/internal/compiler.(*emitter).emit(0x1403bc97380)
        /Users/andrew/Developer/microsoft/typescript-go/internal/compiler/emitter.go:47 +0x34
github.com/microsoft/typescript-go/internal/compiler.(*Program).Emit.func2()
        /Users/andrew/Developer/microsoft/typescript-go/internal/compiler/program.go:1439 +0x194
github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue.func1()
        /Users/andrew/Developer/microsoft/typescript-go/internal/core/workgroup.go:40 +0x24
sync.(*WaitGroup).Go.func1()
        /Users/andrew/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.darwin-arm64/src/sync/waitgroup.go:239 +0x4c
created by sync.(*WaitGroup).Go in goroutine 1
        /Users/andrew/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.darwin-arm64/src/sync/waitgroup.go:237 +0x70
```

## Steps to reproduce

1. `echo '{}' > tsconfig.all.json`
2. `tsgo -p tsconfig.all.json`

### PR DESCRIPTION
**Pull request by ahejlsberg**
With the repro steps in #2697, thousands of tests are treated as script files in a single program, causing some pretty extreme symbol merging. For example, functions named `foo` merge into a single symbol with some 135 overloads. The merging is pretty non-sensical and causes a lot of errors, but in some cases it also causes assertion panics and out-of-bounds accesses. This PR hardens the compiler as follows:

* The `fillMissingTypeArguments` function now ensures that the returned type argument list is always as long as the associated type parameter list in the target (the out-of-bounds accesses apparently didn't cause issues in Strada).
* The `createNormalizedTupleType` function now appropriately accounts for a possible extra type argument that represents the `this` type.
* An assertion in `evaluateEntity` was incorrect and would be triggered when enums merge across files.
* The parser would sometimes generate error spans that extended beyond the end of the source file.

Fixes #2697.

### CODE REVIEW

File: internal/scanner/scanner.go [hunk 1]
```diff
@@ -2442,14 +2442,16 @@ func GetECMALineStarts(sourceFile ast.SourceFileLike) []core.TextPos {
...
 }
 
 func GetECMALineAndCharacterOfPosition(sourceFile ast.SourceFileLike, pos int) (line int, character int) {
 	lineMap := GetECMALineStarts(sourceFile)
+	text := sourceFile.Text()
+	pos = max(0, min(pos, len(text)))
 	line = ComputeLineOfPosition(lineMap, pos)
 	// !!! TODO: this is suspect; these are rune counts, not UTF-8 _or_ UTF-16 offsets.
-	character = utf8.RuneCountInString(sourceFile.Text()[lineMap[line]:pos])
+	character = utf8.RuneCountInString(text[lineMap[line]:pos])
```
Comment (jakebailey) [inline internal/scanner/scanner.go]: I really wish we didn't have to do this; clamping the inputs is most certainly just masking bugs elsewhere... But I know these funcs are all wrong and ill-defined too, so...

Comment (andrewbranch) [reply internal/scanner/scanner.go]: Yeah, what was the root cause of looking out of bounds here?

Comment (ahejlsberg) [reply internal/scanner/scanner.go]: The root cause was an error span generated in the parser generated without a bounds check. That span in turn was passed to `GetECMALineAndCharacterOfPosition` when pretty-printing an error message. I'll fix the issue in the parser and remove the clamping logic.

File: internal/parser/parser.go [hunk 2]
```diff
@@ -863,7 +863,7 @@ func (p *Parser) parseExpectedMatchingBrackets(openKind ast.Kind, closeKind ast.
 		return
 	}
 	if lastError != nil {
-		related := ast.NewDiagnostic(nil, core.NewTextRange(openPosition, openPosition+1), diagnostics.The_parser_expected_to_find_a_1_to_match_the_0_token_here, scanner.TokenToString(openKind), scanner.TokenToString(closeKind))
+		related := ast.NewDiagnostic(nil, core.NewTextRange(openPosition, openPosition), diagnostics.The_parser_expected_to_find_a_1_to_match_the_0_token_here, scanner.TokenToString(openKind), scanner.TokenToString(closeKind))
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply internal/parser/parser.go:866]: The zero length span is intended. We do that in many places elsewhere, and highlighting logic already handles.

File: internal/checker/checker.go [hunk 3]
```diff
@@ -22787,15 +22787,20 @@ func (c *Checker) createNormalizedTupleType(target *Type, elementTypes []*Type)
...
+	// In either layout, zero or more generic variadic elements may be present at any location.
+	// Note that the element types may contain an extra 'this' type argument that we want to ignore during normalization
+	// and then just append to the normalized element types.
 	n := &TupleNormalizer{}
-	if !n.normalize(c, elementTypes, d.elementInfos) {
+	if !n.normalize(c, elementTypes[:len(d.elementInfos)], d.elementInfos) {
 		return c.errorType
 	}
+	if len(elementTypes) > len(d.elementInfos) {
+		n.types = append(n.types, elementTypes[len(d.elementInfos)])
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply internal/checker/checker.go:22802]: It would be a logic error for `elementTypes` to be shorter than `elementInfos`, so we don't want to do that.

**Comment by ahejlsberg** [comment]
Copilot likes clamping. 😄

File: internal/parser/parser.go (hunk 2 above)
Comment (andrewbranch) [inline internal/parser/parser.go:866]: Wait, this didn't cause a baseline change? How is that possible?

Comment (ahejlsberg) [reply internal/parser/parser.go:866]: Because the baselines don't pretty-print errors.

Comment (jakebailey) [reply internal/parser/parser.go:866]: The baseliner and editors treat zero length diagnostics as one-length diagnostics at that specific point, so I wouldn't expect either to observe a difference, unless we had a test which did actually put it out of range at the end of a file
