### PR TITLE
Expose bind diags in LSP, show dead/deprecated code

### LINKED ISSUE #941: tsgo does not detect unreachable code
#### Reproduction Steps

1. Follow the setup instructions from this blog post to enable `tsgo` in VSCode(if you haven't already):  
   https://devblogs.microsoft.com/typescript/announcing-typescript-native-previews/

2. Create a `.ts` file and add the following code:

   ```ts
   function doSomethingAwesome() {
     throw new Error("we messed up");
     return [];
   }

#### Expected Behavior
The return statement should be reported as unreachable when it follows a throw

#### Actual Behavior
No unreachable code warning is shown.


#### Environment 

- **@typescript/native-preview version:** `7.0.0-dev.20250525.1`
- **Node.js version:** `v20.18.2`
- **OS:** Ubuntu 24.04 (if applicable)

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #941

image

### CODE REVIEW

**Review by gabritto — APPROVED** [review]

File: internal/ls/diagnostics.go [hunk 1]
```diff
@@ -13,17 +13,24 @@ func (l *LanguageService) GetDocumentDiagnostics(ctx context.Context, documentUR
...
-		lspDiagnostics = make([]*lsproto.Diagnostic, len(syntaxDiagnostics))
-		for i, diag := range syntaxDiagnostics {
-			lspDiagnostics[i] = toLSPDiagnostic(diag, l.converters)
+		lspDiagnostics = make([]*lsproto.Diagnostic, 0, len(syntaxDiagnostics))
+		for _, diag := range syntaxDiagnostics {
+			lspDiagnostics = append(lspDiagnostics, toLSPDiagnostic(diag, l.converters))
 		}
 	} else {
+		// !!! suggestion diagnostics?
+		// !!! In Strada, we consolidate bind/check errors into semantic diagnostics rather than
```
Comment (gabritto) [inline internal/ls/diagnostics.go]: Wait, we already consolidate them in `program.GetSemanticDiagnostics()`. Why are we not using it here? Is it because of the multiple checkers thing?

Comment (jakebailey) [reply internal/ls/diagnostics.go]: The code below asks for a checker and asks it for diagnostics directly, so nothing here is asking for them anymore.

Comment (gabritto) [reply internal/ls/diagnostics.go]: Yes, but why can't it all be replaced by `program.GetSemanticDiagnostics(ctx, file)`?

Comment (jakebailey) [reply internal/ls/diagnostics.go]: I had thought becuase `getSemanticDiagnosticsForFile` loops through all the checkers, and we can't do that in the LSP. But I see now that it might actually work fine as it will return just the context's checker. Let me give it a try.

Comment (jakebailey) [reply internal/ls/diagnostics.go]: Seems to be fine, yeah. Thanks.

Unfortunately, this PR doesn't seem to be complete and doesn't work when `allowUnreachableCode` is unset (no darkened text), so will have to figure that out.

Comment (jakebailey) [reply internal/ls/diagnostics.go]: Oh, because that's also a suggestion diagnostic. Yay.

Comment (jakebailey) [reply internal/ls/diagnostics.go]: Okay, that wasn't that hard.

File: internal/compiler/program.go [hunk 2]
```diff
@@ -452,6 +456,39 @@ func (p *Program) getSemanticDiagnosticsForFile(ctx context.Context, sourceFile
 	return filtered
 }
 
+func (p *Program) getSuggestionDiagnosticsForFile(ctx context.Context, sourceFile *ast.SourceFile) []*ast.Diagnostic {
```
Comment (jakebailey) [inline internal/compiler/program.go:459]: This all is pretty duplicative but I'm not about to attempt to refactor it into some generic version, honestly.
