### PR TITLE
Display JSDoc documentation in Quick Info

### LINKED ISSUE #992: Bad error in JSDoc type, crashes hover
In `Herebyfile.mjs`, I wrote:

```
/**
 * @type {{ [K in keyof typeof rawOptions as {} extends Record<K, 1> ? never : K]: typeof rawOptions[K] }}
 */
const options = rawOptions;
```

Image

This has a spurious error.

But, hovering over `K` to try and read the error causes a hover, which crashes the server!

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x793171]

goroutine 175 [running]:
github.com/microsoft/typescript-go/internal/ast.(*Node).AsTypeAliasDeclaration(...)
	github.com/microsoft/typescript-go/internal/ast/ast.go:1196
github.com/microsoft/typescript-go/internal/checker.(*Checker).getDeclaredTypeOfTypeAlias(0xc002dd5008, 0xc003175428)
	github.com/microsoft/typescript-go/internal/checker/checker.go:22244 +0xd1
github.com/microsoft/typescript-go/internal/checker.(*Checker).tryGetDeclaredTypeOfSymbol(0x847100?, 0xc0043a0b40?)
	github.com/microsoft/typescript-go/internal/checker/checker.go:22083 +0x66
github.com/microsoft/typescript-go/internal/checker.(*Checker).getDeclaredTypeOfSymbol(...)
	github.com/microsoft/typescript-go/internal/checker/checker.go:22069
github.com/microsoft/typescript-go/internal/checker.(*Checker).GetTypeAliasTypeParameters(0xc002dd5008, 0xc003175428)
	github.com/microsoft/typescript-go/internal/checker/checker.go:1144 +0x26
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideHover(0xc008a04c90, {0xc3a0b0, 0xc008b000f0}, {0xc008b14080?, 0xc0002e96b0?}, {0x5be31f?, 0x0?})
	github.com/microsoft/typescript-go/internal/ls/hover.go:147 +0x10c5
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleHover(0xc00011ab60, {0xc3a0b0, 0xc008b000f0}, 0xc008b08240)
	github.com/microsoft/typescript-go/internal/lsp/server.go:531 +0xcd
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x8a7552?, {0xc3a0b0?, 0xc008b000f0?}, 0xc002087088?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:400 +0x125
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:283 +0x3a
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 34
	github.com/microsoft/typescript-go/internal/lsp/server.go:301 +0x82a
[Info  - 9:36:34 AM] Connection to server got closed. Server will restart.
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we now include JSDoc documentation when hovering over code elements:

image

This PR also fixes several language service crashes, including #992.

Fixes #992.

### CODE REVIEW

**Comment by jakebailey** [comment]
I was bad and #992 was an issue that should have been two; I assume the crash is what's fixed, not the actual bad type error?

**Comment by ahejlsberg** [comment]
> I was bad and https://github.com/microsoft/typescript-go/issues/992 was an issue that should have been two; I assume the crash is what's fixed, not the actual bad type error?

Right, this PR just fixes the crash.

File: internal/checker/types.go [hunk 1]
```diff
@@ -63,6 +63,7 @@ const (
 	TypeFormatFlagsUseSingleQuotesForStringLiteralType TypeFormatFlags = 1 << 28 // Use single quotes for string literal type
 	TypeFormatFlagsNoTypeReduction                     TypeFormatFlags = 1 << 29 // Don't call getReducedType
 	TypeFormatFlagsOmitThisParameter                   TypeFormatFlags = 1 << 25
+	TypeFormatFlagsWriteCallStyleSignature             TypeFormatFlags = 1 << 26 // Write construct signatures as call style signatures
```
Comment (jakebailey) [inline internal/checker/types.go]: Modifying `TypeFormatFlags` should also require updating `nodebuilder.Flags` (we are missing the comment on `TypeFormatFlags` from Strada that says to keep them in sync).

File: internal/ls/hover.go [hunk 2]
```diff
@@ -52,143 +26,367 @@ func (l *LanguageService) ProvideHover(ctx context.Context, documentURI lsproto.
...
+		b.WriteString(prefix)
+		b.WriteString(c.SymbolToStringEx(symbol, nil, ast.SymbolFlagsNone, symbolFormatFlags))
+		b.WriteString(c.SignatureToStringEx(sig, nil, typeFormatFlags|checker.TypeFormatFlagsWriteCallStyleSignature))
+	}
+}
+
+func formatQuickInfoAndJSDoc(quickInfo string, declaration *ast.Node) string {
+	var b strings.Builder
+	b.Grow(32)
+	writeCode(&b, "ts", quickInfo)
```
Comment (jakebailey) [inline internal/ls/hover.go]: Should this be `tsx` to match the old tooltips?

File: internal/checker/types.go (hunk 1 above)
Comment (jakebailey) [reply internal/checker/types.go]: Curious, why does Strada not need this to get the same hover?

Comment (ahejlsberg) [reply internal/checker/types.go]: Strada directly calls the lower level helper that `SignatureToString` uses. Didn't want to expose more methods, thought it was better to just have another format flag.

File: internal/ls/hover.go (hunk 2 above)
Comment (ahejlsberg) [reply internal/ls/hover.go]: Yeah, I'll fix.

File: internal/checker/types.go [hunk 3]
```diff
@@ -63,7 +63,7 @@ const (
 	TypeFormatFlagsUseSingleQuotesForStringLiteralType TypeFormatFlags = 1 << 28 // Use single quotes for string literal type
 	TypeFormatFlagsNoTypeReduction                     TypeFormatFlags = 1 << 29 // Don't call getReducedType
 	TypeFormatFlagsOmitThisParameter                   TypeFormatFlags = 1 << 25
-	TypeFormatFlagsWriteCallStyleSignature             TypeFormatFlags = 1 << 26 // Write construct signatures as call style signatures
+	TypeFormatFlagsWriteCallStyleSignature             TypeFormatFlags = 1 << 27 // Write construct signatures as call style signatures
```
Comment (ahejlsberg) [inline internal/checker/types.go:66]: The value `26` was already in use in the other flags definitions.

**Review by jakebailey — APPROVED** [review]

**Comment by jakebailey** [comment]
ATA test flake :(
