### PR TITLE
fix(2681): prevent nil parent context in import-attributes

### LINKED ISSUE #2681: textDocument/completion: runtime error: invalid memory address or nil pointer dereference
## Stack trace

```
2026-02-04 18:34:24.187 [error] panic handling request textDocument/completion: runtime error: invalid memory address or nil pointer dereference
goroutine 1268 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x64
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x4000188e08, {0x861a0?, 0x4003bfea80?}, 0x4005b03980)
	github.com/microsoft/typescript-go/internal/lsp/server.go:784 +0x40
panic({0x78fa80?, 0x12d5a00?})
	runtime/panic.go:783 +0x120
github.com/microsoft/typescript-go/internal/ast.IsImportAttributes(...)
	github.com/microsoft/typescript-go/internal/ast/ast.go:8277
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData.func12()
	github.com/microsoft/typescript-go/internal/ls/completions.go:1214 +0x6c
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData.func18(...)
	github.com/microsoft/typescript-go/internal/ls/completions.go:1548
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData(0x4005ab74c0, {0xc58a08, 0x4005ba9260}, 0x40035b4008, 0x4005aa6008, 0x10b, 0x4004ded700)
	github.com/microsoft/typescript-go/internal/ls/completions.go:1581 +0x16d8
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionsAtPosition(0x4005ab74c0, {0xc58a08, 0x4005ba9260}, 0x4005aa6008, 0x10b, 0x0)
	github.com/microsoft/typescript-go/internal/ls/completions.go:347 +0x26c
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideCompletion(0x4005ab74c0, {0xc58a08, 0x4005ba91a0}, {0x4002d16260?, 0x4005ba91a0?}, {0x2d16260?, 0x40?}, 0x400274af80)
	github.com/microsoft/typescript-go/internal/ls/completions.go:47 +0x204
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleCompletion(0xfe063297b1f45bb7?, {0xc58a08?, 0x4005ba91a0?}, 0x4002d16260?, 0xffffa53943e8?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:1112 +0x3c
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceWithAutoImportsRequestHandler[...].28({0xc58a08, 0x4005ba91a0}, 0x4005b03980)
	github.com/microsoft/typescript-go/internal/lsp/server.go:689 +0xf4
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x4000188e08, {0xc58a40?, 0x4005a8b2c0?}, 0x4005b03980)
	github.com/microsoft/typescript-go/internal/lsp/server.go:534 +0xc8
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:413 +0x34
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 11
	github.com/microsoft/typescript-go/internal/lsp/server.go:437 +0x7d8

2026-02-04 18:34:24.188 [error] Request textDocument/completion failed.
  Message: InternalError: panic handling request textDocument/completion: runtime error: invalid memory address or nil pointer dereference
  Code: -32603
```

## Steps to reproduce

Crashed as I was typing where the `/*$*/` is. It keeps crashing as I continue typing there, too, but stops crashing if I rename the `enum` variable.

```typescript
import type * as zenstack from '@zenstackhq/schema'
import type * as dmmf from '@prisma/dmmf'

export function convertSchema<
Schema extends zenstack.SchemaDef
>(schema: Schema): dmmf.Schema {
  return {
    enumTypes: [],
  }
}

export function convertEnum<>(enum: /*$*/) {

}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #2681

### CODE REVIEW

File: internal/fourslash/tests/completionColonToken_test.go [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+		IsIncomplete: false,
+		ItemDefaults: &fourslash.CompletionsExpectedItemDefaults{
+			CommitCharacters: &DefaultCommitCharacters,
+			EditRange:        Ignored,
+		},
+		Items: &fourslash.CompletionsExpectedItems{
+			Includes: CompletionGlobals,
+		},
+	})
+}
```
Comment (DanielRosenwasser) [inline internal/fourslash/tests/completionColonToken_test.go]: Can you loop through the markers instead?

File: internal/ls/completions.go [hunk 2]
```diff
@@ -1206,15 +1206,22 @@ func (l *LanguageService) getCompletionData(
...
+			return globalsSearchContinue, nil
 		}
 
-		if importAttributes == nil {
+		var importAttributes *ast.ImportAttributesNode
+		if ast.IsImportAttributes(parent) {
+			importAttributes = parent
+		} else {
 			return globalsSearchContinue, nil
 		}
```
Comment (DanielRosenwasser) [inline internal/ls/completions.go]:
```suggestion
		if !ast.IsImportAttributes(parent) {
			return globalsSearchContinue, nil
		}

		importAttributes := parent.AsImportAttributes()
```

Then update usages below.

Other nits: would prefer a different name than `parent` (`possibleImportAttributes`?).

**Review by DanielRosenwasser — APPROVED** [review]
