### PR TITLE
Fix leading source file comment emit bugs

### LINKED ISSUE #1526: Emit adds generated code before file header/copyright comment
## Steps to reproduce

Compile a ts file with a copyright comment:

```ts
/*---------------------------------------------------------------------------------------------
 *  Copyright
 *--------------------------------------------------------------------------------------------*/

export const a = 1;
```

## Behavior with `typescript@5.8`

The generated helpers and module code is added after the comment:

```js
"use strict";
/*---------------------------------------------------------------------------------------------
 *  Copyright
 *--------------------------------------------------------------------------------------------*/
Object.defineProperty(exports, "__esModule", { value: true });
exports.a = void 0;
exports.a = 1;
```

## Behavior with `tsgo`
The copyright comment after the added code:

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.a = void 0;
/*---------------------------------------------------------------------------------------------
 *  Copyright
 *--------------------------------------------------------------------------------------------*/
exports.a = 1;
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #1526

#1938 sort of found the right area but I found some misports that fix way more baselines still.

### CODE REVIEW

File: internal/printer/printer.go [hunk 1]
```diff
@@ -5083,7 +5087,7 @@ func (p *Printer) emitDetachedCommentsBeforeStatementList(node *ast.Node, detach
 	containerPos := p.containerPos
 	containerEnd := p.containerEnd
 	declarationListContainerEnd := p.declarationListContainerEnd
-	skipLeadingComments := emitFlags&EFNoLeadingComments == 0 && !ast.PositionIsSynthesized(detachedRange.Pos())
+	skipLeadingComments := ast.PositionIsSynthesized(detachedRange.Pos()) || emitFlags&EFNoLeadingComments != 0
```
Comment (jakebailey) [inline internal/printer/printer.go:5092]: This was a porting bug.

File: internal/printer/printer.go [hunk 2]
```diff
@@ -4384,14 +4384,18 @@ func (p *Printer) emitSourceFile(node *ast.SourceFile) {
...
 	p.generateAllNames(node.Statements)
 
 	index := 0
+	var state *commentState
 	if node.ScriptKind != core.ScriptKindJSON {
 		p.emitShebangIfNeeded(node)
 		index = p.emitPrologueDirectives(node.Statements)
+		if !p.writer.IsAtStartOfLine() {
+			p.writeLine()
+		}
```
Comment (jakebailey) [inline internal/printer/printer.go:4397]: This is required. I am not sure where Strada did this particular newline.

**Review by DanielRosenwasser — APPROVED** [review]

File: internal/printer/printer.go (hunk 2 above)
Comment (weswigham) [reply internal/printer/printer.go:4397]: The first line of `emitSourceFile` is an unconditional `writeLine`, which is after `writeFile`'s `emitShebangIfNeeded` and `emitPrologueDirectivesIfNeeded` calls. Which puts this in exactly the right place.

File: internal/printer/printer.go [hunk 3]
```diff
@@ -4384,18 +4384,24 @@ func (p *Printer) emitSourceFile(node *ast.SourceFile) {
...
+		state = p.emitDetachedCommentsBeforeStatementList(node.AsNode(), node.Statements.Loc)
 		p.emitHelpers(node.AsNode())
 		if node.IsDeclarationFile {
 			p.emitTripleSlashDirectives(node)
 		}
+	} else {
```
Comment (weswigham) [inline internal/printer/printer.go:4403]: I don't think a JSON document will ever have detached leading comments (since it only ever has one statement and no prologues), so this *could* probably be a hardcoded initial empty comment emit state, but it's probably fine.

File: internal/printer/printer.go (hunk 1 above)
Comment (weswigham) [reply internal/printer/printer.go:5092]: the ol' "let's invert this condition" and then fail to invert the usage/name.

File: internal/printer/printer.go (hunk 3 above)
Comment (jakebailey) [reply internal/printer/printer.go:4403]: Yeah, no test change when I added this back (nil is fine), but since the original code did this unconditionally (both codebases) I thought I would add it back. I bet we just don't have any tests which reprint a JSON file without downleveling it...
