### PR TITLE
Fix BigInt handling

### LINKED ISSUE #494: bigints in template literal strings not working
```ts
// Type '"5"' is not assignable to type '`${bigint}`'.
const s: `${bigint}` = "5"
// evaluates to error type
type parsed = "5" extends `${bigint}` ? true : false
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #494

### CODE REVIEW

File: internal/jsnum/pseudobigint.go [hunk 1]
```diff
@@ -25,3 +31,37 @@ func (value PseudoBigInt) Sign() int {
...
+			return "0"
+		}
+		return stringValue
+	}
+
+	bi, ok := new(big.Int).SetString(stringValue, 0)
+	if !ok {
+		panic(fmt.Sprintf("Failed to parse big int: %q", stringValue))
+	}
+	return bi.String() // !!!
```
Comment (jakebailey) [inline internal/jsnum/pseudobigint.go:66]: My super lazy way of not porting all of `ParsePseudoBigInt` right now. The Go bigint parser works fine for these.

File: internal/jsnum/pseudobigint_test.go [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+				assert.Equal(
+					t,
+					ParsePseudoBigInt(strings.Repeat("0", leadingZeros)+testNumber.String()+"n"),
+					testNumber.String(),
+				)
+			}
+		}
+	})
+
+	// TODO(jakebailey): tests for other bases
```
Comment (jakebailey) [inline internal/jsnum/pseudobigint_test.go:34]: The other test cases here depend on being run in JS where we can convert number to string with multiple bases, something jsnum can't do right now. I might try my hand at that quick, though.

File: testdata/baselines/reference/submodule/conformance/templateLiteralTypes4.types.diff [hunk 3]
```diff
@@ -47,28 +47,23 @@
  
  // infer from bigint
  type TBigInt0 = "100" extends `${infer N extends bigint}` ? N : never; // 100n
-->TBigInt0 : 100n
-+>TBigInt0 : never
+ >TBigInt0 : 100n
 +>N : N
```
Comment (jakebailey) [inline testdata/baselines/reference/submodule/conformance/templateLiteralTypes4.types.diff]: Noticed these and then figured out #663, yay!

File: testdata/baselines/reference/submodule/conformance/templateLiteralTypesPatterns.errors.txt.diff [hunk 4]
```diff
@@ -81,27 +77,15 @@
...
-+!!! error TS2345: Argument of type '"0x1"' is not assignable to parameter of type '`${bigint}`'.
-     bigints("0o1");
-+            ~~~~~
-+!!! error TS2345: Argument of type '"0o1"' is not assignable to parameter of type '`${bigint}`'.
+@@= skipped -133, +133 lines =@@
+     
+     // whitespace and comments aren't part of numbers
+     bigints("- 1");
+-            ~~~~~
+-!!! error TS2345: Argument of type '"- 1"' is not assignable to parameter of type '`${bigint}`'.
```
Comment (jakebailey) [inline testdata/baselines/reference/submodule/conformance/templateLiteralTypesPatterns.errors.txt.diff:85]: This is missing; will investigate to figure out where this goes wrong.

Comment (jakebailey) [reply testdata/baselines/reference/submodule/conformance/templateLiteralTypesPatterns.errors.txt.diff:85]: It turns out our scanner doesn't respect skipTrivia in all of the places it's supposed to.

**Comment by jakebailey** [comment]
I'm going to undraft this; the scanner fixes are very, very invasive. We've apparently never set skipTrivia=false so all of that code was untested and incorrect.

File: internal/jsnum/pseudobigint_test.go [hunk 5]
```diff
@@ -0,0 +1,43 @@
...
+
+	t.Run("can parse large literals", func(t *testing.T) {
+		t.Parallel()
+		assert.Equal(t, ParsePseudoBigInt("123456789012345678901234567890n"), "123456789012345678901234567890")
+		assert.Equal(t, ParsePseudoBigInt("0b1100011101110100100001111111101101100001101110011111000001110111001001110001111110000101011010010n"), "123456789012345678901234567890")
```
Comment (sandersn) [inline internal/jsnum/pseudobigint_test.go:39]: what happens if one of the binary-format numbers has a non `01` (and the same for octal and decimal, too)?

Edit: Oh, the Go bigint parser receives the prefix as well, so should fail.

File: internal/jsnum/pseudobigint.go [hunk 6]
```diff
@@ -25,3 +31,37 @@ func (value PseudoBigInt) Sign() int {
...
+	return PseudoBigInt{
+		Negative:    negative,
+		Base10Value: ParsePseudoBigInt(text),
+	}
+}
+
+func ParsePseudoBigInt(stringValue string) string {
+	stringValue = strings.TrimSuffix(stringValue, "n")
+
+	var b1 byte
```
Comment (sandersn) [inline internal/jsnum/pseudobigint.go:46]: minor, but: having names `b1 bi big` in the same small space is way too hard to read.

Edit: good chance to promote https://www.codingfont.com/

File: internal/jsnum/pseudobigint.go (hunk 1 above)
Comment (sandersn) [reply internal/jsnum/pseudobigint.go:66]: seems reasonable. wait, does this do base conversion from binary etc to decimal? Or does it just roundtrip whatever was written? The TODO comment in scanner.go implies the former.

Edit: And all the baseline changes.

**Review by sandersn — APPROVED** [review]
Looks good with one naming complaint. I left in my other questions that I had as I read, but they were all answered.

File: internal/jsnum/pseudobigint_test.go (hunk 5 above)
Comment (jakebailey) [reply internal/jsnum/pseudobigint_test.go:39]: The original parse function always succeeded, so I don't think we are actually needing to deal with this case; the code actually strips leading zeros.

File: internal/jsnum/pseudobigint.go (hunk 1 above)
Comment (jakebailey) [reply internal/jsnum/pseudobigint.go:66]: Yes, it does base conversion. The original TS code does some fancy stuff with Uint16Buffer that I don't really want to muck around with when Go gets this correct enough to parse out valid bigints, which is all this code works on.
