### PR TITLE
Fix for Signature help crash

### LINKED ISSUE #1435: Signature help crashes at any location with no signature
Probably related to all the other signature help crashes, but worth adding a test.

```
let x = /**/
```

## Steps to reproduce

1. Request signature help
2. Crash

```
panic handling request textDocument/signatureHelp runtime error: invalid memory address or nil pointer dereference goroutine 1512 [running]:
runtime/debug.Stack()
	/home/daniel/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25rc1.linux-arm64/src/runtime/debug/stack.go:26 +0x64
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1.1()
	/home/daniel/typescript-go/internal/lsp/server.go:357 +0x50
panic({0x5ee320?, 0xe2de00?})
	/home/daniel/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25rc1.linux-arm64/src/runtime/panic.go:783 +0x120
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).GetSignatureHelpItems(0x4001f40210?, {0x8f3dd0?, 0x4006111770?}, 0x8, 0x7a2021?, 0x40075f0848, 0x0, 0x40002aacf0, 0x4005dbf880?)
	/home/daniel/typescript-go/internal/ls/signaturehelp.go:77 +0x88
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideSignatureHelp(0x4007ed7bf0, {0x8f3dd0, 0x4006111770}, {0x4002f154d0?, 0x400249cb40?}, {0x6bb320?, 0x0?}, 0x0, 0x40002aacf0, 0x4004b69e70)
	/home/daniel/typescript-go/internal/ls/signaturehelp.go:47 +0x98
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleSignatureHelp(0x400017ea20, {0x8f3dd0, 0x4006111770}, 0x4008332810)
	/home/daniel/typescript-go/internal/lsp/server.go:684 +0xd4
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x4003065f68?, {0x8f3dd0?, 0x4006111770?}, 0x48dc30?)
	/home/daniel/typescript-go/internal/lsp/server.go:494 +0x94
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	/home/daniel/typescript-go/internal/lsp/server.go:370 +0x60
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 19
	/home/daniel/typescript-go/internal/lsp/server.go:388 +0x448
```

### LINKED ISSUE #1467: Frequent vscode error - panic handling request textDocument/signatureHelp: runtime error: invalid memory address or nil pointer dereference
The extension is alot more stable, the below error doesn't stop the extension working any more, but its still annoying that it pops up pretty often. I didn't find an equivalent issue and I think it might be new. Running the latest extension 0727.1

## Stack trace

```
Info 106  [19:23:25.288] Finishing updateGraph: Project: c:/Projects/x/y/src/ui/tsconfig.json version: 8 in 40.6µs
panic handling request textDocument/signatureHelp runtime error: invalid memory address or nil pointer dereference goroutine 200983 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1.1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:361 +0x5d
panic({0x1434360?, 0x1cbc3c0?})
	runtime/panic.go:792 +0x132
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).GetSignatureHelpItems(0xc032ec0978?, {0x174f6d0?, 0xc0a40e8f00?}, 0x596, 0x15f6425?, 0xc07ff5b608, 0x0, 0xc0000099c8, 0xc081837a40?)
	github.com/microsoft/typescript-go/internal/ls/signaturehelp.go:78 +0xa8
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideSignatureHelp(0xc032ec0990, {0x174f6d0, 0xc0a40e8f00}, {0xc07c0a0c00?, 0x14c0440?}, {0x88741e60?, 0xc0?}, 0x0, 0xc0000099c8, 0xc088741e78)
	github.com/microsoft/typescript-go/internal/ls/signaturehelp.go:47 +0xba
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleSignatureHelp(0xc00019ca20, {0x174f6d0, 0xc0a40e8f00}, 0xc0a7c78ed0)
	github.com/microsoft/typescript-go/internal/lsp/server.go:701 +0xfb
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerRequestHandler[...].17({0x174f6d0, 0xc0a40e8f00}, 0xc0a7c79020)
	github.com/microsoft/typescript-go/internal/lsp/server.go:533 +0x6d
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0xc00019ca20, {0x174f6d0, 0xc0a40e8f00}, 0xc0a7c79020)
	github.com/microsoft/typescript-go/internal/lsp/server.go:469 +0x10d
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:374 +0x75
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 9
	github.com/microsoft/typescript-go/internal/lsp/server.go:394 +0x4d2

[Error - 7:23:25 PM] Request textDocument/signatureHelp failed.
  Message: InternalError: panic handling request textDocument/signatureHelp: runtime error: invalid memory address or nil pointer dereference
  Code: -32603 
```

## Steps to reproduce

I seem to get this all the time editing a file.

### PR DESCRIPTION
**Pull request by navya9singh**
This was crashing every time that the `context` was `nil`. 

Fixes #1435
Fixes #1467

### CODE REVIEW

**Review by jakebailey — APPROVED** [review]

**Comment by navya9singh** [comment]
I changed 1 check here. It should have been `context != nil && context.TriggerKind == 1` and not `context == nil || context.TriggerKind == 1`

**Review by jakebailey — APPROVED** [review]

File: internal/ls/signaturehelp.go [hunk 1]
```diff
@@ -75,14 +75,14 @@ func (l *LanguageService) GetSignatureHelpItems(
...
-	onlyUseSyntacticOwners := context.TriggerKind == lsproto.SignatureHelpTriggerKindTriggerCharacter
+	onlyUseSyntacticOwners := context != nil && context.TriggerKind == lsproto.SignatureHelpTriggerKindTriggerCharacter
 
 	// Bail out quickly in the middle of a string or comment, don't provide signature help unless the user explicitly requested it.
 	if onlyUseSyntacticOwners && IsInString(sourceFile, position, startingToken) { // isInComment(sourceFile, position) needs formatting implemented
 		return nil
 	}
 
-	isManuallyInvoked := context.TriggerKind == 1
+	isManuallyInvoked := context != nil && context.TriggerKind == 1
```
Comment (DanielRosenwasser) [inline internal/ls/signaturehelp.go]: Why are we just explicitly checking the value `1`?

Comment (navya9singh) [reply internal/ls/signaturehelp.go]: It just represents SignatureHelpTriggerKindInvoked

Comment (jakebailey) [reply internal/ls/signaturehelp.go]: Right, I think he was asking why this isn't `context.TriggerKind == lsproto.SignatureHelpTriggerKindInvoked`

**Review by jakebailey — APPROVED** [review]
