### PR TITLE
Fix race in snapshotFSBuilder.FileExists()

### LINKED ISSUE #3148: Data race between GetFileByPath and MatchesDiskText
Saw this in CI:

```
==================
WARNING: DATA RACE
Write at 0x00c028df53a0 by goroutine 152090:
  github.com/microsoft/typescript-go/internal/project.(*snapshotFSBuilder).reloadEntryIfNeeded.func2.1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/snapshotfs.go:341 +0x105
  github.com/microsoft/typescript-go/internal/project/dirty.(*SyncMapEntry[go.shape.string,go.shape.*uint8]).changeLocked()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:105 +0x3a7
  github.com/microsoft/typescript-go/internal/project/dirty.(*lockedEntry[go.shape.string,go.shape.*uint8]).Change()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:27 +0x64
  github.com/microsoft/typescript-go/internal/project/dirty.(*lockedEntry[github.com/microsoft/typescript-go/internal/tspath.Path,*github.com/microsoft/typescript-go/internal/project.diskFile]).Change()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:26 +0xe
  github.com/microsoft/typescript-go/internal/project.(*snapshotFSBuilder).reloadEntryIfNeeded.func2()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/snapshotfs.go:338 +0x10d
  github.com/microsoft/typescript-go/internal/project/dirty.(*SyncMapEntry[go.shape.string,go.shape.*uint8]).Locked()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:90 +0x13c
  github.com/microsoft/typescript-go/internal/project.(*snapshotFSBuilder).reloadEntryIfNeeded()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/snapshotfs.go:333 +0x15d
  github.com/microsoft/typescript-go/internal/project.(*snapshotFSBuilder).getDiskFile()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/snapshotfs.go:286 +0x111
  github.com/microsoft/typescript-go/internal/project.(*snapshotFSBuilder).GetFileByPath()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/snapshotfs.go:267 +0xd1
  github.com/microsoft/typescript-go/internal/project.(*sourceFS).GetFileByPath()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/snapshotfs.go:568 +0x82
  github.com/microsoft/typescript-go/internal/project.(*compilerHost).GetSourceFile()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/compilerhost.go:97 +0xf5
  github.com/microsoft/typescript-go/internal/compiler.(*fileLoader).parseSourceFile()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/fileloader.go:294 +0x252
  github.com/microsoft/typescript-go/internal/compiler.(*parseTask).load()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/filesparser.go:105 +0x7af
  github.com/microsoft/typescript-go/internal/compiler.(*filesParser).start.func1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/filesparser.go:252 +0x615
  github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue.func1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/core/workgroup.go:40 +0x2e
  sync.(*WaitGroup).Go.func1()
      /home/cloudtest/.local/share/microsoft-go/go1.26.1-1/src/sync/waitgroup.go:258 +0x5d

Previous read at 0x00c028df53a0 by goroutine 152086:
  github.com/microsoft/typescript-go/internal/project.(*diskFile).MatchesDiskText()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/overlayfs.go:93 +0xd2
  github.com/microsoft/typescript-go/internal/project.(*snapshotFSBuilder).FileExists()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/snapshotfs.go:253 +0xdc
  github.com/microsoft/typescript-go/internal/project.(*sourceFS).FileExists()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/snapshotfs.go:583 +0xae
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).tryFileLookup()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1537 +0xa3
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).tryFile()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1522 +0x124
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).tryExtension()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1510 +0x67
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).tryAddingExtensions()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1472 +0x1e8
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).loadModuleFromFile()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1367 +0x8b
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).nodeLoadModuleByRelativeName()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1333 +0x3eb
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).tryLoadModuleUsingPathsIfEligible.func1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1212 +0x4b
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).tryLoadModuleUsingPaths()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1238 +0x898
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).tryLoadModuleUsingPathsIfEligible()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1205 +0x5dd
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).tryLoadModuleUsingOptionalResolutionSettings()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:1173 +0x2e
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).resolveNodeLikeWorker()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:504 +0x3b
  github.com/microsoft/typescript-go/internal/module.(*resolutionState).resolveNodeLike()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:479 +0x5fb
  github.com/microsoft/typescript-go/internal/module.(*Resolver).ResolveModuleName()
      /mnt/vss/_work/typescript-go/typescript-go/internal/module/resolver.go:299 +0xc89
  github.com/microsoft/typescript-go/internal/compiler.(*fileLoader).resolveImportsAndModuleAugmentations()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/fileloader.go:416 +0xce4
  github.com/microsoft/typescript-go/internal/compiler.(*parseTask).load()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/filesparser.go:145 +0xff3
  github.com/microsoft/typescript-go/internal/compiler.(*filesParser).start.func1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/filesparser.go:252 +0x615
  github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue.func1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/core/workgroup.go:40 +0x2e
  sync.(*WaitGroup).Go.func1()
      /home/cloudtest/.local/share/microsoft-go/go1.26.1-1/src/sync/waitgroup.go:258 +0x5d

Goroutine 152090 (running) created at:
  sync.(*WaitGroup).Go()
      /home/cloudtest/.local/share/microsoft-go/go1.26.1-1/src/sync/waitgroup.go:238 +0x86
  github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue()
      /mnt/vss/_work/typescript-go/typescript-go/internal/core/workgroup.go:39 +0xa7
  github.com/microsoft/typescript-go/internal/compiler.(*filesParser).start()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/filesparser.go:216 +0x82
  github.com/microsoft/typescript-go/internal/compiler.(*filesParser).parse()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/filesparser.go:204 +0x51
  github.com/microsoft/typescript-go/internal/compiler.processAllProgramFiles()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/fileloader.go:152 +0xcd5
  github.com/microsoft/typescript-go/internal/compiler.NewProgram()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/program.go:259 +0x264
  github.com/microsoft/typescript-go/internal/project.(*Project).CreateProgram()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/project.go:322 +0x524
  github.com/microsoft/typescript-go/internal/project.(*ProjectCollectionBuilder).updateProgram.func1.2()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/projectcollectionbuilder.go:1007 +0x5ca
  github.com/microsoft/typescript-go/internal/project/dirty.(*SyncMapEntry[go.shape.string,go.shape.*uint8]).changeLocked()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:105 +0x3a7
  github.com/microsoft/typescript-go/internal/project/dirty.(*lockedEntry[go.shape.string,go.shape.*uint8]).Change()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:27 +0x64
  github.com/microsoft/typescript-go/internal/project/dirty.(*lockedEntry[github.com/microsoft/typescript-go/internal/tspath.Path,*github.com/microsoft/typescript-go/internal/project.Project]).Change()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:26 +0xe
  github.com/microsoft/typescript-go/internal/project.(*ProjectCollectionBuilder).updateProgram.func1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/projectcollectionbuilder.go:1004 +0x413
  github.com/microsoft/typescript-go/internal/project/dirty.(*SyncMapEntry[go.shape.string,go.shape.*uint8]).Locked()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:90 +0x13c
  github.com/microsoft/typescript-go/internal/project/dirty.(*SyncMapEntry[github.com/microsoft/typescript-go/internal/tspath.Path,*github.com/microsoft/typescript-go/internal/project.Project]).Locked()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:83 +0x3a
  github.com/microsoft/typescript-go/internal/project.(*ProjectCollectionBuilder).updateProgram()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/projectcollectionbuilder.go:978 +0x218
  github.com/microsoft/typescript-go/internal/project.(*ProjectCollectionBuilder).findOrCreateDefaultConfiguredProjectWorker.func2()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/projectcollectionbuilder.go:776 +0x3a4
  github.com/microsoft/typescript-go/internal/core.BreadthFirstSearchParallelEx[go.shape.struct { github.com/microsoft/typescript-go/internal/project.configFileName string; github.com/microsoft/typescript-go/internal/project.loadKind github.com/microsoft/typescript-go/internal/project.projectLoadKind },go.shape.struct { github.com/microsoft/typescript-go/internal/project.configFileName string; github.com/microsoft/typescript-go/internal/project.loadKind github.com/microsoft/typescript-go/internal/project.projectLoadKind; github.com/microsoft/typescript-go/internal/project.logger *github.com/microsoft/typescript-go/internal/project/logging.LogTree }].func1.1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/core/bfs.go:115 +0x24c
  github.com/microsoft/typescript-go/internal/core.BreadthFirstSearchParallelEx[go.shape.struct { github.com/microsoft/typescript-go/internal/project.configFileName string; github.com/microsoft/typescript-go/internal/project.loadKind github.com/microsoft/typescript-go/internal/project.projectLoadKind },go.shape.struct { github.com/microsoft/typescript-go/internal/project.configFileName string; github.com/microsoft/typescript-go/internal/project.loadKind github.com/microsoft/typescript-go/internal/project.projectLoadKind; github.com/microsoft/typescript-go/internal/project.logger *github.com/microsoft/typescript-go/internal/project/logging.LogTree }].func1.gowrap1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/core/bfs.go:142 +0x46

Goroutine 152086 (running) created at:
  sync.(*WaitGroup).Go()
      /home/cloudtest/.local/share/microsoft-go/go1.26.1-1/src/sync/waitgroup.go:238 +0x86
  github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue()
      /mnt/vss/_work/typescript-go/typescript-go/internal/core/workgroup.go:39 +0xa7
  github.com/microsoft/typescript-go/internal/compiler.(*filesParser).start()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/filesparser.go:216 +0x82
  github.com/microsoft/typescript-go/internal/compiler.(*filesParser).parse()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/filesparser.go:204 +0x51
  github.com/microsoft/typescript-go/internal/compiler.processAllProgramFiles()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/fileloader.go:152 +0xcd5
  github.com/microsoft/typescript-go/internal/compiler.NewProgram()
      /mnt/vss/_work/typescript-go/typescript-go/internal/compiler/program.go:259 +0x264
  github.com/microsoft/typescript-go/internal/project.(*Project).CreateProgram()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/project.go:322 +0x524
  github.com/microsoft/typescript-go/internal/project.(*ProjectCollectionBuilder).updateProgram.func1.2()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/projectcollectionbuilder.go:1007 +0x5ca
  github.com/microsoft/typescript-go/internal/project/dirty.(*SyncMapEntry[go.shape.string,go.shape.*uint8]).changeLocked()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:105 +0x3a7
  github.com/microsoft/typescript-go/internal/project/dirty.(*lockedEntry[go.shape.string,go.shape.*uint8]).Change()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:27 +0x64
  github.com/microsoft/typescript-go/internal/project/dirty.(*lockedEntry[github.com/microsoft/typescript-go/internal/tspath.Path,*github.com/microsoft/typescript-go/internal/project.Project]).Change()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:26 +0xe
  github.com/microsoft/typescript-go/internal/project.(*ProjectCollectionBuilder).updateProgram.func1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/projectcollectionbuilder.go:1004 +0x413
  github.com/microsoft/typescript-go/internal/project/dirty.(*SyncMapEntry[go.shape.string,go.shape.*uint8]).Locked()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:90 +0x13c
  github.com/microsoft/typescript-go/internal/project/dirty.(*SyncMapEntry[github.com/microsoft/typescript-go/internal/tspath.Path,*github.com/microsoft/typescript-go/internal/project.Project]).Locked()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/dirty/syncmap.go:83 +0x3a
  github.com/microsoft/typescript-go/internal/project.(*ProjectCollectionBuilder).updateProgram()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/projectcollectionbuilder.go:978 +0x218
  github.com/microsoft/typescript-go/internal/project.(*ProjectCollectionBuilder).findOrCreateDefaultConfiguredProjectWorker.func2()
      /mnt/vss/_work/typescript-go/typescript-go/internal/project/projectcollectionbuilder.go:776 +0x3a4
  github.com/microsoft/typescript-go/internal/core.BreadthFirstSearchParallelEx[go.shape.struct { github.com/microsoft/typescript-go/internal/project.configFileName string; github.com/microsoft/typescript-go/internal/project.loadKind github.com/microsoft/typescript-go/internal/project.projectLoadKind },go.shape.struct { github.com/microsoft/typescript-go/internal/project.configFileName string; github.com/microsoft/typescript-go/internal/project.loadKind github.com/microsoft/typescript-go/internal/project.projectLoadKind; github.com/microsoft/typescript-go/internal/project.logger *github.com/microsoft/typescript-go/internal/project/logging.LogTree }].func1.1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/core/bfs.go:115 +0x24c
  github.com/microsoft/typescript-go/internal/core.BreadthFirstSearchParallelEx[go.shape.struct { github.com/microsoft/typescript-go/internal/project.configFileName string; github.com/microsoft/typescript-go/internal/project.loadKind github.com/microsoft/typescript-go/internal/project.projectLoadKind },go.shape.struct { github.com/microsoft/typescript-go/internal/project.configFileName string; github.com/microsoft/typescript-go/internal/project.loadKind github.com/microsoft/typescript-go/internal/project.projectLoadKind; github.com/microsoft/typescript-go/internal/project.logger *github.com/microsoft/typescript-go/internal/project/logging.LogTree }].func1.gowrap1()
      /mnt/vss/_work/typescript-go/typescript-go/internal/core/bfs.go:142 +0x46
==================
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #3148

### CODE REVIEW

File: internal/project/snapshotfs.go [hunk 1]
```diff
@@ -250,13 +250,10 @@ func (s *snapshotFSBuilder) FileExists(fileName string, path tspath.Path) bool {
 		if val == nil {
 			return false
 		}
-		if val.MatchesDiskText() {
```
Comment (andrewbranch) [inline internal/project/snapshotfs.go:253]: `s.reloadEntryIfNeeded` already checks `MatchesDiskText()` under the lock, so this was unnecessary.

**Comment by jakebailey** [comment]
Thanks!
