### PR TITLE
fix(1650): [lsp] panic when hovering error in catch(error)

### LINKED ISSUE #1650: [lsp] panic when hovering error in catch(error)
## Stack trace

```
panic handling request textDocument/hover interface conversion: ast.nodeData is *ast.CatchClause, not *ast.VariableDeclarationList goroutine 602 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0xc0001a0dc0, 0xc006483890)
	github.com/microsoft/typescript-go/internal/lsp/server.go:532 +0x58
panic({0xb0a860?, 0xc00659a690?})
	runtime/panic.go:783 +0x132
github.com/microsoft/typescript-go/internal/ast.(*Node).AsVariableDeclarationList(...)
	github.com/microsoft/typescript-go/internal/ast/ast.go:1307
github.com/microsoft/typescript-go/internal/ls.getJSDocOrTag(0xc00039a000)
	github.com/microsoft/typescript-go/internal/ls/hover.go:358 +0x18d
github.com/microsoft/typescript-go/internal/ls.getQuickInfoAndDocumentationForSymbol(0xc005a74608?, 0xc000398000?, 0xc0001b3c01?)
	github.com/microsoft/typescript-go/internal/ls/hover.go:57 +0x51
github.com/microsoft/typescript-go/internal/ls.getQuickInfoAndDocumentation(0xc005a74608, 0xc000398000?)
	github.com/microsoft/typescript-go/internal/ls/hover.go:47 +0x5d
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideHover(0xc000538ca8, {0xe46bf0, 0xc0065ac5a0}, {0xc0064a4000?, 0xc005a08ef8?}, {0x5a08ed0?, 0xc0?})
	github.com/microsoft/typescript-go/internal/ls/hover.go:30 +0x105
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleHover(0xc0002781c0?, {0xe46bf0?, 0xc0065ac5a0?}, 0xc0064a4000?, 0x4d?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:720 +0x35
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceDocumentRequestHandler[...].12({0xe46bf0, 0xc0065ac5a0}, 0xc006483890)
	github.com/microsoft/typescript-go/internal/lsp/server.go:518 +0x11a
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0xc0001a0dc0, {0xe46bf0, 0xc0065ac5a0}, 0xc006483890)
	github.com/microsoft/typescript-go/internal/lsp/server.go:424 +0x10d
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:329 +0x3a
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 34
	github.com/microsoft/typescript-go/internal/lsp/server.go:349 +0x8aa

[Error - 4:34:33 PM] Request textDocument/hover failed.
  Message: InternalError: panic handling request textDocument/hover: interface conversion: ast.nodeData is *ast.CatchClause, not *ast.VariableDeclarationList
  Code: -32603 

```

## Steps to reproduce

Given this code:
```
try {} catch(error) {}
```
hover over `error`

I'm using extension version `0.20250829.3` and have seen this using MacOS and WSL.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #1650

### CODE REVIEW

File: internal/fourslash/tests/gen/quickInfoCatch_test.go
Comment (jakebailey) [inline internal/fourslash/tests/gen/quickInfoCatch_test.go:1]: Move this test up a dir; the gen dir is only for generated tests. (The manual dir is for generated tests that need manual modification)

File: internal/ls/hover.go [hunk 1]
```diff
@@ -355,7 +355,7 @@ func getJSDocOrTag(node *ast.Node) *ast.Node {
 		return getMatchingJSDocTag(node.Parent, node.Name().Text(), isMatchingParameterTag)
 	case ast.IsTypeParameterDeclaration(node):
 		return getMatchingJSDocTag(node.Parent, node.Name().Text(), isMatchingTemplateTag)
-	case ast.IsVariableDeclaration(node) && core.FirstOrNil(node.Parent.AsVariableDeclarationList().Declarations.Nodes) == node:
+	case ast.IsVariableDeclaration(node) && ast.IsVariableDeclarationList(node.Parent) && core.FirstOrNil(node.Parent.AsVariableDeclarationList().Declarations.Nodes) == node:
```
Comment (jakebailey) [inline internal/ls/hover.go:358]: Given the test case is about a catch clause, I'm assuming this is a case where a variable declaration parent can be a declaration list or a catch clause.

Does this mean that we should actually just be handling both? I don't think we actually allow jsdoc in this position, so presumably not?

Comment (a-tarasyuk) [reply internal/ls/hover.go:358]: I’m not entirely certain I understand the key issue, however, I’ve added explicit checks for both the catch clause and variable declarations, along with additional tests to cover these cases. Please let me know if this aligns with your expectations or if there’s an alternative approach you’d suggest.

Comment (jakebailey) [reply internal/ls/hover.go:358]: I think your original fix is probably fine; I was trying to speculate on our old behavior here for JSDoc.

Feel free to change it back to the simpler change.

Comment (a-tarasyuk) [reply internal/ls/hover.go:358]: @jakebailey thanks, reverted

**Review by jakebailey — APPROVED** [review]
