### PR TITLE
Implement auto-import code actions, port tests and fix some bugs

### LINKED ISSUE #1658: tsgo preview: fails to show import suggestions when imports statements deleted
## Steps to reproduce

Delete anyone import statement

## Behavior with `typescript@5.8`

It will show import suggestion in fix dropdown menu

## Behavior with `tsgo`

No suggestions.

The PR https://github.com/microsoft/typescript-go/pull/1553 seems only support showing import sugguestions when writing code.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #1658

~This is not perfect. It passes maybe 60 out of 160 ported fourslash tests so far. Many issues exist with import sorting or formatting, and there are other diagnostics fixed by import fixes that are not being addressed here (like swapping a non-type to a type), and there are other auto-imports that seem weird that I need to double check.~

~But for the typical cases of just missing an import, this seems to work.~

Re-ported a bunch of code and it's now passing tests except these differences:

- symlink tests don't work
- import ordering sometimes differs
- a bit of formatting weirdness in some tests
- JSDoc `@import` doesn't work (we see the reparsed nodes...)

### CODE REVIEW

**Comment by jakebailey** [comment]
I'm currently reworking this with less of a minimal implementation that passes way more tests, which will fix all of the CI problems too.

File: internal/fourslash/fourslash.go [hunk 1]
```diff
@@ -1030,6 +1030,141 @@ func (f *FourslashTest) VerifyApplyCodeActionFromCompletion(t *testing.T, marker
...
+		actualTextArray = append(actualTextArray, text)
+
+		// Undo changes to perform next fix
+		for _, textChange := range edits {
+			start := int(f.converters.LineAndCharacterToPosition(script, textChange.Range.Start))
+			end := int(f.converters.LineAndCharacterToPosition(script, textChange.Range.End))
+			deletedText := originalContent[start:end]
+			insertedText := textChange.NewText
+			f.editScriptAndUpdateMarkers(t, f.activeFilename, start, start+len(insertedText), deletedText)
+		}
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/fourslash/fourslash.go:1171]: I entirely agree but the old code is just as bad!

File: internal/ls/codeactions_importfixes.go [hunk 2]
```diff
@@ -0,0 +1,1278 @@
...
+
+// symbolFlagsHaveMeaning already exists in utilities.go
+
+// getImportFixes gets import fixes for export infos (from importFixes.ts getImportFixes)
+type importFixesResult struct {
+	fixes                     []*ImportFix
+	computedWithoutCacheCount int
+}
+
+func getImportFixes(
```
Comment (andrewbranch) [inline internal/ls/codeactions_importfixes.go]: Duplicated with `(*LanguageService).getImportFixes`?

File: internal/ls/codeactions_importfixes.go [hunk 3]
```diff
@@ -0,0 +1,1278 @@
...
+	return false
+}
+
+// jsxModeNeedsExplicitImport checks if JSX mode needs explicit import (from importFixes.ts)
+func jsxModeNeedsExplicitImport(jsx core.JsxEmit) bool {
+	return jsx == core.JsxEmitReact || jsx == core.JsxEmitReactNative
+}
+
+// getExportInfos searches for exports (from importFixes.ts)
+func getExportInfos(
```
Comment (andrewbranch) [inline internal/ls/codeactions_importfixes.go:345]: Duplicated with `(*LanguageService).getExportInfos`?

File: internal/ls/codeactions_importfixes.go [hunk 4]
```diff
@@ -0,0 +1,1278 @@
...
+}
+
+// shouldUseRequire determines if require should be used (from importFixes.ts)
+func shouldUseRequire(sourceFile *ast.SourceFile, program *compiler.Program) bool {
+	// Delegate to the existing implementation in autoimports.go
+	return getShouldUseRequire(sourceFile, program)
+}
+
+// codeActionForFix creates a code action for a fix (from importFixes.ts codeActionForFix)
+func codeActionForFix(ctx context.Context, fixContext *CodeFixContext, info *fixInfo) *CodeAction {
```
Comment (andrewbranch) [inline internal/ls/codeactions_importfixes.go]: Duplicated with `(*LanguageService).codeActionForFix`?

File: internal/ls/codeactions_importfixes.go [hunk 5]
```diff
@@ -0,0 +1,1278 @@
...
+	endLine, endChar := scanner.GetECMALineAndCharacterOfPosition(sourceFile, typeEnd)
+
+	changes.ReplaceRangeWithText(sourceFile, lsproto.Range{
+		Start: lsproto.Position{Line: uint32(startLine), Character: uint32(startChar)},
+		End:   lsproto.Position{Line: uint32(endLine), Character: uint32(endChar)},
+	}, "")
+}
+
+// tryGetModuleSpecifierFromDeclaration tries to get the module specifier from a declaration (from utilities.ts)
+func tryGetModuleSpecifierFromDeclaration(node *ast.Node) *ast.Node {
```
Comment (andrewbranch) [inline internal/ls/codeactions_importfixes.go]: Duplicated with nodebuilderimpl.go?

File: internal/ls/codeactions_importfixes.go [hunk 6]
```diff
@@ -0,0 +1,1278 @@
...
+
+	changes.ReplaceRangeWithText(sourceFile, lsproto.Range{
+		Start: lsproto.Position{Line: uint32(startLine), Character: uint32(startChar)},
+		End:   lsproto.Position{Line: uint32(endLine), Character: uint32(endChar)},
+	}, "")
+}
+
+// insertImports inserts new import statements in the correct position relative to existing imports
+// (from utilities.ts insertImports)
+func insertImports(
```
Comment (andrewbranch) [inline internal/ls/codeactions_importfixes.go]: Duplicated with `(*LanguageService).insertImports`?

File: internal/ls/codeactions_importfixes.go [hunk 7]
```diff
@@ -0,0 +1,1278 @@
...
+
+		// Compare module specifiers
+		return compareModuleSpecifiers(a.fix, b.fix, fixContext.SourceFile, fixContext.Program, packageJsonFilter, fixContext.LS)
+	})
+
+	return sorted
+}
+
+// compareModuleSpecifiers compares two import fixes by their module specifiers (from importFixes.ts)
+func compareModuleSpecifiers(
```
Comment (andrewbranch) [inline internal/ls/codeactions_importfixes.go]: Duplicated with `(*LanguageService).compareModuleSpecifiers`?

File: internal/fourslash/_scripts/failingTests.txt [hunk 8]
```diff
@@ -148,10 +161,7 @@ TestCompletionsGenericTypeWithMultipleBases1
 TestCompletionsImportOrExportSpecifier
 TestCompletionsImport_default_alreadyExistedWithRename
 TestCompletionsImport_default_anonymous
-TestCompletionsImport_default_symbolName
```
Comment (jakebailey) [inline internal/fourslash/_scripts/failingTests.txt:151]: A smattering of bugfixes as I looked at failing auto-import fix tests caused other existing tests to pass.

File: internal/ls/codeactions_importfixes.go (hunk 7 above)
Comment (jakebailey) [reply internal/ls/codeactions_importfixes.go]: Shockingly, `importFixes.ts` had its own local `compareModuleSpecifiers`; I should rename it to indicate that it's special.

Comment (jakebailey) [reply internal/ls/codeactions_importfixes.go]: That or I am confusing it with the _other_ one in organize imports...

Comment (andrewbranch) [reply internal/ls/codeactions_importfixes.go]: This is definitely duplicated. Most of importFixes.ts has already been ported.

File: internal/ls/codeactions_importfixes.go (hunk 3 above)
Comment (jakebailey) [reply internal/ls/codeactions_importfixes.go:345]: Technically, no, I think; the the existing one should have been called `getExportInfoMap`

**Comment by jakebailey** [comment]
`TestImportNameCodeFix_reExport` is flaky; looking into that...

**Comment by jakebailey** [comment]
Going to merge this now just to get this out. It's going to be no worse than the fixes that completions give, and both will improve as we fix bugs.

**Comment by cpojer** [comment]
@jakebailey I tried the latest tsgo from today and `cmd+.` in VS Code says "No code actions available". Is there any configuration needed to make this work?

**Comment by jakebailey** [comment]
Nope, nothing special. Try moving your cursor to the end of the name and hit Ctrl+Space to trigger a completion; if the auto import shows up in that then there's definitely a bug in this PR. Otherwise, there's a more generic bug in auto imports.

In any case, you should still file a separate issue.

**Comment by cpojer** [comment]
I just updated VS Code, and now it appears to be working. That was my last blocker for fully adopting tsgo, thank you!

**Comment by cpojer** [comment]
Ah, looks like there are some issues. It only works sometimes, but I have not yet narrowed down when it works and when it doesn't work.

**Comment by paulintrognon** [comment]
Agree with cpojer: doesn't work all the time. I sometimes have to `Reload Window` to make it work again.
