### PR TITLE
Mark file as changed when didOpen content differs from disk content

### LINKED ISSUE #3470: panic handling request textDocument/semanticTokens/full: semantic tokens: token spans multiple lines: start=(15,34) end=(16,12) for token at offset 617
Copied from `@typescript-bot` results on PR #3454.

Source PR: https://github.com/microsoft/typescript-go/pull/3454

This error was reported in 1 bot report section across 1 affected repo.

Source comments:
- https://github.com/microsoft/typescript-go/pull/3454#issuecomment-4285883217

Affected repos:
- janhq/jan

The source comment contains the raw stack trace, affected repo section, old server result, last few requests, and repro steps.

### PR DESCRIPTION
**Pull request by jakebailey**
This is one possible way #3441 could have broken.

(This bug was introduced in #2549)

Fixes #3470 (i tested, yay)

### CODE REVIEW

**Review by gabritto — APPROVED** [review]

**Comment by jakebailey** [comment]
This turns out to go further than I thought and is the source for more reported crashes. If any difference happens at all between disk and didOpen, we break!

This might be the source of a lot of crashes.

**Review by gabritto — APPROVED** [review]

File: internal/project/snapshotfs.go [hunk 1]
```diff
@@ -600,6 +600,14 @@ func (s *snapshotFSBuilder) convertOpenAndCloseToChanges(change FileChangeSummar
 		path := s.toPath(change.Opened.FileName())
 		if entry, ok := s.diskFiles.Load(path); !ok || entry.Original() == nil {
 			change.Created.Add(change.Opened)
+		} else if overlay, ok := s.overlays[path]; ok {
+			// The file already exists in the program, but the overlay content from
+			// didOpen may differ from what was originally read from disk (e.g. the
+			// editor normalizes line endings, or the file changed on disk since the
+			// project was loaded). Mark it as Changed so the project rebuilds.
```
Comment (Andarist) [inline internal/project/snapshotfs.go:607]: I looked at this one too before I noticed this PR and came up with this extra test case in my explorations
```go
// internal/lsp/server_semantic_tokens_test.go

package lsp_test

import (
	"context"
	"io"
	"testing"

	"github.com/microsoft/typescript-go/internal/bundled"
	"github.com/microsoft/typescript-go/internal/ls/lsconv"
	"github.com/microsoft/typescript-go/internal/lsp"
	"github.com/microsoft/typescript-go/internal/lsp/lsproto"
	"github.com/microsoft/typescript-go/internal/testutil/lsptestutil"
	"github.com/microsoft/typescript-go/internal/vfs/vfstest"
	"gotest.tools/v3/assert"
)

func initSemanticTokensClient(t *testing.T, files map[string]string) *lsptestutil.LSPClient {
	t.Helper()

	fs := bundled.WrapFS(vfstest.FromMap(files, false))

	onServerRequest := func(_ context.Context, req *lsproto.RequestMessage) *lsproto.ResponseMessage {
		switch req.Method {
		case lsproto.MethodClientRegisterCapability, lsproto.MethodClientUnregisterCapability, lsproto.MethodWindowWorkDoneProgressCreate:
			return &lsproto.ResponseMessage{ID: req.ID, JSONRPC: req.JSONRPC, Result: lsproto.Null{}}
		default:
			return nil
		}
	}

	client, closeClient := lsptestutil.NewLSPClient(t, lsp.ServerOptions{
		Err:                io.Discard,
		Cwd:                "/home/projects",
		FS:                 fs,
		DefaultLibraryPath: bundled.LibPath(),
	}, onServerRequest)
	t.Cleanup(func() { _ = closeClient() })

	initMsg, _, ok := lsptestutil.SendRequest(t, client, lsproto.InitializeInfo, &lsproto.InitializeParams{
		Capabilities: &lsproto.ClientCapabilities{
			TextDocument: &lsproto.TextDocumentClientCapabilities{
				SemanticTokens: &lsproto.SemanticTokensClientCapabilities{
					Requests: &lsproto.ClientSemanticTokensRequestOptions{
						Full: &lsproto.BooleanOrClientSemanticTokensRequestFullDelta{Boolean: new(true)},
					},
					TokenTypes: []string{
						string(lsproto.SemanticTokenTypeNamespace),
						string(lsproto.SemanticTokenTypeClass),
						string(lsproto.SemanticTokenTypeEnum),
						string(lsproto.SemanticTokenTypeInterface),
						string(lsproto.SemanticTokenTypeStruct),
						string(lsproto.SemanticTokenTypeTypeParameter),
						string(lsproto.SemanticTokenTypeType),
						string(lsproto.SemanticTokenTypeParameter),
						string(lsproto.SemanticTokenTypeVariable),
						string(lsproto.SemanticTokenTypeProperty),
						string(lsproto.SemanticTokenTypeEnumMember),
						string(lsproto.SemanticTokenTypeDecorator),
						string(lsproto.SemanticTokenTypeEvent),
						string(lsproto.SemanticTokenTypeFunction),
						string(lsproto.SemanticTokenTypeMethod),
						string(lsproto.SemanticTokenTypeMacro),
						string(lsproto.SemanticTokenTypeLabel),
						string(lsproto.SemanticTokenTypeComment),
						string(lsproto.SemanticTokenTypeString),
						string(lsproto.SemanticTokenTypeKeyword),
						string(lsproto.SemanticTokenTypeNumber),
						string(lsproto.SemanticTokenTypeRegexp),
						string(lsproto.SemanticTokenTypeOperator),
					},
					TokenModifiers: []string{
						string(lsproto.SemanticTokenModifierDeclaration),
						string(lsproto.SemanticTokenModifierDefinition),
						string(lsproto.SemanticTokenModifierReadonly),
						string(lsproto.SemanticTokenModifierStatic),
						string(lsproto.SemanticTokenModifierDeprecated),
						string(lsproto.SemanticTokenModifierAbstract),
						string(lsproto.SemanticTokenModifierAsync),
						string(lsproto.SemanticTokenModifierModification),
						string(lsproto.SemanticTokenModifierDocumentation),
						string(lsproto.SemanticTokenModifierDefaultLibrary),
						"local",
					},
					Formats: []lsproto.TokenFormat{lsproto.TokenFormatRelative},
				},
			},
		},
	})
	assert.Assert(t, ok && initMsg.AsResponse().Error == nil, "Initialize failed")
	lsptestutil.SendNotification(t, client, lsproto.InitializedInfo, &lsproto.InitializedParams{})
	<-client.Server.InitComplete()

	return client
}

func TestSemanticTokensBOM1(t *testing.T) {
	t.Parallel()

	if !bundled.Embedded {
		t.Skip("bundled files are not embedded")
	}

	const source = "\ufefffunction f({\n" +
		"  x\n" +
		"}){}\n"

	client := initSemanticTokensClient(t, map[string]string{
		"/home/projects/a.ts": source,
	})

	uri := lsconv.FileNameToDocumentURI("/home/projects/a.ts")

	// Prime the inferred project before opening the file so the test exercises
	// the path where the open-file overlay text and the inferred-project parse
	// state are established from different server inputs.
	msg, _, ok := lsptestutil.SendRequest(t, client, lsproto.CustomProjectInfoInfo, &lsproto.ProjectInfoParams{
		TextDocument: lsproto.TextDocumentIdentifier{Uri: uri},
	})
	assert.Assert(t, ok && msg.AsResponse().Error == nil, "expected project info response")

	lsptestutil.SendNotification(t, client, lsproto.TextDocumentDidOpenInfo, &lsproto.DidOpenTextDocumentParams{
		TextDocument: &lsproto.TextDocumentItem{
			Uri:        uri,
			LanguageId: "typescript",
			Version:    1,
			Text:       source,
		},
	})

	// Wait for the didOpen to be processed before checking state or requesting semantic tokens.
	msg, _, ok = lsptestutil.SendRequest(t, client, lsproto.CustomProjectInfoInfo, &lsproto.ProjectInfoParams{
		TextDocument: lsproto.TextDocumentIdentifier{Uri: uri},
	})
	assert.Assert(t, ok && msg.AsResponse().Error == nil, "expected post-open project info response")

	msg, resp, ok := lsptestutil.SendRequest(t, client, lsproto.TextDocumentSemanticTokensFullInfo, &lsproto.SemanticTokensParams{
		TextDocument: lsproto.TextDocumentIdentifier{Uri: uri},
	})
	assert.Assert(t, ok, "expected semantic tokens response")
	assert.Assert(t, msg != nil, "expected semantic tokens response")
	assert.Assert(t, msg.AsResponse().Error == nil, "expected semantic tokens request to succeed")
	assert.Assert(t, resp.SemanticTokens != nil, "expected semantic tokens payload")
	assert.Assert(t, len(resp.SemanticTokens.Data) > 0, "expected semantic token data")
	assert.Equal(t, len(resp.SemanticTokens.Data)%5, 0, "expected semantic token data to be encoded in 5-word entries")
}
```
