### PR TITLE
Handle nil end position in getMappedLocation

### LINKED ISSUE #1867: importing the `Effect` library causes a panic "panic handling request textDocument/definition: runtime error: invalid memory address or nil pointer dereference"
## Stack trace

```
======== Cache Statistics ========
[14:22:01.736] Open file count:        1
[14:22:01.736] Cached disk files:    678
[14:22:01.736] Project count:          1
[14:22:01.736] Config count:           0
[14:22:01.736] Parse cache size:              663
[14:22:01.736] Program count:                   1
[14:22:01.736] Extended config cache size:      0

[14:22:01.736] Updated watches in 3.167µs
panic handling request textDocument/definition runtime error: invalid memory address or nil pointer dereference goroutine 41768 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x64
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x140000fadc0, 0x14014361d70)
	github.com/microsoft/typescript-go/internal/lsp/server.go:542 +0x44
panic({0x104f025a0?, 0x10569bde0?})
	runtime/panic.go:783 +0x120
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getMappedLocation(0x14013cbc300, {0x1400f645030, 0x65}, {0x4c15570?, 0x1?})
	github.com/microsoft/typescript-go/internal/ls/source_map.go:21 +0x4c
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).createLocationsFromDeclarations(0x14013cbc300, {0x1400f2299e0, 0x1, 0x14001861808?})
	github.com/microsoft/typescript-go/internal/ls/definition.go:108 +0x114
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideDefinition(0x14013cbc300, {0x1050e8c30, 0x14014344370}, {0x1401273a030?, 0x7b?}, {0x60?, 0x0?})
	github.com/microsoft/typescript-go/internal/ls/definition.go:57 +0x314
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleDefinition(0x1400011c1e0?, {0x1050e8c30?, 0x14014344370?}, 0x1401273a030?, 0x2c?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:766 +0x38
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceDocumentRequestHandler[...].13({0x1050e8c30, 0x14014344370}, 0x14014361d70)
	github.com/microsoft/typescript-go/internal/lsp/server.go:528 +0xf0
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x140000fadc0, {0x1050e8c30, 0x14014344370}, 0x14014361d70)
	github.com/microsoft/typescript-go/internal/lsp/server.go:425 +0xf4
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:330 +0x34
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 7
	github.com/microsoft/typescript-go/internal/lsp/server.go:350 +0x6f8

[Error - 2:22:41 PM] Request textDocument/definition failed.
  Message: InternalError: panic handling request textDocument/definition: runtime error: invalid memory address or nil pointer dereference
  Code: -32603 
```

## Steps to reproduce

1. Clone the reproduction repo
2. Open `index.ts`, and TS Go will show the panic
  2.1 Only thing the files does is import from Node.fs to demonstrate that LSP works, but importing Effect doesn't

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #1867

Analogous to "this shouldn't happen" 🙃

```ts
/** @internal */
export function getMappedDocumentSpan(documentSpan: DocumentSpan, sourceMapper: SourceMapper, fileExists?: (path: string) => boolean): DocumentSpan | undefined {
    const { fileName, textSpan } = documentSpan;
    const newPosition = getMappedLocation({ fileName, pos: textSpan.start }, sourceMapper, fileExists);
    if (!newPosition) return undefined;
    const newEndPosition = getMappedLocation({ fileName, pos: textSpan.start + textSpan.length }, sourceMapper, fileExists);
    const newLength = newEndPosition
        ? newEndPosition.pos - newPosition.pos
        : textSpan.length; // This shouldn't happen
```

### CODE REVIEW

File: internal/fourslash/tests/gen/findAllRefsForDefaultExport03_test.go [hunk 1]
```diff
@@ -9,7 +9,7 @@ import (
 
 func TestFindAllRefsForDefaultExport03(t *testing.T) {
 	t.Parallel()
-	t.Skip()
+
```
Comment (jakebailey) [inline internal/fourslash/tests/gen/findAllRefsForDefaultExport03_test.go]: Hm, I think this is actually already fixed on main. I don't know why main CI is not catching this...

Comment (jakebailey) [reply internal/fourslash/tests/gen/findAllRefsForDefaultExport03_test.go]: #1922, sigh.

File: internal/ls/source_map.go [hunk 2]
```diff
@@ -18,6 +18,12 @@ func (l *LanguageService) getMappedLocation(fileName string, fileRange core.Text
 		}
 	}
 	endPos := l.tryGetSourcePosition(fileName, core.TextPos(fileRange.End()))
+	if endPos == nil {
+		endPos = &sourcemap.DocumentPosition{
+			FileName: startPos.FileName,
+			Pos:      startPos.Pos + fileRange.Len(),
```
Comment (andrewbranch) [inline internal/ls/source_map.go:24]: Looks right as a port, but since this _is_ happening, do we need to ensure this position is inside the length of the file?

Comment (jakebailey) [reply internal/ls/source_map.go:24]: I'm not sure; my understanding is that the conversion to an LSP range will clamp it via the line map, but maybe not... I can grab the script and `min` the text length.

Comment (andrewbranch) [reply internal/ls/source_map.go:24]: It looks like `PositionToLineAndCharacter` will crash with a slice range out of bounds when rescanning the line for the UTF-16 character offset. Maybe it’s worth adding a guard there and not worrying about it here.

Comment (jakebailey) [reply internal/ls/source_map.go:24]: Hm, I can. I'm questioning whether or not it's a good idea, though, given we don't do the same sort of bounds checks when going from an LSP position to a byte position... Could go either way. Either way it's sort of papering over something.

**Review by andrewbranch — APPROVED** [review]
