### PR TITLE
Ensure language service requests create a project for the requested file if one doesn't already exist

### LINKED ISSUE #2822: Harden LSP against requests for files that don't have open projects
While https://github.com/microsoft/vscode-languageserver-node/issues/1717 turned out to be a bug, we should not have been falling over so hard. We need to have a way of responding to requests for non-open files that we haven't opened a project for.

### LINKED ISSUE #2906: Requests failing with ` Message: no project found for URI`
After reloading a VS Code window, I'm seeing errors like this:

```
2026-02-25 13:51:31.915 [error] error handling method 'textDocument/codeLens' (9): no project found for URI file:///Users/matb/projects/sandbox/x.ts
2026-02-25 13:51:31.915 [error] Request textDocument/codeLens failed.
  Message: no project found for URI file:///Users/matb/projects/sandbox/x.ts
  Code: -32603 
```

[Full logs](https://github.com/user-attachments/files/25559029/log.txt)

### PR DESCRIPTION
**Pull request by andrewbranch**
- Fixes #2906 
- Fixes #2822

I didn't realize until investigating, but this was already fixed for files that belong in configured projects (as long as the `disableReferencedProjectLoad` and `disableSolutionSearching` settings don't prevent us from discovering the right project for that file); we just needed to go the last step of creating an inferred project when no configured project is found.

I opted not to do anything special with the lifecycle of projects created like this; they will be cleaned up on the next file open unless that file open provides a reason for it to stick around.

### CODE REVIEW

File: internal/project/session.go [hunk 1]
```diff
@@ -550,7 +551,7 @@ func (s *Session) GetLanguageServiceAndProjectsForFile(ctx context.Context, uri
 func (s *Session) GetProjectsForFile(ctx context.Context, uri lsproto.DocumentUri) ([]ls.Project, error) {
 	snapshot := s.getSnapshot(
 		ctx,
-		ResourceRequest{Documents: []lsproto.DocumentUri{uri}},
+		ResourceRequest{ConfiguredProjectDocuments: []lsproto.DocumentUri{uri}},
```
Comment (andrewbranch) [inline internal/project/session.go:557]: This request is not direct from the LSP client; it's part of the logic for cross-project find-all-refs and similar. It's different in kind from everything else we use `ResourceRequest{Documents}` for, because it's _supposed_ to only load configured projects for these documents _if_ settings allow those projects to be loaded and _if_ there's actually a tsconfig.json. `ResourceRequest{Documents}`, on the other hand, was always intended to mean “the LSP client is asking a question about these documents so you _have_ to produce a snapshot that has a project for all of them.”

File: internal/project/session.go [hunk 2]
```diff
@@ -479,23 +479,24 @@ func (s *Session) getSnapshot(
...
+			for _, document := range documents {
+				if snapshot.fs.isOpenFile(document.FileName()) {
+					project := snapshot.GetDefaultProject(document)
+					if project == nil {
+						return UpdateReasonRequestedLanguageServiceProjectNotLoaded
+					} else if project.dirty {
+						return UpdateReasonRequestedLanguageServiceProjectDirty
+					}
+				} else {
+					return UpdateReasonRequestedLanguageServiceForFileNotOpen
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply internal/project/session.go]: This is not new, but it does seem like it might have been a mistake before 🤔

File: internal/project/projectcollectionbuilder.go [hunk 3]
```diff
@@ -912,6 +935,7 @@ func (b *ProjectCollectionBuilder) updateInferredProjectRoots(rootFileNames []st
 		return false
 	}
 
+	slices.Sort(rootFileNames)
```
Comment (andrewbranch) [inline internal/project/projectcollectionbuilder.go:938]: Moving this into a shared code path, previously missed from a couple callers, was a drive-by fix suggested by Copilot review

File: internal/project/session.go (hunk 1 above)
Comment (DanielRosenwasser) [reply internal/project/session.go:557]: Are you saying we'll never get to this code path with something like a non-configured `.js` file?

Comment (DanielRosenwasser) [reply internal/project/session.go:557]: Just saw the comment below - it's not the case, it sounds like it's just handled differently compared to `Documents`.
