### PR TITLE
Fix empty array tsconfig parsing, ensure helpers are nil-preserving

### LINKED ISSUE #623: types: [] in tsconfig.json is treated as "all visible types"
In tsc:

1. Unspecified `types`: all "visible" types (from node_modules)
2. `types: []`: no extra types

in tsgo (tsgo.exe)

1. Unspecified `types`: all "visible" types (from node_modules)
2. `types: []`: also all visible types, no difference from unspecified

The problem is here:

https://github.com/microsoft/typescript-go/blob/main/internal/compiler/module/resolver.go#L1799

```go
if options.Types != nil {
    return options.Types
}
```

Because here https://github.com/microsoft/typescript-go/blob/main/internal/tsoptions/parsinghelpers.go#L26

```go
func parseStringArray(value any) []string {
	if arr, ok := value.([]any); ok {
		var result []string
		for _, v := range arr {
			if str, ok := v.(string); ok {
				result = append(result, str)
			}
		}
		return result
	}
	return nil
}
```

`var result []string` is a nil slice, which is returned if there are no elements in an array.

I have never programmed in Go so I didn't submit a pull request since I don't know if replacing it with a `result := []string{}` is a good way to do it, hopefully it's an easy fix.

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #623
Replaces #624

The issues here were somewhat wide reaching:

- `core.Map` and `core.MapIndex` were not nil-preserving. This led to parsing turning empty slices into nil slices, which is a problem when `nil` means "was not provided".
- `parseStringArray` was not nil-preserving.
- `setPropertyValue` was not nil-preserving.
- `getPropFromRaw` was not nil-preserving.

Fixing these removes a bunch of extra code from `parseJsonToStringKey`, too.

Annoyingly, `core.Pool` _also_ returns `nil` instead of an empty slice, so we can end up with `nil` lists in the tree rather than empty slices. I've not changed this yet, since we can just say "the parser may produce nil slices for NodeLists", but I suspect this will be a problem for API use given `nil` should really mean `undefined` and that's what the JSON package may do depending on the tags.

### CODE REVIEW

File: internal/tsoptions/parsinghelpers.go [hunk 1]
```diff
@@ -25,7 +25,10 @@ func parseTristate(value any) core.Tristate {
 
 func parseStringArray(value any) []string {
 	if arr, ok := value.([]any); ok {
-		var result []string
+		if arr == nil {
```
Comment (navya9singh) [inline internal/tsoptions/parsinghelpers.go:28]: Is it possible to have a nil `arr` if it has entered the if block?

Comment (jakebailey) [reply internal/tsoptions/parsinghelpers.go:28]: Yes, `[]any(nil)` is a valid value.

**Review by navya9singh — APPROVED** [review]
