### PR TITLE
Handle file casing when creating program

### LINKED ISSUE #1549: Crash in incremental due to inconsistent casing
Tracking the crash mentioned in #1535.

## Stack trace

```
panic: ManyToManySet.Set: key already exists: c:/users/gabrielaa/code/.../removable.d.ts

goroutine 1 [running]:
github.com/microsoft/typescript-go/internal/collections.(*ManyToManySet[...]).Set(0xa65e80, {0xc002fc0700, 0x5d}, 0xc000c07800)
        C:/Users/gabrielaa/code/typescript-go/internal/collections/manytomanyset.go:31 +0x33a
github.com/microsoft/typescript-go/internal/incremental.newSnapshotForProgram(0xc0000036c0, 0x0, 0x0)
        C:/Users/gabrielaa/code/typescript-go/internal/incremental/snapshot.go:373 +0x572
github.com/microsoft/typescript-go/internal/incremental.NewProgram(0xc0000036c0, 0x0, 0x0)
        C:/Users/gabrielaa/code/typescript-go/internal/incremental/program.go:36 +0x25
github.com/microsoft/typescript-go/internal/execute.performIncrementalCompilation({0xa54370, 0xc0000ceba0}, 0xc0000e61e0, 0xc0001f4e00, 0xc000037d10, 0x36d6ac, 0x0)
        C:/Users/gabrielaa/code/typescript-go/internal/execute/tsc.go:247 +0x377
github.com/microsoft/typescript-go/internal/execute.tscCompilation({0xa54370, 0xc0000ceba0}, 0xc0000e60f0, 0x0)
        C:/Users/gabrielaa/code/typescript-go/internal/execute/tsc.go:194 +0xb53
github.com/microsoft/typescript-go/internal/execute.CommandLine({0xa54370, 0xc0000ceba0}, {0xc00008a150, 0x2, 0x3}, 0x0)
        C:/Users/gabrielaa/code/typescript-go/internal/execute/tsc.go:63 +0x17e
main.runMain()
        C:/Users/gabrielaa/code/typescript-go/cmd/tsgo/main.go:23 +0x109
main.main()
        C:/Users/gabrielaa/code/typescript-go/cmd/tsgo/main.go:10 +0x13
```

## Steps to reproduce

1. From #1535, you can repro it with the following test in `tsc_test.go`:
```go
{
			subScenario:     "Compile incremental with case insensitive file names",
			commandLineArgs: []string{"-p", "."},
			files: FileMap{
				"/home/project/tsconfig.json": stringtestutil.Dedent(`
				{
    				"compilerOptions": {
       					"incremental": true
    				},
				}`),
				"/home/project/src/index.ts": stringtestutil.Dedent(`
				import type { Foo1 } from 'lib1';
				import type { Foo2 } from 'lib2';
				export const foo1: Foo1 = { foo: "a" };
				export const foo2: Foo2 = { foo: "b" };`),
				"/home/node_modules/lib1/index.d.ts": stringtestutil.Dedent(`
				import type { Foo } from 'someLib';
				export type { Foo as Foo1 };`),
				"/home/node_modules/lib1/package.json": stringtestutil.Dedent(`
				{
					"name": "lib1"
				}`),
				"/home/node_modules/lib2/index.d.ts": stringtestutil.Dedent(`
				import type { Foo } from 'somelib';
				export type { Foo as Foo2 };
				export declare const foo2: Foo;`),
				"/home/node_modules/lib2/package.json": stringtestutil.Dedent(`
				{
					"name": "lib2"
				}
				`),
				"/home/node_modules/someLib/index.d.ts": stringtestutil.Dedent(`
				import type { Str } from 'otherLib';
				export type Foo = { foo: Str; };`),
				"/home/node_modules/someLib/package.json": stringtestutil.Dedent(`
				{
    				"name": "somelib"
				}`),
				"/home/node_modules/otherLib/index.d.ts": stringtestutil.Dedent(`
				export type Str = string;`),
				"/home/node_modules/otherLib/package.json": stringtestutil.Dedent(`
				{
					"name": "otherlib"
				}`),
			},
			cwd:        "/home/project",
			ignoreCase: true,
		},
```

See #1535 for discussion, but the crash happens because right now it's possible for the same file to be included more than once in a program, when the file system is case insensitive and the file is included each time with a name that differs in casing from the others.
Having the same file multiple times in the program then breaks the assumption of the snapshot code that each file (i.e. each `Path`) will only show up once in the program.

Note that you can get into this situation even without the compiler producing an inconsistent casing error. In the original scenario, I caused the crash by invoking tsgo with a path to the tsconfig which used a different casing than the realpath. This resulted in files added to the program by using the config path having one casing, and files added via module resolution (which invokes `realpath`) having a different casing.

### LINKED ISSUE #1619: Panic in incremental with tsbuildinfo with mismatched `fileNames` and `fileInfos`
## Stack trace

```
panic: runtime error: index out of range [61666] with length 61666

goroutine 1 [running]:
github.com/microsoft/typescript-go/internal/incremental.(*toSnapshot).toFilePath(...)
        /Users/benkraft/src/typescript-go/internal/incremental/buildinfotosnapshot.go:61
github.com/microsoft/typescript-go/internal/incremental.(*toSnapshot).setFileInfoAndEmitSignatures(0x140001ac800)
        /Users/benkraft/src/typescript-go/internal/incremental/buildinfotosnapshot.go:104 +0x400
github.com/microsoft/typescript-go/internal/incremental.buildInfoToSnapshot(0x140001c8b40, {0x140011feff0?, 0x46?}, 0x140001c87e0, {0x1031730d8, 0x140001eda40})
        /Users/benkraft/src/typescript-go/internal/incremental/buildinfotosnapshot.go:34 +0x328
github.com/microsoft/typescript-go/internal/incremental.ReadBuildInfoProgram(0x140001c87e0, {0x10316db20, 0x1400021c2c0}, {0x1031730d8, 0x140001eda40})
        /Users/benkraft/src/typescript-go/internal/incremental/incremental.go:53 +0xd4
github.com/microsoft/typescript-go/internal/execute.performIncrementalCompilation({0x103174ed8, 0x14000182c00}, 0x140001c87e0, 0x140011f9140, {0x10316db00, 0x140000c78c0}, 0x5480e30b, {0x0, 0x0})
        /Users/benkraft/src/typescript-go/internal/execute/tsc.go:251 +0x1fc
github.com/microsoft/typescript-go/internal/execute.tscCompilation({0x103174ed8, 0x14000182c00}, 0x140001c8c60, {0x0, 0x0})
        /Users/benkraft/src/typescript-go/internal/execute/tsc.go:198 +0x87c
github.com/microsoft/typescript-go/internal/execute.CommandLine({0x103174ed8, 0x14000182c00}, {0x14000020060, 0x4, 0x4}, {0x0, 0x0})
        /Users/benkraft/src/typescript-go/internal/execute/tsc.go:67 +0x1b4
main.runMain()
        /Users/benkraft/src/typescript-go/cmd/tsgo/main.go:23 +0x120
main.main()
        /Users/benkraft/src/typescript-go/cmd/tsgo/main.go:10 +0x1c

```

## Steps to reproduce

I haven't been able to repro this in isolation -- one of our internal users ran into it and I can repro it by doing an incremental build from their tsbuildinfo file. I don't think I can share the full file but here's a relevant fact about it:
```
$ jq '.fileInfos|length' path/to/tsconfig.tsbuildinfo
61667
$ jq '.fileNames|length' path/to/tsconfig.tsbuildinfo
61666
```

Perhaps as a start the tsbuildinfo loader should validate this? It's a bit harder for me to figure out how the tsbuildinfo got that way, but I'm gonna try. (My guess is maybe some kind of casing-conflict or other condition that causes two file-infos for one file name? The code doesn't really look like it ensures they are 1:1, but then it assumes they are, I think.) Let me know if anyone has ideas for what to look at, or which other facts about the tsbuildinfo might be of interest.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Handle file casing when creating program so that we dont add duplicate files that only differ in casing on case insesitive file system.
This also adds checks for `forceConsistentCasingInFileNames`

Fixes #1549
Fixes #1619

### CODE REVIEW

File: internal/compiler/filesparser.go [hunk 1]
```diff
@@ -138,132 +130,262 @@ func (t *parseTask) loadAutomaticTypeDirectives(loader *fileLoader) {
...
+					if checkedAbsolutePath != inputAbsolutePath {
+						loader.includeProcessor.addProcessingDiagnosticsForFileCasing(task.path, checkedName, task.normalizedFilePath, includeReason)
+					}
+				}
+				continue
+			} else {
+				seen[data] = task.normalizedFilePath
+			}
+
+			if tasksSeenByNameIgnoreCase != nil {
```
Comment (gabritto) [inline internal/compiler/filesparser.go:287]: To make sure I understand this, why can't this check be made above along with the check for when `ForceConsistentCasingInFileNames` is true?

Comment (sheetalkamat) [reply internal/compiler/filesparser.go:287]: Because in case sensitive systems, path= file name so they are distinct and need to check if lowecasing file names as path (as it would do on case insensitive file systems ) can have duplicates and report errors

Comment (sheetalkamat) [reply internal/compiler/filesparser.go:287]: Interestingly we always did this check irrespective of force consistent file names

**Review by gabritto — APPROVED** [review]
