### PR TITLE
Incremental fixes

### LINKED ISSUE #1465: Intermittent crash with --incremental
## Stack trace

https://gist.github.com/tmm1/03a124c5e5c19dede914bf6566755a2c

## Steps to reproduce

1. run `tsgo --noEmit --extendedDiagnostics -p src --incremental` on large project at high frequency in CI

### PR DESCRIPTION
**Pull request by sheetalkamat**
I am going to try and create repro for this but i think this fixes the issue where if there is reference cycle with the const enum usage , it runs into stack overflow.

Fixes #1465

### CODE REVIEW

File: internal/execute/incremental/affectedfileshandler.go [hunk 1]
```diff
@@ -200,6 +200,8 @@ func (h *affectedFilesHandler) handleDtsMayChangeOfAffectedFile(dtsMayChange dts
 		return
 	}
 
+	// At this point affectedFile is actually changed file with change in signature.
```
Comment (DanielRosenwasser) [inline internal/execute/incremental/affectedfileshandler.go]:
```suggestion
	// At this point affectedFile is actually one of the changed files
	// that has some change in its .d.ts signature.
```

File: internal/execute/incremental/affectedfileshandler.go [hunk 2]
```diff
@@ -35,7 +35,7 @@ type affectedFilesHandler struct {
 	dtsMayChange                           []dtsMayChange
 	filesToRemoveDiagnostics               collections.SyncSet[tspath.Path]
 	cleanedDiagnosticsOfLibFiles           sync.Once
-	seenFileAndExportsOfFile               collections.SyncMap[tspath.Path, bool]
+	seenFileAndReferences                  collections.SyncMap[tspath.Path, bool]
```
Comment (DanielRosenwasser) [inline internal/execute/incremental/affectedfileshandler.go:38]: Can we make this a `collections.SyncSet` instead?

File: internal/execute/incremental/affectedfileshandler.go [hunk 3]
```diff
@@ -250,30 +252,35 @@ func (h *affectedFilesHandler) handleDtsMayChangeOfAffectedFile(dtsMayChange dts
...
 				return
 			}
 		}
 	}
 }
 
-func (h *affectedFilesHandler) handleDtsMayChangeOfFileAndExportsOfFile(dtsMayChange dtsMayChange, filePath tspath.Path, invalidateJsFiles bool) bool {
-	if existing, loaded := h.seenFileAndExportsOfFile.LoadOrStore(filePath, invalidateJsFiles); loaded && (existing || !invalidateJsFiles) {
+func (h *affectedFilesHandler) handleDtsMayChangeOfFileAndReferences(dtsMayChange dtsMayChange, filePath tspath.Path, invalidateJsFiles bool) bool {
+	if existing, loaded := h.seenFileAndReferences.LoadOrStore(filePath, invalidateJsFiles); loaded && (existing || !invalidateJsFiles) {
```
Comment (DanielRosenwasser) [inline internal/execute/incremental/affectedfileshandler.go:271]: Since this is really a set, you don't need to handle `existing` and `loaded` differently.

File: internal/execute/incremental/affectedfileshandler.go [hunk 4]
```diff
@@ -250,30 +252,35 @@ func (h *affectedFilesHandler) handleDtsMayChangeOfAffectedFile(dtsMayChange dts
...
+		h.seenFileAndReferences.Store(filePath, true)
 	}
+
 	if h.handleDtsMayChangeOfGlobalScope(dtsMayChange, filePath, invalidateJsFiles) {
 		return true
 	}
 	h.handleDtsMayChangeOf(dtsMayChange, filePath, invalidateJsFiles)
 
-	// Remove the diagnostics of files that import this file and handle all its exports too
+	// Remove the diagnostics of files that imports this file and references to this (direct or indirect)
```
Comment (DanielRosenwasser) [inline internal/execute/incremental/affectedfileshandler.go]:
```suggestion
	// Remove the diagnostics of files that import this file and
	// any files that are referenced by it (directly or indirectly)
```

?

File: internal/execute/incremental/affectedfileshandler.go (hunk 2 above)
Comment (sheetalkamat) [reply internal/execute/incremental/affectedfileshandler.go:38]: This has value bool - true if js files were invalidated. otherwise false. So this is not a set but map.

File: internal/execute/incremental/affectedfileshandler.go (hunk 3 above)
Comment (sheetalkamat) [reply internal/execute/incremental/affectedfileshandler.go:271]: This isnt a set. The value is "true if we invalidated js files, otherwise false.

**Comment by chriskrycho** [comment]
I can confirm that this fixed a stack overflow in our code (in this same code path)! **Edit:** I should say: one user who was consistently hitting it has seen this build resolve it, and I’m also looking for further confirmation from other users in our app who’ve hit it, but signs are promising.
