### PR TITLE
fix(3605): Missing generic param displayed in hover

### LINKED ISSUE #3605: Missing generic param displayed in hover
### Extension Version

0.20260425.1

### VS Code Version

1.114.0

### Operating system Version

Microsoft Windows NT 10.0.26200.0 x64

### Steps to reproduce

1.

```ts
class Foo<T extends number = 42> {
    bar() {}
}
```

2.

Hover on `bar`.

ts6.0:
```ts
(method) Foo<T extends number = 42>.bar(): void
```

tsgo:
```ts
(method) Foo.bar(): void
```

### Issue

Expected the same as ts6.0

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #3605.

Fixes crash found in https://github.com/microsoft/typescript-go/issues/3512#issuecomment-4299732162.

### CODE REVIEW

File: internal/checker/nodebuilderimpl.go [hunk 1]
```diff
@@ -3480,7 +3480,13 @@ func (b *NodeBuilderImpl) lookupExpressionChainTypeArgumentNodes(chain []*ast.Sy
 		}
 
 		b.ctx.typeParameterSymbolList[symbolId] = struct{}{}
-		return b.lookupInstantiatedTypeArgumentNodes(chain, index)
+		if typeArgumentNodes := b.lookupInstantiatedTypeArgumentNodes(chain, index); typeArgumentNodes != nil {
+			return typeArgumentNodes
+		}
+		typeParameterNodes := b.typeParametersToTypeParameterDeclarations(symbol)
```
Comment (gabritto) [inline internal/checker/nodebuilderimpl.go:3486]: This matches Strada's behavior of `lookupTypeParameterNodes`.

**Review by gabritto — APPROVED** [review]
