### PR TITLE
Fix `completionItem/resolve` keyword and hover crashes

### LINKED ISSUE #1402: [bug] panic when providing auto-complete results on type
The weird thing is that other than the error modal I wouldn't have noticed this panic -- the LSP continues to remain responsive and provide completion results. Let me know if there's anything else I can attach to this bug report that can help ya'll diagnose the issue.

Image

TS extension verison:

```
Identifier typescriptteam.native-preview
Version 0.20250712.1
```

LSP logs:

```
Info 7494 [16:45:21.874] Finishing updateGraph: Project: /<omitted>/canva/<omitted>/tsconfig.json version: 11 in 307.31µs
panic handling request completionItem/resolve runtime error: invalid memory address or nil pointer dereference goroutine 431935 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1.1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:351 +0x5d
panic({0xa4c5c0?, 0x1268d90?})
	runtime/panic.go:792 +0x132
github.com/microsoft/typescript-go/internal/ast.IsPropertyAccessExpression(...)
	github.com/microsoft/typescript-go/internal/ast/ast.go:6127
github.com/microsoft/typescript-go/internal/ls.getCallOrNewExpression(0xc148920008?)
	github.com/microsoft/typescript-go/internal/ls/hover.go:280 +0x12
github.com/microsoft/typescript-go/internal/ls.getSignaturesAtLocation(0xc148920008, 0xc147297088?, 0x0, 0xc147297088)
	github.com/microsoft/typescript-go/internal/ls/hover.go:268 +0x65
github.com/microsoft/typescript-go/internal/ls.getQuickInfoAndDeclarationAtLocation(0xc148920008, 0xc148920008?, 0xc147297088)
	github.com/microsoft/typescript-go/internal/ls/hover.go:173 +0x1785
github.com/microsoft/typescript-go/internal/ls.getQuickInfoAndDocumentationForSymbol(0x46fc39?, 0x40?, 0xad6ca0?)
	github.com/microsoft/typescript-go/internal/ls/hover.go:49 +0x1f
github.com/microsoft/typescript-go/internal/ls.createCompletionDetailsForSymbol(0xc0651d3040, 0xc10265a0e8, 0xc148920008, 0xc147297088, {0x0, 0x0, 0xc136fbfe88?})
	github.com/microsoft/typescript-go/internal/ls/completions.go:4831 +0x17a
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionItemDetails(0xc071959200, {0xd39eb0, 0xc1494fc730}, 0xc14729d180, 0x55a6, 0xc147297088, 0xc0651d3040, 0xc05cd03f00, 0xc0003b5290, 0xc136fbfe88)
	github.com/microsoft/typescript-go/internal/ls/completions.go:4671 +0x2b1
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ResolveCompletionItem(0xc071959200, {0xd39eb0, 0xc1494fc730}, 0xc0651d3040, 0xc05cd03f00, 0xc0003b5290, 0xc1312a6e88)
	github.com/microsoft/typescript-go/internal/ls/completions.go:4607 +0xb1
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleCompletionItemResolve(0xc00019ea20, {0xd39eb0, 0xc1494fc730}, 0xc071fda960)
	github.com/microsoft/typescript-go/internal/lsp/server.go:733 +0x145
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0xc147e16848?, {0xd39eb0?, 0xc1494fc730?}, 0xc03017dbc0?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:496 +0x8f
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:364 +0x75
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 8
	github.com/microsoft/typescript-go/internal/lsp/server.go:382 +0x4d2
```

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #1402, a crash in hover code called by completionItem/resolve.
Also fixes another completionItem/resolve crash that resulted from not including data for keyword completion items.

### CODE REVIEW

File: internal/ls/hover.go [hunk 1]
```diff
@@ -277,6 +277,9 @@ func getSignaturesAtLocation(c *checker.Checker, symbol *ast.Symbol, kind checke
 }
 
 func getCallOrNewExpression(node *ast.Node) *ast.Node {
+	if node.Parent == nil {
+		return nil
```
Comment (weswigham) [inline internal/ls/hover.go:281]: Am I weird for thinking that we should be OK with `if node.Kind == ast.SourceFile { return nil }` here, but the general case should be `if node.Parent == nil { panic("!!!") }`? Since it implies we're working with an unparented synthetic/reparsed node which should be regarded as a bug.

Comment (gabritto) [reply internal/ls/hover.go:281]: That's a valid point, I'll update it. But we typically didn't do it in Strada, I think we just checked at the very beginning of an API call if the node was a tree node and assumed navigating from that one would only ever get us other tree nodes.

**Review by sandersn — APPROVED** [review]
