### PR TITLE
Generate remaining sig help tests, fix remaining bugs

### LINKED ISSUE #1495: Signature help may not respect capabilities
Current code for signature help has the following:

```
var activeParameter *lsproto.UintegerOrNull
if argumentInfo.argumentIndex == nil {
	if clientOptions.SignatureInformation.NoActiveParameterSupport != nil && *clientOptions.SignatureInformation.NoActiveParameterSupport {
		activeParameter = nil
	}
} else {
	activeParameter = &lsproto.UintegerOrNull{Uinteger: ptrTo(uint32(*argumentInfo.argumentIndex))}
}
```

I think there's a bug because it needs to be set to `0` or something if `NoActiveParameterSupport` is not set or is set to true.

Should have a test that (un)sets that capability.

### PR DESCRIPTION
**Pull request by jakebailey**
- Properly handle the active parameter capability
- Don't set active parameter when client allows it
- Check `inComment` now that we have it
- Port over backup JS sig help code

Plus, generate all remaining tests that mention sig help. Some new tests with unrelated issues (other LSP features) become skipped.

Fixes #1495

### CODE REVIEW

File: internal/fourslash/tests/manual/jsDocFunctionSignatures2_test.go
Comment (DanielRosenwasser) [inline internal/fourslash/tests/manual/jsDocFunctionSignatures2_test.go:1]: Why is this one a manual test?

File: internal/fourslash/_scripts/failingTests.txt [hunk 1]
```diff
@@ -43,10 +43,17 @@ TestAutoImportTypeOnlyPreferred2
 TestAutoImportVerbatimTypeOnly1
 TestBestCommonTypeObjectLiterals
 TestBestCommonTypeObjectLiterals1
+TestCalledUnionsOfDissimilarTyeshaveGoodDisplay
```
Comment (DanielRosenwasser) [inline internal/fourslash/_scripts/failingTests.txt:46]: I hate when my unions of dissimilar tyes don't *h*aveGoodDisplay

Comment (DanielRosenwasser) [reply internal/fourslash/_scripts/failingTests.txt:46]: This one is just type-ordering, right?

**Review by DanielRosenwasser — APPROVED** [review]

File: internal/fourslash/_scripts/failingTests.txt (hunk 1 above)
Comment (jakebailey) [reply internal/fourslash/_scripts/failingTests.txt:46]: Yep, but we loved tests with hardcoded strings (for better or for worse).

File: internal/fourslash/tests/manual/jsDocFunctionSignatures2_test.go
Comment (jakebailey) [reply internal/fourslash/tests/manual/jsDocFunctionSignatures2_test.go:1]: This is a JS test that previously used removed `JSDoc` syntax, like `function(string, boolean=)`. The two manual tests are ones I fixed.
