### PR TITLE
Handle urls in import path by making vfs not panic on Url paths

### LINKED ISSUE #1905: panic: vfs: path is not absolute
## Stack trace

```
panic: vfs: path "https://deno.land/std@0.208.0/path/mod.ts" is not absolute

goroutine 49 [running]:
github.com/microsoft/typescript-go/internal/vfs/internal.RootLength({0xc00015644e, 0x29})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:23 +0x88
github.com/microsoft/typescript-go/internal/vfs/internal.SplitPath({0xc00015644e?, 0xc0001f4f20?})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:30 +0x27
github.com/microsoft/typescript-go/internal/vfs/internal.(*Common).RootAndPath(0x14890f0, {0xc00015644e?, 0xb0b3c0?})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:37 +0x25
github.com/microsoft/typescript-go/internal/vfs/internal.(*Common).Stat(0xc0001f4f30?, {0xc00015644e?, 0xc00031ea38?})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:45 +0x18
github.com/microsoft/typescript-go/internal/vfs/internal.(*Common).DirectoryExists(0xc0001f4f20?, {0xc00015644e?, 0x29?})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:62 +0x18
github.com/microsoft/typescript-go/internal/vfs/osvfs.(*osFS).DirectoryExists(0xc000366320?, {0xc00015644e?, 0xc00015644e?})
	github.com/microsoft/typescript-go/internal/vfs/osvfs/os.go:91 +0x1a
github.com/microsoft/typescript-go/internal/vfs/cachedvfs.(*FS).DirectoryExists(0xc00031ea20, {0xc00015644e, 0x29})
	github.com/microsoft/typescript-go/internal/vfs/cachedvfs/cachedvfs.go:55 +0x67
github.com/microsoft/typescript-go/internal/project.(*compilerFS).DirectoryExists(0xc000366320?, {0xc00015644e, 0x29})
	github.com/microsoft/typescript-go/internal/project/compilerhost.go:146 +0x3b
github.com/microsoft/typescript-go/internal/module.(*resolutionState).getPackageJsonInfo(0xc00012f040, {0xc00015644e, 0x29}, 0x0)
	github.com/microsoft/typescript-go/internal/module/resolver.go:1674 +0x64a
github.com/microsoft/typescript-go/internal/module.(*resolutionState).loadModuleFromSpecificNodeModulesDirectory(0xc00012f040, 0x4, {0xc000294067, 0x29}, {0xc000152cf0, 0x2e}, 0x1)
	github.com/microsoft/typescript-go/internal/module/resolver.go:963 +0x125
github.com/microsoft/typescript-go/internal/module.(*resolutionState).loadModuleFromImmediateNodeModulesDirectory(0xc00012f040, 0x4, {0xc00002cb40?, 0x29?}, 0x0)
	github.com/microsoft/typescript-go/internal/module/resolver.go:939 +0x218
github.com/microsoft/typescript-go/internal/module.(*Resolver).tryResolveFromTypingsLocation(0xc000368180, {0xc000294067, 0x29}, {0xc000234cc7, 0x27}, 0xc00016e0e0, 0x0)
	github.com/microsoft/typescript-go/internal/module/resolver.go:290 +0x2dc
github.com/microsoft/typescript-go/internal/module.(*Resolver).ResolveModuleName(0xc000368180, {0xc000294067, 0x29}, {0xc000234cc7, 0x2e}, 0x63, {0xe9b9c8, 0x0})
	github.com/microsoft/typescript-go/internal/module/resolver.go:267 +0xb08
github.com/microsoft/typescript-go/internal/compiler.(*fileLoader).resolveImportsAndModuleAugmentations(0xc000346e08, 0xc00031eb40)
	github.com/microsoft/typescript-go/internal/compiler/fileloader.go:546 +0x7e5
github.com/microsoft/typescript-go/internal/compiler.(*parseTask).load(0xc00031eb40, 0xc000346e08)
	github.com/microsoft/typescript-go/internal/compiler/filesparser.go:117 +0x3b8
github.com/microsoft/typescript-go/internal/compiler.(*filesParser).start.func1()
	github.com/microsoft/typescript-go/internal/compiler/filesparser.go:220 +0x165
github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue.func1()
	github.com/microsoft/typescript-go/internal/core/workgroup.go:42 +0x50
created by github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue in goroutine 34
	github.com/microsoft/typescript-go/internal/core/workgroup.go:40 +0x85
[Error - 10:48:13 PM] The typescript.native-preview-lsp server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 10:48:13 PM] Server process exited with code 2.
Restarting language server...
[22:48:47.066] Processed 1 file changes in 61.147µs
panic: vfs: path "https://deno.land/std@0.208.0/path/mod.ts" is not absolute

goroutine 33 [running]:
github.com/microsoft/typescript-go/internal/vfs/internal.RootLength({0xc00045014e, 0x29})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:23 +0x88
github.com/microsoft/typescript-go/internal/vfs/internal.SplitPath({0xc00045014e?, 0xc000182f20?})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:30 +0x27
github.com/microsoft/typescript-go/internal/vfs/internal.(*Common).RootAndPath(0x14890f0, {0xc00045014e?, 0xc000182f78?})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:37 +0x25
github.com/microsoft/typescript-go/internal/vfs/internal.(*Common).Stat(0xc000182f30?, {0xc00045014e?, 0xc000228a38?})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:45 +0x18
github.com/microsoft/typescript-go/internal/vfs/internal.(*Common).DirectoryExists(0xc000182f20?, {0xc00045014e?, 0x29?})
	github.com/microsoft/typescript-go/internal/vfs/internal/internal.go:62 +0x18
github.com/microsoft/typescript-go/internal/vfs/osvfs.(*osFS).DirectoryExists(0xc000268320?, {0xc00045014e?, 0xc00045014e?})
	github.com/microsoft/typescript-go/internal/vfs/osvfs/os.go:91 +0x1a
github.com/microsoft/typescript-go/internal/vfs/cachedvfs.(*FS).DirectoryExists(0xc000228a20, {0xc00045014e, 0x29})
	github.com/microsoft/typescript-go/internal/vfs/cachedvfs/cachedvfs.go:55 +0x67
github.com/microsoft/typescript-go/internal/project.(*compilerFS).DirectoryExists(0xc000268320?, {0xc00045014e, 0x29})
	github.com/microsoft/typescript-go/internal/project/compilerhost.go:146 +0x3b
github.com/microsoft/typescript-go/internal/module.(*resolutionState).getPackageJsonInfo(0xc0004249c0, {0xc00045014e, 0x29}, 0x0)
	github.com/microsoft/typescript-go/internal/module/resolver.go:1674 +0x64a
github.com/microsoft/typescript-go/internal/module.(*resolutionState).loadModuleFromSpecificNodeModulesDirectory(0xc0004249c0, 0x4, {0xc000034f08, 0x29}, {0xc000444a80, 0x2e}, 0x1)
	github.com/microsoft/typescript-go/internal/module/resolver.go:963 +0x125
github.com/microsoft/typescript-go/internal/module.(*resolutionState).loadModuleFromImmediateNodeModulesDirectory(0xc0004249c0, 0x4, {0xc00002c270?, 0x29?}, 0x0)
	github.com/microsoft/typescript-go/internal/module/resolver.go:939 +0x218
github.com/microsoft/typescript-go/internal/module.(*Resolver).tryResolveFromTypingsLocation(0xc0002001e0, {0xc000034f08, 0x29}, {0xc000034e87, 0x27}, 0xc0004520e0, 0x0)
	github.com/microsoft/typescript-go/internal/module/resolver.go:290 +0x2dc
github.com/microsoft/typescript-go/internal/module.(*Resolver).ResolveModuleName(0xc0002001e0, {0xc000034f08, 0x29}, {0xc000034e87, 0x2e}, 0x63, {0xe9b9c8, 0x0})
	github.com/microsoft/typescript-go/internal/module/resolver.go:267 +0xb08
github.com/microsoft/typescript-go/internal/compiler.(*fileLoader).resolveImportsAndModuleAugmentations(0xc000248e08, 0xc000228b40)
	github.com/microsoft/typescript-go/internal/compiler/fileloader.go:546 +0x7e5
github.com/microsoft/typescript-go/internal/compiler.(*parseTask).load(0xc000228b40, 0xc000248e08)
	github.com/microsoft/typescript-go/internal/compiler/filesparser.go:117 +0x3b8
github.com/microsoft/typescript-go/internal/compiler.(*filesParser).start.func1()
	github.com/microsoft/typescript-go/internal/compiler/filesparser.go:220 +0x165
github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue.func1()
	github.com/microsoft/typescript-go/internal/core/workgroup.go:42 +0x50
created by github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue in goroutine 7
	github.com/microsoft/typescript-go/internal/core/workgroup.go:40 +0x85
```

## Steps to reproduce

1. Run the TypeScript native-preview extension
2. Create a file with `import "https://deno.land/std@0.208.0/path/mod.ts"` or another similar URL.

### PR DESCRIPTION
**Pull request by sheetalkamat**
Fixes #1905

### CODE REVIEW

File: internal/vfs/iovfs/iofs.go [hunk 1]
```diff
@@ -112,6 +112,9 @@ func From(fsys fs.FS, useCaseSensitiveFileNames bool) FsWithSys {
 				p := tspath.RemoveTrailingDirectorySeparator(root)
 				sub, err := fs.Sub(fsys, p)
 				if err != nil {
+					if tspath.IsUrl(root) {
+						return nil
```
Comment (jakebailey) [inline internal/vfs/iovfs/iofs.go:116]: If this is `nil`, won't callers error on it when they attempt to call funcs with the FS?

Comment (sheetalkamat) [reply internal/vfs/iovfs/iofs.go:116]: All the callers handle nil fs  i think

Comment (jakebailey) [reply internal/vfs/iovfs/iofs.go:116]: Ah, indeed they do
