### PR TITLE
Acquire snapshots synchronously while blocking other requests/notifications

### LINKED ISSUE #2690: Panic - inlayHint - bad line number - from autofix/auto-formatting setup
## Stack trace

```
2026-02-05 07:20:07.683 [error] panic handling request textDocument/inlayHint: bad line number. Line: 29, lineMap length: 29
goroutine 8637650 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0xc0001b0708, {0x7ff652d618a5?, 0xc14b2abdc0?}, 0xc46f84f590)
	github.com/microsoft/typescript-go/internal/lsp/server.go:776 +0x4c
panic({0x7ff6535318c0?, 0xc180efe3c0?})
	runtime/panic.go:783 +0x132
github.com/microsoft/typescript-go/internal/ls/lsconv.(*Converters).LineAndCharacterToPosition(0xc4c092bb30, {0x7ff653a3d830, 0xc2576fe008}, {0x533f9920?, 0x7ff6?})
	github.com/microsoft/typescript-go/internal/ls/lsconv/converters.go:153 +0x2d9
github.com/microsoft/typescript-go/internal/ls/lsconv.(*Converters).FromLSPRange(0xc4c092bb30, {0x7ff653a3d830, 0xc2576fe008}, {{0x576fe008?, 0xc2?}, {0xc8cab208?, 0xc0?}})
	github.com/microsoft/typescript-go/internal/ls/lsconv/converters.go:50 +0x4c
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideInlayHint(0xc26fa09180, {0x7ff653a40388, 0xc46f84f7a0}, 0xc46f84f530)
	github.com/microsoft/typescript-go/internal/ls/inlay_hints.go:41 +0x265
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleInlayHint(0xc46f84f7a0?, {0x7ff653a40388?, 0xc46f84f7a0?}, 0xc2aded4540?, 0x7ff65362a5a0?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:1174 +0x25
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceDocumentRequestHandler[...].23({0x7ff653a40388, 0xc46f84f7a0}, 0xc46f84f590)
	github.com/microsoft/typescript-go/internal/lsp/server.go:658 +0x134
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0xc0001b0708, {0x7ff653a403c0?, 0xc2520e4960?}, 0xc46f84f590)
	github.com/microsoft/typescript-go/internal/lsp/server.go:530 +0x1c6
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:413 +0x3a
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 10
	github.com/microsoft/typescript-go/internal/lsp/server.go:437 +0x9f1
```

## Steps to reproduce

1. I have eslint setup to autofix and prettier setup to autoformat, both on save
2. make a change where eslint/prettier will change the length of the file
3. save the file
4. see the error above

logs:
```
2026-02-05 07:20:04.631 [info] Updated watches in 0s
2026-02-05 07:20:04.634 [info] handled method 'textDocument/codeAction' (44042) in 0s
2026-02-05 07:20:04.653 [info] handled method 'textDocument/diagnostic' (44039) in 77.8564ms
2026-02-05 07:20:04.669 [info] handled method 'textDocument/inlayHint' (44041) in 36.9496ms
2026-02-05 07:20:04.778 [info] handled method 'completionItem/resolve' (44040) in 193.681ms
2026-02-05 07:20:04.796 [info] handled method 'textDocument/foldingRange' (44043) in 0s
2026-02-05 07:20:04.837 [info] handled method 'textDocument/codeLens' (44044) in 0s
2026-02-05 07:20:04.837 [info] handled method 'textDocument/documentSymbol' (44045) in 0s
2026-02-05 07:20:04.915 [info] handled method 'textDocument/codeAction' (44046) in 0s
2026-02-05 07:20:04.937 [info] handled method 'textDocument/documentSymbol' (44047) in 0s
2026-02-05 07:20:04.981 [info] handled method 'textDocument/diagnostic' (44048) in 1.004ms
2026-02-05 07:20:05.397 [info] handled method 'textDocument/inlayHint' (44049) in 848.6µs
2026-02-05 07:20:05.497 [info] handled method 'textDocument/diagnostic' (44050) in 0s
2026-02-05 07:20:05.965 [info] handled method 'textDocument/inlayHint' (44051) in 0s
2026-02-05 07:20:05.967 [info] handled method 'textDocument/documentHighlight' (44052) in 0s
2026-02-05 07:20:05.998 [info] handled method 'textDocument/diagnostic' (44053) in 0s
2026-02-05 07:20:06.098 [info] handled method 'textDocument/inlayHint' (44054) in 0s
2026-02-05 07:20:06.264 [info] handled method 'textDocument/inlayHint' (44055) in 0s
2026-02-05 07:20:06.284 [info] handled method 'textDocument/documentHighlight' (44056) in 0s
2026-02-05 07:20:06.429 [info] handled method 'textDocument/documentHighlight' (44057) in 0s
2026-02-05 07:20:06.515 [info] handled method 'textDocument/diagnostic' (44058) in 510.8µs
2026-02-05 07:20:06.637 [info] handled method 'textDocument/codeAction' (44059) in 0s
2026-02-05 07:20:07.023 [info] handled method 'textDocument/diagnostic' (44060) in 0s
2026-02-05 07:20:07.197 [info] handled method 'textDocument/codeAction' (44061) in 0s
2026-02-05 07:20:07.482 [info] handled method 'textDocument/codeAction' (44062) in 0s
2026-02-05 07:20:07.513 [info] handled method 'textDocument/didChange' (<nil>) in 0s
2026-02-05 07:20:07.513 [info] Processed 1 file changes in 0s
2026-02-05 07:20:07.632 [info] handled method 'textDocument/didChange' (<nil>) in 0s
2026-02-05 07:20:07.660 [info] ======== Cloning snapshot 6017 ========
[07:20:07.512] Reason: RequestedLanguageService (pending file changes) -  Documents: [file:///c%3A/Projects/project/folder/queries.ts]
[07:20:07.513] DidChangeFiles
	[07:20:07.513] Checking for changes affecting config files
		[07:20:07.513] Summarizing file changes
		[07:20:07.513] Checking if any changed files are config files
	[07:20:07.513] Marking project c:/Projects/project/folder/tsconfig.json as dirty due to changes in c:/projects/project/folder/queries.ts
[07:20:07.513] DidRequestFile
	[07:20:07.513] Acquiring config for project
	[07:20:07.513] CompilerHost
	[07:20:07.639] Program update for c:/Projects/project/folder/tsconfig.json completed in 126.3049ms
[07:20:07.639] UpdateAutoImports
	[07:20:07.639] Building autoimport registry
		[07:20:07.639] Updated buckets and directories in 0s
		[07:20:07.639] Built autoimport registry in 0s
[07:20:07.655] Finished cloning snapshot 6017 into snapshot 6018 in 143.1098ms

2026-02-05 07:20:07.660 [info] 
2026-02-05 07:20:07.660 [info] Updated watches in 0s
2026-02-05 07:20:07.660 [info] Processed 1 file changes in 0s
2026-02-05 07:20:07.666 [info] handled method 'textDocument/diagnostic' (44063) in 153.2942ms
2026-02-05 07:20:07.678 [info] ======== Cloning snapshot 6018 ========
[07:20:07.659] Reason: RequestedLanguageService (pending file changes) -  Documents: [file:///c%3A/Projects/project/folder/queries.ts]
[07:20:07.659] DidChangeFiles
	[07:20:07.659] Checking for changes affecting config files
		[07:20:07.659] Summarizing file changes
		[07:20:07.659] Checking if any changed files are config files
	[07:20:07.659] Marking project c:/Projects/project/folder/tsconfig.json as dirty due to changes in c:/projects/project/folder/queries.ts
[07:20:07.659] DidRequestFile
	[07:20:07.659] Acquiring config for project
	[07:20:07.659] CompilerHost
	[07:20:07.669] Program update for c:/Projects/project/folder/tsconfig.json completed in 9.9536ms
[07:20:07.669] UpdateAutoImports
	[07:20:07.669] Building autoimport registry
		[07:20:07.669] Updated buckets and directories in 0s
		[07:20:07.669] Built autoimport registry in 0s
[07:20:07.674] Finished cloning snapshot 6018 into snapshot 6019 in 14.8165ms

2026-02-05 07:20:07.678 [info] 
2026-02-05 07:20:07.678 [info] Updated watches in 0s
2026-02-05 07:20:07.683 [error] panic handling request textDocument/inlayHint: bad line number. Line: 29, lineMap length: 29
goroutine 8637650 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0xc0001b0708, {0x7ff652d618a5?, 0xc14b2abdc0?}, 0xc46f84f590)
	github.com/microsoft/typescript-go/internal/lsp/server.go:776 +0x4c
panic({0x7ff6535318c0?, 0xc180efe3c0?})
	runtime/panic.go:783 +0x132
github.com/microsoft/typescript-go/internal/ls/lsconv.(*Converters).LineAndCharacterToPosition(0xc4c092bb30, {0x7ff653a3d830, 0xc2576fe008}, {0x533f9920?, 0x7ff6?})
	github.com/microsoft/typescript-go/internal/ls/lsconv/converters.go:153 +0x2d9
github.com/microsoft/typescript-go/internal/ls/lsconv.(*Converters).FromLSPRange(0xc4c092bb30, {0x7ff653a3d830, 0xc2576fe008}, {{0x576fe008?, 0xc2?}, {0xc8cab208?, 0xc0?}})
	github.com/microsoft/typescript-go/internal/ls/lsconv/converters.go:50 +0x4c
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideInlayHint(0xc26fa09180, {0x7ff653a40388, 0xc46f84f7a0}, 0xc46f84f530)
	github.com/microsoft/typescript-go/internal/ls/inlay_hints.go:41 +0x265
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleInlayHint(0xc46f84f7a0?, {0x7ff653a40388?, 0xc46f84f7a0?}, 0xc2aded4540?, 0x7ff65362a5a0?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:1174 +0x25
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceDocumentRequestHandler[...].23({0x7ff653a40388, 0xc46f84f7a0}, 0xc46f84f590)
	github.com/microsoft/typescript-go/internal/lsp/server.go:658 +0x134
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0xc0001b0708, {0x7ff653a403c0?, 0xc2520e4960?}, 0xc46f84f590)
	github.com/microsoft/typescript-go/internal/lsp/server.go:530 +0x1c6
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:413 +0x3a
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 10
	github.com/microsoft/typescript-go/internal/lsp/server.go:437 +0x9f1

2026-02-05 07:20:07.684 [error] Request textDocument/inlayHint failed.
  Message: InternalError: panic handling request textDocument/inlayHint: bad line number. Line: 29, lineMap length: 29
  Code: -32603 
2026-02-05 07:20:07.684 [info] handled method 'textDocument/inlayHint' (44065) in 128.8225ms
2026-02-05 07:20:07.684 [info] ======== Cloning snapshot 6019 ========
[07:20:07.678] DidRequestFile
	[07:20:07.678] Acquiring config for project
[07:20:07.678] UpdateAutoImports
	[07:20:07.678] Building autoimport registry
		[07:20:07.678] Updated buckets and directories in 0s
		[07:20:07.683] Built autoimport registry in 5.4611ms
[07:20:07.683] Finished cloning snapshot 6019 into snapshot 6020 in 5.4611ms

2026-02-05 07:20:07.684 [info] 
2026-02-05 07:20:07.684 [info] Updated watches in 0s
2026-02-05 07:20:07.686 [info] ======== Cloning snapshot 6020 ========
[07:20:07.683] DidRequestFile
	[07:20:07.683] Acquiring config for project
[07:20:07.683] UpdateAutoImports
	[07:20:07.683] Building autoimport registry
		[07:20:07.684] Updated buckets and directories in 533.9µs
		[07:20:07.686] Built autoimport registry in 2.5833ms
[07:20:07.686] Finished cloning snapshot 6020 into snapshot 6021 in 2.5833ms

2026-02-05 07:20:07.686 [info] 
2026-02-05 07:20:07.686 [info] Updated watches in 0s
2026-02-05 07:20:07.710 [info] handled method 'textDocument/inlayHint' (44066) in 55.4147ms
2026-02-05 07:20:07.715 [info] handled method 'textDocument/diagnostic' (44067) in 47.7255ms
2026-02-05 07:20:07.719 [info] handled method 'textDocument/diagnostic' (44064) in 164.4348ms
2026-02-05 07:20:07.840 [info] handled method 'textDocument/foldingRange' (44068) in 0s
2026-02-05 07:20:07.882 [info] handled method 'textDocument/documentSymbol' (44070) in 0s
2026-02-05 07:20:07.882 [info] handled method 'textDocument/codeLens' (44069) in 0s
2026-02-05 07:20:07.987 [info] handled method 'textDocument/codeAction' (44071) in 0s
2026-02-05 07:20:07.988 [info] handled method 'textDocument/documentSymbol' (44072) in 0s
2026-02-05 07:20:08.234 [info] handled method 'textDocument/diagnostic' (44073) in 0s
2026-02-05 07:20:08.375 [info] handled method 'textDocument/didChange' (<nil>) in 0s
2026-02-05 07:20:08.375 [info] Processed 1 file changes in 0s
2026-02-05 07:20:08.382 [info] handled method 'textDocument/didSave' (<nil>) in 0s
2026-02-05 07:20:08.395 [info] ======== Cloning snapshot 6021 ========
[07:20:08.374] Reason: RequestedLanguageService (pending file changes) -  Documents: [file:///c%3A/Projects/project/folder/queries.ts]
[07:20:08.374] DidChangeFiles
	[07:20:08.374] Checking for changes affecting config files
		[07:20:08.374] Summarizing file changes
		[07:20:08.374] Checking if any changed files are config files
	[07:20:08.374] Marking project c:/Projects/project/folder/tsconfig.json as dirty due to changes in c:/projects/project/folder/queries.ts
[07:20:08.374] DidRequestFile
	[07:20:08.374] Acquiring config for project
	[07:20:08.374] CompilerHost
	[07:20:08.386] Program update for c:/Projects/project/folder/tsconfig.json completed in 12.3511ms
[07:20:08.386] UpdateAutoImports
	[07:20:08.386] Building autoimport registry
		[07:20:08.386] Updated buckets and directories in 0s
		[07:20:08.386] Built autoimport registry in 0s
[07:20:08.391] Finished cloning snapshot 6021 into snapshot 6022 in 17.5033ms

2026-02-05 07:20:08.395 [info] 
2026-02-05 07:20:08.396 [info] Updated watches in 0s
2026-02-05 07:20:08.397 [info] Processed 1 file changes in 0s
2026-02-05 07:20:08.408 [info] handled method 'textDocument/diagnostic' (44074) in 31.5319ms
2026-02-05 07:20:08.435 [info] handled method 'textDocument/inlayHint' (44075) in 36.9563ms
2026-02-05 07:20:08.443 [info] handled method 'textDocument/diagnostic' (44076) in 34.1586ms
2026-02-05 07:20:08.595 [info] handled method 'textDocument/foldingRange' (44077) in 10.5072ms
2026-02-05 07:20:08.656 [info] handled method 'textDocument/codeLens' (44078) in 0s
2026-02-05 07:20:08.656 [info] handled method 'textDocument/documentSymbol' (44079) in 0s
2026-02-05 07:20:08.715 [info] Scheduling new diagnostics refresh...
2026-02-05 07:20:08.715 [info] handled method 'workspace/didChangeWatchedFiles' (<nil>) in 0s
2026-02-05 07:20:08.748 [info] Processed 1 file changes in 15.871ms
2026-02-05 07:20:08.748 [info] handled method 'textDocument/documentSymbol' (44080) in 15.871ms
2026-02-05 07:20:08.756 [info] handled method 'textDocument/diagnostic' (44081) in 7.8634ms
2026-02-05 07:20:09.174 [info] handled method 'textDocument/inlayHint' (44082) in 0s
2026-02-05 07:20:09.215 [info] Running scheduled diagnostics refresh
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #2690 

Imagine a sequence of

1. textDocument/didChange
2. textDocument/inlayHint
3. textDocument/didChange

When we saw the first change in the server dispatch loop, we would hold processing of the rest of the queue while that change gets pushed. Then we would resume and call `s.handleRequestOrNotification` with the inlay hint one, and (without waiting for it to complete) handle the next change, holding any more pending requests. The problem is that `s.handleRequestOrNotification` didn't get passed a snapshot; it looked at the request method, looked up the correct handler in the server, which would _then_ get acquire a snapshot (in the form of a LanguageService) and pass it to the handler. So there was a _tiny_ bit of intermediate time that was available for the next change notification to sneak in.

With this PR, handlers now have a sync portion that gets executed serially in the dispatch loop, which they use to secure a snapshot, and return a function of async work that uses the snapshot.

The downside of this is that if a client isn’t diligent about canceling old requests, we have no choice but to manifest a program for each one, even if we've built up changes that make them stale. The LSP spec says as much:

> - if a client sends a request to the server and the client state changes in a way that invalidates the response, the client should do the following:
>   - cancel the server request and ignore the result if the result is not useful for the client anymore. If necessary, the client should resend the request.
>   - keep the request running if the client can still make use of the result by, for example, transforming it to a new result by applying the state change to the result.
> - servers should therefore not decide by themselves to cancel requests simply due to that fact that a state change notification is detected in the queue. As said, the result could still be useful for the client.

So I think this is the right approach.

### CODE REVIEW

File: internal/lsp/server.go [hunk 1]
```diff
@@ -649,71 +670,75 @@ func registerRequestHandler[Req, Resp any](
...
-		resp, err := fn(s, ctx, ls, params)
-		if err != nil {
-			return err
-		}
-		if ctx.Err() != nil {
-			return ctx.Err()
-		}
-		return s.sendResult(req.ID, resp)
+		return func() error {
+			defer s.recover(ctx, req)
```
Comment (jakebailey) [inline internal/lsp/server.go:715]: Does this defer need to be duplicated for the sync portion above, so we catch panics in GetLanguageService? (And below too)

Comment (andrewbranch) [reply internal/lsp/server.go:715]: That's not how it was before—if getting the language service panics, that means cloning the snapshot panicked, so the server is in a bad state and we restart. I think I preserved the same panic vs. error behavior here but I might have goofed something.

File: internal/lsp/server.go [hunk 2]
```diff
@@ -415,32 +415,34 @@ func (s *Server) dispatchLoop(ctx context.Context) error {
...
 
-			if isBlockingMethod(req.Method) {
-				handle()
-			} else {
-				go handle()
+			if req.ID != nil {
+				s.pendingClientRequestsMu.Lock()
+				delete(s.pendingClientRequests, *req.ID)
+				s.pendingClientRequestsMu.Unlock()
 			}
```
Comment (jakebailey) [inline internal/lsp/server.go]: This deletion can now happen before doAsyncWork completes (or even runs), which I think means that requests can't be cancelled.

Probably this needs to be duplicated, or done in an IIFE so it can be deferred?

Comment (jakebailey) [reply internal/lsp/server.go]: Like:

```go
func() {
	defer func() {
		s.pendingClientRequestsMu.Lock()
		defer s.pendingClientRequestsMu.Unlock()
		delete(s.pendingClientRequests, *req.ID)
	}()

	if doAsyncWork, err := s.handleRequestOrNotification(requestCtx, req); err != nil {
		handleError(err)
	} else if doAsyncWork != nil {
		go func() {
			if lsError := doAsyncWork(); lsError != nil {
				handleError(lsError)
			}
		}()
	}
}()
```

**Comment by DanielRosenwasser** [comment]
I do feel like servicing every out-of-date request, especially for the most typical kind of client (e.g. editors) is not ideal - but probably something we can pull back on later.

File: internal/lsp/server.go [hunk 3]
```diff
@@ -415,33 +415,39 @@ func (s *Server) dispatchLoop(ctx context.Context) error {
...
+				}()
+
+				if doAsyncWork, err := s.handleRequestOrNotification(requestCtx, req); err != nil {
+					handleError(err)
+				} else if doAsyncWork != nil {
+					go func() {
+						if lsError := doAsyncWork(); lsError != nil {
+							handleError(lsError)
+						}
+					}()
```
[the remark this answers is not in the document]
Comment (andrewbranch) [reply internal/lsp/server.go]: This is true actually. We want to preserve the ability to cancel until the async work returns, because some LS requests are expensive and would like to quit if they're canceled.

[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/lsp/server.go]: Ah, shoot, my suggested change had exactly the same bug, but with defer that made it look different. I think I meant to pull it into a func like handleError and then move that around.

**Comment by andrewbranch** [comment]
Sorryyyy
