### PR TITLE
Fix off-by-one truncation in union type display

### LINKED ISSUE #3647: Behavior difference: TS7053 union count is slightly off in tsgo
## Steps to reproduce

1. Start a plain new project
    - "@typescript/native-preview": "7.0.0-dev.20260428.1",
    - "typescript": "6.0.3"
2. Run `npx tsgo --init` to get the default tsconfig. Turn on these flags as well.
    - "stableTypeOrdering": true,
3. Add `src/main.ts`. Run `npx tsc --noEmit` & `npx tsgo --noEmit` to see the difference.

```ts
// src/main.ts
declare let s: string;
declare let o1:
    | { id: '00' }
    | { id: '01' }
    | { id: '02' }
    | { id: '03' }
    | { id: '04' }
    | { id: '05' }
    | { id: '06' }
    | { id: '07' }
    | { id: '08' }
    | { id: '09' }
    | { id: '10' }
    | { id: '11' }
    | { id: '12' }
    | { id: '13' }
    | { id: '14' }
    | { id: '15' }
    | { id: '16' }
    | { id: '17' }
    | { id: '18' }
;
declare let o2:
    | typeof o1
    | { id: '19' }
;

o1[s];
o2[s];
```

## Behavior with `typescript@6.0`

```
src/main.ts:29:1 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ id: "00"; } | { id: "01"; } | { id: "02"; } | { id: "03"; } | { id: "04"; } | { id: "05"; } | { id: "06"; } | { id: "07"; } | { id: "08"; } | { id: "09"; } | { id: "10"; } | { id: "11"; } | { id: "12"; } | { id: "13"; } | { id: "14"; } | { ...; } | { ...; } | { ...; } | { ...; }'.
  No index signature with a parameter of type 'string' was found on type '{ id: "00"; } | { id: "01"; } | { id: "02"; } | { id: "03"; } | { id: "04"; } | { id: "05"; } | { id: "06"; } | { id: "07"; } | { id: "08"; } | { id: "09"; } | { id: "10"; } | { id: "11"; } | { id: "12"; } | { id: "13"; } | { id: "14"; } | { ...; } | { ...; } | { ...; } | { ...; }'.

29 o1[s];
   ~~~~~

src/main.ts:30:1 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ id: "00"; } | { id: "01"; } | { id: "02"; } | { id: "03"; } | { id: "04"; } | { id: "05"; } | { id: "06"; } | { id: "07"; } | { id: "08"; } | { id: "09"; } | { id: "10"; } | { id: "11"; } | { id: "12"; } | { id: "13"; } | { id: "14"; } | ... 4 more ... | { ...; }'.
  No index signature with a parameter of type 'string' was found on type '{ id: "00"; } | { id: "01"; } | { id: "02"; } | { id: "03"; } | { id: "04"; } | { id: "05"; } | { id: "06"; } | { id: "07"; } | { id: "08"; } | { id: "09"; } | { id: "10"; } | { id: "11"; } | { id: "12"; } | { id: "13"; } | { id: "14"; } | ... 4 more ... | { ...; }'.

30 o2[s];
   ~~~~~


Found 2 errors in the same file, starting at: src/main.ts:29
```

## Behavior with `tsgo`

```
src/main.ts:29:1 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ id: "00"; } | { id: "01"; } | { id: "02"; } | { id: "03"; } | { id: "04"; } | { id: "05"; } | { id: "06"; } | { id: "07"; } | { id: "08"; } | { id: "09"; } | { id: "10"; } | { id: "11"; } | { id: "12"; } | { id: "13"; } | { id: "14"; } | ... 4 more ... | { ...; }'.
  No index signature with a parameter of type 'string' was found on type '{ id: "00"; } | { id: "01"; } | { id: "02"; } | { id: "03"; } | { id: "04"; } | { id: "05"; } | { id: "06"; } | { id: "07"; } | { id: "08"; } | { id: "09"; } | { id: "10"; } | { id: "11"; } | { id: "12"; } | { id: "13"; } | { id: "14"; } | ... 4 more ... | { ...; }'.

29 o1[s];
   ~~~~~

src/main.ts:30:1 - error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ id: "00"; } | { id: "01"; } | { id: "02"; } | { id: "03"; } | { id: "04"; } | { id: "05"; } | { id: "06"; } | { id: "07"; } | { id: "08"; } | { id: "09"; } | { id: "10"; } | { id: "11"; } | { id: "12"; } | { id: "13"; } | { id: "14"; } | ... 5 more ... | { ...; }'.
  No index signature with a parameter of type 'string' was found on type '{ id: "00"; } | { id: "01"; } | { id: "02"; } | { id: "03"; } | { id: "04"; } | { id: "05"; } | { id: "06"; } | { id: "07"; } | { id: "08"; } | { id: "09"; } | { id: "10"; } | { id: "11"; } | { id: "12"; } | { id: "13"; } | { id: "14"; } | ... 5 more ... | { ...; }'.

30 o2[s];
   ~~~~~


Found 2 errors in the same file, starting at: src/main.ts:29
```

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/microsoft/typescript-go/issues/3647

### CODE REVIEW

File: internal/checker/nodebuilderimpl.go [hunk 1]
```diff
@@ -380,11 +380,12 @@ func (b *NodeBuilderImpl) mapToTypeNodes(list []*Type, isBareList bool) *ast.Nod
 	result := make([]*ast.Node, 0, len(list))
 
 	for i, t := range list {
```
Comment (Andarist) [inline internal/checker/nodebuilderimpl.go:382]: https://github.dev/microsoft/TypeScript/blob/f350b52331494b68c90ab02e2b6d0828d2a22a74/src/compiler/checker.ts#L7921-L7936

**Review by gabritto — APPROVED** [review]
