### PR TITLE
fix(3510): handle object-equality diagnostics

### LINKED ISSUE #3510: JS: `{} == {}` loose equality now also flagged with TS2839
conformance/plainJSTypeErrors.errors.txt.diff

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #3510

### CODE REVIEW

File: internal/checker/checker.go [hunk 1]
```diff
@@ -12147,7 +12147,9 @@ func (c *Checker) checkBinaryLikeExpression(left *ast.Node, operatorToken *ast.N
 		// control flow analysis it is possible for operands to temporarily have narrower types, and those narrower
 		// types may cause the operands to not be comparable. We don't want such errors reported (see #46475).
 		if checkMode&CheckModeTypeOnly == 0 {
-			if isLiteralExpressionOfObject(left) || isLiteralExpressionOfObject(right) {
+			if (isLiteralExpressionOfObject(left) || isLiteralExpressionOfObject(right)) &&
+				// only report for === and !== in JS, not == or !=
+				(!ast.IsInJSFile(left) || (operator == ast.KindEqualsEqualsEqualsToken || operator == ast.KindExclamationEqualsEqualsToken)) {
```
Comment (jakebailey) [inline internal/checker/checker.go:12152]: This is what Strada did, though I am surprised we special cased this.

**Review by jakebailey — APPROVED** [review]
