### PR TITLE
fix(2426): goToDefinition for pattern ambient module no longer goes to implementation 

### LINKED ISSUE #2426: goToDefinition for pattern ambient module no longer goes to implementation
After switching to `tsgo`, command-clicking a `.css` import no longer opens the `.css` file. It just opens the pattern ambient module declaration.

## Steps to reproduce

I'm pretty sure this test suite diff is already reproducing this issue:

https://github.com/microsoft/typescript-go/blob/d9178cc1fef3cedc3c1a48a652e63dd83310ea20/testdata/baselines/reference/submodule/fourslash/goToDefinition/goToDefinitionCSSPatternAmbientModule.baseline.jsonc.diff#L1-L10

## Behavior with `typescript@5.9`

Go-to-Definition = Go-to-Implementation 👍 

## Behavior with `tsgo`

Go-to-Definition = Go-to-Type-Definition 👎

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #2426

### CODE REVIEW

File: internal/ls/definition.go [hunk 1]
```diff
@@ -121,13 +129,34 @@ type fileRange struct {
...
+		targetRange := lsproto.Range{
+			Start: lsproto.Position{
+				Line:      0,
+				Character: 0,
+			},
+			End: lsproto.Position{
+				Line:      0,
+				Character: 0,
+			},
+		}
```
Comment (DanielRosenwasser) [inline internal/ls/definition.go:151]: To minimize some of the diffs, can you do something like this?

```
l.converters.ToLSPRange(reference.file, reference.file.Loc)
```

(not sure if `file` might be `nil` though)

Comment (a-tarasyuk) [reply internal/ls/definition.go:151]: @DanielRosenwasser thanks for the feedback. The file can be `nil`., even if it exists, this case is handled using a range with zero positions

https://github.com/microsoft/TypeScript/blob/f3770c9b89ba7969b163c5cea7805d5df23b2086/src/services/goToDefinition.ts#L123-L127

https://github.com/microsoft/TypeScript/blob/f3770c9b89ba7969b163c5cea7805d5df23b2086/src/services/goToDefinition.ts#L764-L774

if the file is used for the range, the selection will look like this

```
-// [||] export class Foo {}
+// [| export class Foo {}|]
```

Several differences in this PR are due to handling whitespace at the start of the file, for example

https://github.com/microsoft/typescript-go/pull/2429/files#diff-f36f4a55771065e64894e0d32a5c744439364e2a7804d6267af778e0d4ac09ddR3

https://github.com/microsoft/TypeScript/blob/f3770c9b89ba7969b163c5cea7805d5df23b2086/tests/cases/fourslash/goToDefinitionExternalModuleName.ts#L8

https://github.com/microsoft/TypeScript/blob/main/tests/baselines/reference/goToDefinitionExternalModuleName.baseline.jsonc#L3

Before
```
// [||]export class Foo {}
```

After
```
//[||] export class Foo {}
```

Comment (DanielRosenwasser) [reply internal/ls/definition.go:151]: > Several differences in this PR are due to handling whitespace at the start of the file, for example

In that case, `createLspRangeFromNode` or `createLspRangeFromRange` should take care of those differences.

Comment (a-tarasyuk) [reply internal/ls/definition.go:151]: These diffs are related to missing [chompLeadingSpace](https://github.com/microsoft/TypeScript/blob/f3770c9b89ba7969b163c5cea7805d5df23b2086/src/harness/fourslashImpl.ts#L4977) from the test parser. I’m not sure whether this behavior should be preserved.

Comment (a-tarasyuk) [reply internal/ls/definition.go:151]: There are a couple of failing formatting tests, but they’re all in `gen` folder, which shouldn’t be modified directly. We probably need to regenerate the tests for these cases. For example, Strada behaviour for some of them,

this test has 4 spaces after `///`
https://github.com/microsoft/TypeScript/blob/f3770c9b89ba7969b163c5cea7805d5df23b2086/tests/cases/fourslash/semicolonFormattingInsideAStringLiteral.ts#L3

but the behavior is validated with 3 spaces
https://github.com/microsoft/TypeScript/blob/f3770c9b89ba7969b163c5cea7805d5df23b2086/tests/cases/fourslash/semicolonFormattingInsideAStringLiteral.ts#L9

Anyway, the remaining question is whether we should proceed with or without the `chompLeadingSpace` helper.

Comment (jakebailey) [reply internal/ls/definition.go:151]: If you want to fix the generated tests, you should be able to do something like `npm run makemanual semicolonFormattingInsideAStringLiteral` and then fix the test.

Comment (a-tarasyuk) [reply internal/ls/definition.go:151]: @jakebailey, thanks for pointing that out. I've updated the failing tests to align with Strada.

File: internal/fourslash/_scripts/manualTests.txt
Comment (jakebailey) [inline internal/fourslash/_scripts/manualTests.txt:1]: Did the script sort this or something?

**Comment by jakebailey** [comment]
PR is failing because the failing tests need to be updated

File: internal/fourslash/tests/manual/semicolonFormattingInsideAStringLiteral_test.go [hunk 2]
```diff
@@ -11,7 +11,7 @@ func TestSemicolonFormattingInsideAStringLiteral(t *testing.T) {
 	fourslash.SkipIfFailing(t)
```
Comment (jakebailey) [inline internal/fourslash/tests/manual/semicolonFormattingInsideAStringLiteral_test.go]: `SkipIfFailing` should be removed from the manual tests. The script unfortunately does not do this

File: internal/fourslash/_scripts/manualTests.txt
Comment (a-tarasyuk) [reply internal/fourslash/_scripts/manualTests.txt:1]: I ran the script as-is, without any manual modifications.

File: internal/ls/definition.go [hunk 3]
```diff
@@ -121,13 +129,34 @@ type fileRange struct {
...
+		locations = append(locations, &lsproto.LocationLink{
+			OriginSelectionRange: originSelectionRange,
+			TargetUri:            lsconv.FileNameToDocumentURI(reference.fileName),
```
Comment (gabritto) [inline internal/ls/definition.go:154]: Could this ever need to go through the source mapper?
