### PR TITLE
fix(2674): fix identifier name lookup in variable declaration lists

### LINKED ISSUE #2674: Crash when fetching adjusted position of malformed variable declaration
```ts
/*$*/const const
```

If you request completions at the marker, you'll get

```
[error] panic handling request completionItem/resolve: runtime error: index out of range [0] with length 0
goroutine 15912 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0xc0001b4a08, {0x441ae5?, 0xc0023e6c40?}, 0xc00b61c420)
	github.com/microsoft/typescript-go/internal/lsp/server.go:783 +0x58
panic({0xd0b740?, 0xc00f02e270?})
	runtime/panic.go:783 +0x132
github.com/microsoft/typescript-go/internal/ls.getAdjustedLocation(0xc001e90480, 0x0, 0x0?)
	github.com/microsoft/typescript-go/internal/ls/utilities.go:686 +0xc5b
github.com/microsoft/typescript-go/internal/ls.getMeaningFromLocation(0xc006289358?)
	github.com/microsoft/typescript-go/internal/ls/utilities.go:986 +0x25
github.com/microsoft/typescript-go/internal/ls.getQuickInfoAndDeclarationAtLocation.func5(0xc0061b3a48)
	github.com/microsoft/typescript-go/internal/ls/hover.go:239 +0x267
github.com/microsoft/typescript-go/internal/ls.getQuickInfoAndDeclarationAtLocation(0xc00b8b4008, 0xc0061b3a48, 0xc001e90480)
	github.com/microsoft/typescript-go/internal/ls/hover.go:400 +0x29f
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getQuickInfoAndDocumentationForSymbol(0xc000838000, 0xc00b8b4008, 0x67bfc0?, 0xc00b028808?, {0xc000352480, 0x8})
	github.com/microsoft/typescript-go/internal/ls/hover.go:64 +0x30
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).createCompletionDetailsForSymbol(0xc000838000, 0xc008e68960, 0xc0061b3a48, 0xc00b8b4008, 0xc001e90480, {0x0, 0x0, 0xc0040a7008?}, {0xc000352480, 0x8})
	github.com/microsoft/typescript-go/internal/ls/completions.go:5031 +0x3c5
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionItemDetails(0xc000838000, {0x1115848, 0xc00b61c540}, 0xc006f82008, 0xc00b8b4008, 0x1, 0xc008c0fc08, 0xc008e68960, 0xc00e503f40)
	github.com/microsoft/typescript-go/internal/ls/completions.go:4868 +0x4f3
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ResolveCompletionItem(0xc000838000, {0x1115848, 0xc00b61c540}, 0xc008e68960, 0xc00e503f40)
	github.com/microsoft/typescript-go/internal/ls/completions.go:4798 +0x105
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleCompletionItemResolve(0xc0001b4a08, {0x1115848, 0xc00b61c540}, 0xc008e68960, 0xc00b61c420)
	github.com/microsoft/typescript-go/internal/lsp/server.go:1126 +0x13d
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerRequestHandler[...].37({0x1115848, 0xc00b61c540}, 0xc00b61c420)
	github.com/microsoft/typescript-go/internal/lsp/server.go:642 +0xb6
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0xc0001b4a08, {0x1115880?, 0xc0090ba410?}, 0xc00b61c420)
	github.com/microsoft/typescript-go/internal/lsp/server.go:533 +0xec
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:412 +0x3a
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 36
	github.com/microsoft/typescript-go/internal/lsp/server.go:436 +0x9f1
```

However, weirdly enough, the panic won't be shown as a notification.

If you try find-all-references:

```
Received response 'textDocument/references - (1844)' in 1ms. Request failed: InternalError: panic handling request textDocument/references: Panics occurred during cross-project handling: [panic handling request: runtime error: index out of range [0] with length 0
goroutine 16098 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/microsoft/typescript-go/internal/ls.handleCrossProject[...].func2.1.1()
	github.com/microsoft/typescript-go/internal/ls/crossproject.go:89 +0x58
panic({0xd0b740?, 0xc0043940a8?})
	runtime/panic.go:783 +0x132
github.com/microsoft/typescript-go/internal/ls.getAdjustedLocation(0xc004e3e660, 0x0, 0xc00479a708?)
	github.com/microsoft/typescript-go/internal/ls/utilities.go:686 +0xc5b
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getReferencedSymbolsForNode(0xc00be29600, {0x1115848, 0xc00c9ecea0}, 0x4, 0xc004e3e660, 0xc007131448, {0xc009008808, 0x2c4, 0x2ff}, {0x0, ...})
	github.com/microsoft/typescript-go/internal/ls/findallreferences.go:942 +0xad7
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getSymbolAndEntries(0xc00479a708?, {0x1115848?, 0xc00c9ecea0?}, 0xfd8360?, 0x1?, 0x1?, 0x0?, 0x0?)
	github.com/microsoft/typescript-go/internal/ls/findallreferences.go:650 +0x7f
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).provideSymbolsAndEntries(0xc00be29600, {0x1115848, 0xc00c9ecea0}, {0xc0060d2f60?, 0xc00c9ecea0?}, {0x60d2f60?, 0xc0?}, 0x0, 0x0)
	github.com/microsoft/typescript-go/internal/ls/findallreferences.go:601 +0x170
github.com/microsoft/typescript-go/internal/ls.handleCrossProject[...].func2.1()
	github.com/microsoft/typescript-go/internal/ls/crossproject.go:105 +0x231
github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue.func1()
	github.com/microsoft/typescript-go/internal/core/workgroup.go:40 +0x13
sync.(*WaitGroup).Go.func1()
	sync/waitgroup.go:239 +0x4a
created by sync.(*WaitGroup).Go in goroutine 16097
	sync/waitgroup.go:237 +0x73
```

The UI actually *will* surface that one.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #2674

### CODE REVIEW

File: internal/ls/utilities.go [hunk 1]
```diff
@@ -683,8 +683,12 @@ func getAdjustedLocation(node *ast.Node, forRename bool, sourceFile *ast.SourceF
 	// /**/<var|let| [|n:ame|] ...
 	if node.Kind == ast.KindVarKeyword || node.Kind == ast.KindConstKeyword || node.Kind == ast.KindLetKeyword &&
 		ast.IsVariableDeclarationList(parent) && len(parent.AsVariableDeclarationList().Declarations.Nodes) == 1 {
-		if decl := parent.AsVariableDeclarationList().Declarations.Nodes[0].AsVariableDeclaration(); ast.IsIdentifier(decl.Name()) {
-			return decl.Name()
+		declarations := parent.AsVariableDeclarationList().Declarations.Nodes
+		if len(declarations) > 0 {
```
Comment (jakebailey) [inline internal/ls/utilities.go]: How can this not be true if the len of the declarations node list is 1, per the check above?

Comment (ahejlsberg) [reply internal/ls/utilities.go]: Looks to me like some parentheses are missing around the or-ed together checks for `node.Kind`.

Comment (a-tarasyuk) [reply internal/ls/utilities.go]: That’s my bad — I completely missed it.

Alt Text

File: internal/ls/utilities.go [hunk 2]
```diff
@@ -681,7 +681,7 @@ func getAdjustedLocation(node *ast.Node, forRename bool, sourceFile *ast.SourceF
 	}
 
 	// /**/<var|let| [|n:ame|] ...
```
Comment (DanielRosenwasser) [inline internal/ls/utilities.go]: Original comment was

```suggestion
	// /**/<var|let|const> [|name|] ...
```

if you can fix that while you're here.

File: internal/ls/utilities.go [hunk 3]
```diff
@@ -681,7 +681,7 @@ func getAdjustedLocation(node *ast.Node, forRename bool, sourceFile *ast.SourceF
...
-	if node.Kind == ast.KindVarKeyword || node.Kind == ast.KindConstKeyword || node.Kind == ast.KindLetKeyword &&
+	if (node.Kind == ast.KindVarKeyword || node.Kind == ast.KindConstKeyword || node.Kind == ast.KindLetKeyword) &&
 		ast.IsVariableDeclarationList(parent) && len(parent.AsVariableDeclarationList().Declarations.Nodes) == 1 {
 		if decl := parent.AsVariableDeclarationList().Declarations.Nodes[0].AsVariableDeclaration(); ast.IsIdentifier(decl.Name()) {
```
Comment (DanielRosenwasser) [inline internal/ls/utilities.go]: Wondering if others feel like this is worth breaking into some nested `if`s or if it's fine as-is. I'm on the fence.

Comment (a-tarasyuk) [reply internal/ls/utilities.go]: @DanielRosenwasser Personally, I’d vote for declaring the variable outside of the if. However, if the project convention is to keep it inside, I’m fine with reverting.

Comment (jakebailey) [reply internal/ls/utilities.go]: I'd say no because this is ported code, but I don't particularly care
