### PR TITLE
Handle long paths in native-preview tsgo entrypoint

### LINKED ISSUE #2441: using tsgo fails with pnpx
## Steps to reproduce
try to start a tsgo build via pnpx.

pnpx --package=@typescript/native-preview@latest tsgo --project "D:\git\collaboration\apis.core2\src\Siemens.Collaboration.Js\tsconfig.json" --noEmit --pretty false

 I get the following error, which indicates that a file isn't found. If I do the same with tsc and the latest typescript package it works.

## Behavior with `typescript@5.9`

it works.

## Behavior with `tsgo`

======= Build WebProject siemens.collaboration.js ========
1>  WebBuildCommand: pnpx --package=@typescript/native-preview@latest tsgo --project "D:\git\collaboration\apis.core2\src\Siemens.Collaboration.Js\tsconfig.json" --noEmit --pretty false
1>  Progress: resolved 1, reused 0, downloaded 0, added 0
1>  Packages: +2
1>  ++
1>  Progress: resolved 8, reused 0, downloaded 1, added 1
1>  Progress: resolved 8, reused 0, downloaded 2, added 2, done
1>  node:internal/child_process:1120
1>      result.error = new ErrnoException(result.error, 'spawnSync ' + options.file);
1>                     ^
1>
1>  <ref *1> Error: spawnSync C:\Users\adfrth5\AppData\Local\pnpm-cache\dlx\257d8c301d9980ff4d4d255ce715aca448f1288d9c35e8e42ee0b22e11bdb394\19b8de9f98d-4fac\node_modules\.pnpm\@typescript+native-preview-win32-x64@7.0.0-dev.20260105.1\node_modules\@typescript\native-preview-win32-x64\lib\tsgo.exe ENOENT
1>      at Object.spawnSync (node:internal/child_process:1120:20)
1>      at spawnSync (node:child_process:901:24)
1>      at execFileSync (node:child_process:944:15)
1>      at file:///C:/Users/adfrth5/AppData/Local/pnpm-cache/dlx/257d8c301d9980ff4d4d255ce715aca448f1288d9c35e8e42ee0b22e11bdb394/19b8de9f98d-4fac/node_modules/.pnpm/@typescript+native-preview@7.0.0-dev.20260105.1/node_modules/@typescript/native-preview/bin/tsgo.js:9:5
1>      at ModuleJob.run (node:internal/modules/esm/module_job:345:25)
1>      at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:651:26)
1>      at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5) {
1>    errno: -4058,
1>    code: 'ENOENT',
1>    syscall: 'spawnSync C:\\Users\\adfrth5\\AppData\\Local\\pnpm-cache\\dlx\\257d8c301d9980ff4d4d255ce715aca448f1288d9c35e8e42ee0b22e11bdb394\\19b8de9f98d-4fac\\node_modules\\.pnpm\\@typescript+native-preview-win32-x64@7.0.0-dev.20260105.1\\node_modules\\@typescript\\native-preview-win32-x64\\lib\\tsgo.exe',
1>    path: 'C:\\Users\\adfrth5\\AppData\\Local\\pnpm-cache\\dlx\\257d8c301d9980ff4d4d255ce715aca448f1288d9c35e8e42ee0b22e11bdb394\\19b8de9f98d-4fac\\node_modules\\.pnpm\\@typescript+native-preview-win32-x64@7.0.0-dev.20260105.1\\node_modules\\@typescript\\native-preview-win32-x64\\lib\\tsgo.exe',
1>    spawnargs: [
1>      '--project',
1>      'D:\\git\\collaboration\\apis.core2\\src\\Siemens.Collaboration.Js\\tsconfig.json',
1>      '--noEmit',
1>      '--pretty',
1>      'false'
1>    ],
1>    error: [Circular *1],
1>    status: null,
1>    signal: null,
1>    output: null,
1>    pid: 0,
1>    stdout: undefined,
1>    stderr: undefined
1>  }

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #2441 (theoretically)

### CODE REVIEW

File: _packages/native-preview/lib/getExePath.js [hunk 1]
```diff
@@ -41,7 +41,13 @@ export default function getExePath() {
...
     }
 
-    const exe = path.join(exeDir, "tsgo" + (process.platform === "win32" ? ".exe" : ""));
+    let exe = path.join(exeDir, "tsgo");
+    if (process.platform === "win32") {
+        exe += ".exe";
+        if (exe.length >= 248) {
+            exe = "\\\\?\\" + exe;
+        }
+    }
```
Comment (jakebailey) [inline _packages/native-preview/lib/getExePath.js:50]: It's not super clear to me where to make this fix; this fixes it for both VS Code and the CLI, but it's unclear if this will come to bite us or if we should copy/paste it into both places given it's really `child_process`'s fault for not handling this

**Review by DanielRosenwasser — APPROVED** [review]

File: _packages/native-preview/lib/getExePath.js [hunk 2]
```diff
@@ -41,7 +41,13 @@ export default function getExePath() {
         }
     }
 
-    const exe = path.join(exeDir, "tsgo" + (process.platform === "win32" ? ".exe" : ""));
+    let exe = path.join(exeDir, "tsgo");
+    if (process.platform === "win32") {
+        exe += ".exe";
+        if (exe.length >= 248) {
+            exe = "\\\\?\\" + exe;
```
Comment (jakebailey) [inline _packages/native-preview/lib/getExePath.js:48]:
```suggestion
            exe = `\\?\` + exe;
```

File: _packages/native-preview/lib/getExePath.js (hunk 1 above)
Comment (DanielRosenwasser) [reply _packages/native-preview/lib/getExePath.js:50]: Honestly, you might consider sending a PR to Node.js.
