### PR TITLE
Revisit folding range logic for JSDoc imports

### LINKED ISSUE #2785: Panic in textDocument/foldingRange with multiple subsequent JSDoc @import statements
## Stack trace

```
panic handling request textDocument/foldingRange: Cannot create token from reparsed node of kind KindJSImportDeclaration
goroutine 1699 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:26 +0x8e
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x29393413ae08, {0x7e1e018, 0x293938bdaae0}, 0x293938f6f0b0)
	/Users/apendua/Repos/apendua/typescript-go/internal/lsp/server.go:791 +0x5e
panic({0x7b86480?, 0x29393687b030?})
	/usr/local/go/src/runtime/panic.go:860 +0x14f
github.com/microsoft/typescript-go/internal/ast.(*SourceFile).GetOrCreateToken(0x293938a8a008, 0x3b, 0x7, 0x8, 0x29393422e7e0, 0x0)
	/Users/apendua/Repos/apendua/typescript-go/internal/ast/ast.go:11020 +0x465
github.com/microsoft/typescript-go/internal/astnav.FindChildOfKind(0x29393422e7e0, 0x65, 0x293938a8a008)
	/Users/apendua/Repos/apendua/typescript-go/internal/astnav/tokens.go:754 +0x2c5
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).addNodeOutliningSpans(0x293938bb1100, {0x7e1e018, 0x293938bdaae0}, 0x293938a8a008)
	/Users/apendua/Repos/apendua/typescript-go/internal/ls/folding.go:63 +0x73b
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideFoldingRange(0x293938bb1100, {0x7e1e018, 0x293938bdaae0}, {0x29393435a1e0, 0x50})
	/Users/apendua/Repos/apendua/typescript-go/internal/ls/folding.go:20 +0xe5
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleFoldingRange(0x29393413ae08, {0x7e1e018, 0x293938bdaae0}, 0x293938bb1100, 0x2939393001a0)
	/Users/apendua/Repos/apendua/typescript-go/internal/lsp/server.go:1106 +0x96
github.com/microsoft/typescript-go/internal/lsp.registerLanguageServiceDocumentRequestHandler[...].func1({0x7e1e018, 0x293938bdaae0}, 0x293938f6f0b0)
	/Users/apendua/Repos/apendua/typescript-go/internal/lsp/server.go:673 +0x2fc
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x29393413ae08, {0x7e1e018, 0x293938bdaae0}, 0x293938f6f0b0)
	/Users/apendua/Repos/apendua/typescript-go/internal/lsp/server.go:540 +0x11e
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	/Users/apendua/Repos/apendua/typescript-go/internal/lsp/server.go:419 +0x65
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 19
	/Users/apendua/Repos/apendua/typescript-go/internal/lsp/server.go:443 +0x605
```

## Steps to reproduce

In VS Code, create a JS file with the following content and save:
```javascript
/**
 * @import {a} from "a";
 * @import {b} from "b";
 */
```
The editor reports an error:

Image

and more details about the panic can be found in `tsserver` output.

### PR DESCRIPTION
**Pull request by apendua**
Fixes #2785

### CODE REVIEW

File: internal/ls/folding.go [hunk 1]
```diff
@@ -58,6 +58,12 @@ func (l *LanguageService) adjustFoldingEnd(ranges []*lsproto.FoldingRange, sourc
 	return result
 }
 
+func isAnyFoldableImportSyntax(node *ast.Node) bool {
+	// Since KindJSImportDeclaration is now considered one of the "import syntax" kinds,
+	// we want to make sure to only fold import declarations that haven't been re-parsed.
```
Comment (jakebailey) [inline internal/ls/folding.go]: Maybe we should skip any reparsed node, period?

File: internal/fourslash/tests/outliningSpansForImportTagJSDoc_test.go
Comment (jakebailey) [inline internal/fourslash/tests/outliningSpansForImportTagJSDoc_test.go:1]: move this to the parent dir, tests

Comment (apendua) [reply internal/fourslash/tests/outliningSpansForImportTagJSDoc_test.go:1]: done

File: internal/ls/folding.go (hunk 1 above)
Comment (apendua) [reply internal/ls/folding.go]: Do you mean something like:
```go
func (l *LanguageService) addNodeOutliningSpans(ctx context.Context, sourceFile *ast.SourceFile) []*lsproto.FoldingRange {
  // ...
  foldableNodes := make([]*ast.Node, 0, len(statements.Nodes))
  for _, node := range statements.Nodes {
    if node.Flags&ast.NodeFlagsReparsed == 0 {
      foldableNodes = append(foldableNodes, node)
    }
  }
  // business as usual but use foldableNodes
}
```
I guess that would work too and would be functionally equivalent, so we can go that path if you believe it will be better for readability.

Btw, it seems like we are performing the flag check in `visitNode()` anyway, but the reason for this panic is because we have the special handling of import statements.

Comment (apendua) [reply internal/ls/folding.go]: I also rephrased the comment for `isFoldableImportNode` to better explain the purpose of this helper function.

Comment (jakebailey) [reply internal/ls/folding.go]: Right, yes, I'd want it to be similar to other checks.

**Comment by apendua** [comment]
@ahejlsberg Updated. I had to rework one other helper to make sure other tests are not failing. I also added some documentation to make it crystal clear to the user what does the predicate actually checks.
