### PR TITLE
Some of the changes to improve --build memory footprint

### LINKED ISSUE #1622: [bug] `tsgo --build` uses extreme amounts of memory
## Stack trace

Unfortunately I don't have one to share as it crashed my remote dev machine (used 116GB of RSS before it did).

Image

## Steps to reproduce

This is probably unique to our scale here at Canva. I attempted to build one of the TS projects in our monorepo that transitively depends upon 5k+ other TS projects. It built for ~5 mins before crashing out due to excess memory usage.

```
./built/local/tsgo --build ../canva/<omitted>/tsconfig.json
```

### PR DESCRIPTION
**Pull request by sheetalkamat**
- found that sometimes the writerPool retained program so fixed that
- Fixed source files cache to actually cache only d.ts or json files (we were earlier storing .ts files even though that wasnt intended)
- --builders = number of go routines to spawn instead of limiting number of projects to build using semaphore

Fixes #1622 (probably)

### CODE REVIEW

File: internal/compiler/program.go [hunk 1]
```diff
@@ -1405,9 +1405,10 @@ func (p *Program) Emit(ctx context.Context, options EmitOptions) *EmitResult {
 		}
 	}
 
+	newLine := p.Options().NewLine.GetNewLineCharacter()
 	writerPool := &sync.Pool{
 		New: func() any {
-			return printer.NewTextWriter(p.Options().NewLine.GetNewLineCharacter())
+			return printer.NewTextWriter(newLine)
```
Comment (jakebailey) [inline internal/compiler/program.go:1411]: oops 😄

**Comment by Zzzen** [comment]
Would you mind pushing a beta build? I’d love to give it a spin.

**Comment by jakebailey** [comment]
We don't have a way to do that; you'd have to build from source

**Comment by Zzzen** [comment]
I gave the local build a try, but I'm still running into OOM. tsgo seems to be consuming significantly more memory compared to the previous tsc.

**Comment by sheetalkamat** [comment]
@Zzzen  is it possible to share repro. What does extendedDiagnostics show..

**Comment by sheetalkamat** [comment]
> I gave the local build a try, but I'm still running into OOM. tsgo seems to be consuming significantly more memory compared to the previous tsc.

Sorry there were some mistakes when i restructured code. can you please give it a try. if it still repros, can you please share the repro steps, pprof dump, result with extendedDiagnostics so i can look into it some more

**Comment by Zzzen** [comment]
It's a proprietary project, so I can't share the actual code.
That said, I managed to track down the issue — it’s not related to builder mode at all. The real problem is with type checking / declaration emitting.In short:

In TypeScript 5.9 my function
```ts
export function f(input: DeepReadonly<LargeType>) { … }
```

gets emitted cleanly like this in the .d.ts:
```ts
export function f(input: DeepReadonly<LargeType>): void;
```

But with tsgo, `DeepReadonly<LargeType>` gets fully expanded, which turns the declaration file into something huge like
```ts
export function f(input: { prop1: { propA: … }, prop2: ……… }): void;
```

`DeepReadonly<LargeType>` is used a lot in my project, which makes this particularly painful.

**Comment by jakebailey** [comment]
Can you try building #2459 and see if that fixes your issue?

**Comment by Zzzen** [comment]
Just built and tried this branch #2459 on my project — the emitted types / .d.ts files now match what tsc produces! 
Please merge soon 🙏

**Comment by jakebailey** [comment]
> Please merge soon

I assume you mean that other PR?

**Review by andrewbranch — APPROVED** [review]

**Comment by sheetalkamat** [comment]
> eople play with `--builders 1` so it's probably okay to clamp this down for now.

its not fully concurrent as that was crazy with memory when you had to build 100+ projects

**Comment by Zzzen** [comment]
>> Please merge soon

> I assume you mean that other PR?

yeah, i mean https://github.com/microsoft/typescript-go/pull/2459
