### PR TITLE
Invalidate caches on batches of 1000+ watch changes

### LINKED ISSUE #1646: LSP: changes to files not open in editor are sometimes not picked up
Essentially after switching branch, sometimes, particularly when alot of file changes are made, tsgo seems to have an old version of project files *not* open in the editor, cached.

Issue started occurring after snapshot LSP was merged.

## Steps to reproduce

I was re-testing https://github.com/microsoft/typescript-go/issues/1265 but I have seen this just in day-2-day too.

1. switch branch - have a file open that uses something from a file edited on another branch

logs do detect file changes:

```
======== Cloning snapshot 92 ========
[08:23:47.134] DidChangeFiles
	[08:23:47.134] Checking for changes affecting config files
		[08:23:47.134] Summarizing file changes
		[08:23:47.134] Checking if any changed files are config files
[08:23:47.134] DidRequestFile
	[08:23:47.134] Acquiring config for project
	[08:23:47.134] CompilerHost
	[08:23:47.965] Program update for c:/Projects/x/y/src/frontend/tsconfig.json completed in 831.249ms
[08:23:47.965] Finished cloning snapshot 92 into snapshot 93 in 831.249ms

[08:23:48.033] 
Project 'c:/Projects/x/y/src/frontend/tsconfig.json'
	Files (15029)
-----------------------------------------------

[08:23:48.053] Updated watch: affecting locations for c:/Projects/x/y/src/frontend/tsconfig.json watcher 200
[08:23:48.053] 	C:/Projects/x/y/node_modules/**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json}
[08:23:48.053] 	C:/Projects/x/y/src/openapi-clientlib/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json}
[08:23:48.053] 	C:/Projects/x/y/src/toolkit/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json}
[08:23:48.053] 	C:/Projects/x/y/src/ui/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json}
[08:23:48.053] 	C:/Projects/x/y/tools/sharedtypes/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json}
[08:23:48.053] 	c:/Projects/x/y/node_modules/**/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json}
[08:23:48.053] 	c:/Projects/x/t/src/frontend/*.{js,jsx,mjs,cjs,ts,tsx,mts,cts,json}
[08:23:48.053] 
[08:23:48.284] Updated watch: failed lookups for c:/Projects/x/y/src/frontend/tsconfig.json watcher 201
<long list of every file/folder in the project>
[08:23:48.286] Scheduling new diagnostics refresh...
[08:23:48.297] Scheduling new snapshot update...
======== Cloning snapshot 94 ========
[08:23:48.531] DidRequestFile
	[08:23:48.531] Acquiring config for project
[08:23:48.531] Finished cloning snapshot 94 into snapshot 95 in 0s


======== Cloning snapshot 95 ========
[08:23:48.531] DidRequestFile
	[08:23:48.531] Acquiring config for project
[08:23:48.531] Finished cloning snapshot 95 into snapshot 96 in 0s


======== Cloning snapshot 93 ========
[08:23:47.965] DidRequestFile
	[08:23:47.965] Acquiring config for project
	[08:23:47.965] CompilerHost
	[08:23:48.529] Program update for c:/Projects/x/y/src/portfolio/tsconfig.json completed in 563.3994ms
[08:23:48.531] Finished cloning snapshot 93 into snapshot 94 in 566.0796ms

<another updated watch and updated watch failed>

[08:23:48.786] Running scheduled diagnostics refresh
[08:23:48.788] Processed 978 file changes in 1.4577ms
[08:23:48.788] Canceling scheduled snapshot update and performing one now
======== Cloning snapshot 96 ========
[08:23:48.789] DidChangeFiles
	[08:23:48.789] Checking for changes affecting config files
		[08:23:48.789] Summarizing file changes
		[08:23:48.790] Checking if any changed files are config files
[08:23:48.790] DidRequestFile
	[08:23:48.790] Acquiring config for project
[08:23:48.791] Finished cloning snapshot 96 into snapshot 97 in 2.5711ms


[08:23:48.791] Scheduling new diagnostics refresh...
[08:23:49.291] Running scheduled diagnostics refresh
[08:23:59.519] Scheduling new snapshot update...
[08:24:00.037] Processed 69762 file changes in 15.3193ms
[08:24:00.037] Running scheduled snapshot update
======== Cloning snapshot 97 ========
[08:24:00.037] DidChangeFiles
	[08:24:00.037] Checking for changes affecting config files
		[08:24:00.037] Summarizing file changes
		[08:24:00.049] Checking if any changed files are config files
		[08:24:00.050] Checking if any of 9769 created files match root files for config c:/projects/x/y/src/frontend/tsconfig.json
		[08:24:00.050] Checking if any of 9769 created files match root files for config c:/projects/x/y/src/portfolio/tsconfig.json
	[08:24:00.061] Marking project c:/Projects/x/y/src/frontend/tsconfig.json as dirty
	[08:24:00.069] Marking project c:/Projects/x/y/src/portfolio/tsconfig.json as dirty
[08:24:00.069] Finished cloning snapshot 97 into snapshot 98 in 32.6397ms
```

2. an error appears in the open file that is incorrect. e.g.
Image

3. wait 9 minutes - no change in errors or tslog

```
[08:24:21.054] Scheduling new snapshot update...
[08:24:21.555] Processed 2 file changes in 0s
[08:24:21.555] Running scheduled snapshot update
======== Cloning snapshot 102 ========
[08:24:21.555] DidChangeFiles
	[08:24:21.555] Checking for changes affecting config files
		[08:24:21.555] Summarizing file changes
		[08:24:21.555] Checking if any changed files are config files
[08:24:21.555] Finished cloning snapshot 102 into snapshot 103 in 0s


[08:24:21.555] Scheduling new diagnostics refresh...
[08:24:22.055] Running scheduled diagnostics refresh
```

4. open the file that changed with the branch switch, where it says the function doesn't exist, but it does since the branch change

5. the error caused by having an old version of the file disappears - other errors from other files updated still remain

### PR DESCRIPTION
**Pull request by andrewbranch**
- Any time more than 1000 watch changes are processed in a batch, clear the FS cache
- If any of those changes are outside node_modules, also assume that all known tsconfigs could be affected

1000 was picked arbitrarily, but I’m not sure what else we can do.

Fixes #1646

### CODE REVIEW

**Comment by jakebailey** [comment]
One worry I have with this approach is that now that we are watching basically all TS/JS within the workspace, that some other build system like vite or angular or something writes a bunch of dist files and we detect those and then effectively restart everything. Is that something that can happen or do we filter this somehow? I assume we don't given the filtering is the expensive thing we are trying to avoid...

**Comment by andrewbranch** [comment]
Filtering is not expensive, but how would you propose we filter for that?

**Comment by andrewbranch** [comment]
I suppose the happy case is that none of the changes we pick up are in our cache at all. That's easy to check for.

**Comment by andrewbranch** [comment]
Although, that doesn’t help much with regard to new files being created on disk—if you add 1000 new files, is that an external build tool or a `git switch` into a branch with a new component? We will definitely want to implement watch ignore settings like we have in TS Server, but maybe I can make these heuristics smarter still.

**Comment by andrewbranch** [comment]
Refactored with a bit more of a sophisticated strategy. In order for the 1000+ changes to trigger a cache invalidation, we have to find _something_ in the events that were collected that impacts the cache in question. If something is found, only then do we assume other events that affect the same cache could have been missed.

File: internal/project/filechange.go [hunk 1]
```diff
@@ -38,8 +44,20 @@ type FileChangeSummary struct {
...
+	// event of a file outside a node_modules directory.
+	IncludesWatchChangeOutsideNodeModules bool
 }
 
 func (f FileChangeSummary) IsEmpty() bool {
 	return f.Opened == "" && len(f.Closed) == 0 && f.Changed.Len() == 0 && f.Created.Len() == 0 && f.Deleted.Len() == 0
 }
+
+func (f FileChangeSummary) HasExcessiveWatchEvents() bool {
+	return f.Created.Len()+f.Deleted.Len()+f.Changed.Len() > excessiveChangeThreshold
```
Comment (jakebailey) [inline internal/project/filechange.go:58]: I assume that if this turns out to be a negative change (maybe, a npm install repeatedly modifying 1000 files over a long period of time), we can disable this? (I guess though, it's still a net win.)

**Review by jakebailey — APPROVED** [review]

File: internal/project/filechange.go (hunk 1 above)
Comment (andrewbranch) [reply internal/project/filechange.go:58]: Yeah, this is very tweakable. I tested this out ad-hoc on some repos, and the `npm install` case is very fast / non-disruptive because of the way this isolates node_modules cache invalidation from everything else. The big `git switch` is much more analogous to just restarting the server.
