### PR TITLE
fix: panic in `regexp.MustCompile` when building wildcarddirectories with non ascii characters

### LINKED ISSUE #2236: Crashing when project path contains Chinese characters.
## Stack trace

```
panic: regexp: Compile(`(?i)^((/Users/x/develop/proj_\副\本/src/node(/.+?)?/[^/]*)|(/Users/x/develop/proj_\副\本/src/node\-common(/.+?)?/[^/]*)|(/Users/x/develop/proj_\副\本/node_modules(/.+?)?/[^/]*)|(/Users/x/develop/proj_\副\本/src/[^/]*/[^/]*/node_modules(/.+?)?/[^/]*))($|/)`): error parsing regexp: invalid escape sequence: `\副`
```

## Steps to reproduce

1.Create a project with Chinese characters in its name and initialize node_modules.
2.Use the VS Code TypeScript Native plugin and start the service.

### PR DESCRIPTION
**Pull request by camc314**
Fixes #2236

### CODE REVIEW

**Comment by jakebailey** [comment]
I'm not sure I understand; if this were panicking wouldn't everything be broken right now?

**Comment by camc314** [comment]
> I'm not sure I understand; if this were panicking wouldn't everything be broken right now?

sorry should've clarified in the PR description, apparently this is only an issue when you've got non-ascii characters inside the path on windows machines.


```
panic: regexp: Compile(`(?i)^((C\:/Users/TobiasL\ægreid/dev/app/frontend/packages/react/src(/.+?)?/[^/]*\.test\.ts[^/]*)|(C\:/Users/TobiasL\ægreid/dev/app/frontend/packages/react/src(/.+?)?/[^/]*\.stories\.ts[^/]*)|(C\:/Users/TobiasL\ægreid/dev/app/frontend/packages/react/src(/.+?)?/[^/]*\.mdx))($|/)`): error parsing regexp: invalid escape sequence: `\æ`
goroutine 299 [running]:
regexp.MustCompile({0xc0000b0840, 0x151})
        /opt/hostedtoolcache/go/1.25.0/x64/src/regexp/regexp.go:313 +0xb4
github.com/microsoft/typescript-go/internal/tsoptions.getWildcardDirectories({0xc000500f70, 0x1, 0x70?}, {0xc0000a9840?, 0xc000118900?, 0x70?}, {0x28?, {0xc000118c60?, 0x7ff62e770331?}})

**Comment by jakebailey** [comment]
Ah, this is https://github.com/oxc-project/tsgolint/issues/318. I didn't realize you meant a knock-on effect from a later regex call.

File: internal/vfs/utilities.go [hunk 1]
```diff
@@ -81,11 +81,11 @@ func IsImplicitGlob(lastPathComponent string) bool {
 	return !strings.ContainsAny(lastPathComponent, ".*?")
 }
 
-// Reserved characters, forces escaping of any non-word (or digit), non-whitespace character.
-// It may be inefficient (we could just match (/[-[\]{}()*+?.,\\^$|#\s]/g), but this is future
-// proof.
+// Reserved characters - only escape actual regex metacharacters.
+// Go's regexp doesn't support \x escape sequences for arbitrary characters,
```
Comment (jakebailey) [inline internal/vfs/utilities.go:85]: We shouldn't be using regexp at all; does switching to regexp2 fix this?

Comment (jakebailey) [reply internal/vfs/utilities.go:85]: Yeah, I don't understand why `getWildcardDirectories` uses `regexp` instead of `regexp2`.

(I would rather we not use regexp/regexp2 at all in the codebase but that's another problem.)

Comment (camc314) [reply internal/vfs/utilities.go:85]: i would guess it's still a problem with regexp2.

I remove this regex in favor of a simple for loop though https://github.com/microsoft/typescript-go/pull/1947/commits/6bf55437f89bf2fe227a395f3ea9bb5dafc8e108

**Comment by jakebailey** [comment]
The latest commit is not exactly what I mean; I wasn't trying to say to continue to change the escaping, but rather fix `getWildcardDirectories` to not use Go's regexp package, given the original code was more or less trying to emulate ECMAScript regexes which can be done with `regexp2`.

I feel somewhat less confident about hand escaping regexes like this unless we can be sure that those characters are definitely all that matter?

Otherwise, we'd just use https://pkg.go.dev/regexp#QuoteMeta, right?

File: internal/vfs/utilities.go (hunk 1 above)
Comment (jakebailey) [reply internal/vfs/utilities.go:85]: It shouldn't be, given regexp2 has a mode that emulates ECMAScript regexes?

If we are going to use `regexp` and not `regexp2`, then we can probably just use `regexp.QuoteMeta`.

**Comment by camc314** [comment]
> The latest commit is not exactly what I mean; I wasn't trying to say to continue to change the escaping, but rather fix `getWildcardDirectories` to not use Go's regexp package, given the original code was more or less trying to emulate ECMAScript regexes which can be done with `regexp2`.
> 
> I feel somewhat less confident about hand escaping regexes like this unless we can be sure that those characters are definitely all that matter?
> 
> Otherwise, we'd just use https://pkg.go.dev/regexp#QuoteMeta, right?

Ah i see. i reverted that commit. The problem is that `GetRegularExpressionForWildcard` combines multiple strings, so it has to be escaped, hence we can't just omit the regex escaping change. Regardless, i changed `wildcarddirectories` to use `regexp2`.

Hopefully I understood that correctly 🙂

**Comment by jakebailey** [comment]
Why does Strada not need the escaping change, though?

File: internal/vfs/utilities.go [hunk 2]
```diff
@@ -81,11 +81,11 @@ func IsImplicitGlob(lastPathComponent string) bool {
...
+// so we only escape characters that have special meaning in regex.
 var (
-	reservedCharacterPattern *regexp.Regexp = regexp.MustCompile(`[^\w\s/]`)
+	reservedCharacterPattern *regexp.Regexp = regexp.MustCompile(`[\\.\+*?()\[\]{}^$|#]`)
```
Comment (jakebailey) [inline internal/vfs/utilities.go:88]: The goal of suggesting `regex2` was to avoid making this particular change. If we still want to restrict the characters, it makes me think we should just use QuoteMeta and not change anything else.

**Comment by jakebailey** [comment]
Honestly, this PR is probably fine. It would be good to make a test that would have crashed before. But, I would like to have this change upstreamed.

**Comment by camc314** [comment]
Sorry forgot to reply! This panic happens when getWildcardDirectories builds a Go regexp from a Windows file path that contains non-ASCII characters, because the escaping logic can produce sequences like `\æ` that Go’s regexp rejects. We hit this in tsgolint because we feed raw filesystem paths into wildcard direcotry handling to work out what project they're apart of. From my understanding `getWildcardDirectories` is only used by the language server. When editors pass filesystem paths to the language server, they're in percent-encoded form which means this issue is not encountered.

**Comment by jakebailey** [comment]
> When editors pass filesystem paths to the language server, they're in percent-encoded form which means this issue is not encountered.

Hm, but shouldn't we have decoded from URI format before handing this over? What code path actually lets such a path through?

**Comment by jakebailey** [comment]
I don't think the percent encoded thing is actually critical here, but you're definitely correct otherwise.
