### PR TITLE
Port IsSourceFileFromExternalLibrary, fix node18 emit

### LINKED ISSUE #1215: When referenced external dependency contains `.ts` alongside `.js` of the same name, builds are nested
Repro case here:

- https://github.com/dimitropoulos/tsgo-repros/pull/2

Where a fairly vanilla monorepo setup created a nested `dist`. Solve-able by just NOT having `.ts` files in `dist` (and this is good practice) but it is a weird regression case.

A (very rough) attempt at a fix is here:

- https://github.com/microsoft/typescript-go/pull/1214

### PR DESCRIPTION
**Pull request by maschwenk**
Fixes #1215

### CODE REVIEW

File: internal/project/project.go [hunk 1]
```diff
@@ -970,6 +970,7 @@ func (p *Project) GetFileNames(excludeFilesFromExternalLibraries bool, excludeCo
 	result := []string{}
 	sourceFiles := p.program.GetSourceFiles()
 	for _, sourceFile := range sourceFiles {
+		// !! This is probably ready to be implemented now?
```
Comment (maschwenk) [inline internal/project/project.go:986]: Because we have `IsSourceFileFromExternalLibrary`

File: internal/compiler/program.go [hunk 2]
```diff
@@ -820,6 +831,16 @@ func (p *Program) getModeForTypeReferenceDirectiveInFile(ref *ast.FileReference,
 	return p.GetDefaultResolutionModeForFile(sourceFile)
 }
 
+// IsSourceFileFromExternalLibrary returns true if the source file is from an external library.
+// This mirrors the TypeScript implementation which tracks files found while searching node_modules.
```
Comment (jakebailey) [inline internal/compiler/program.go]: I assume some LLM added the comments; I would just remove all of these as they just describe exactly what the code says.

File: internal/compiler/fileloader.go [hunk 3]
```diff
@@ -412,9 +428,10 @@ func (p *fileLoader) resolveImportsAndModuleAugmentations(file *ast.SourceFile,
 
 			if shouldAddFile {
 				toParse = append(toParse, resolvedRef{
-					fileName:      resolvedFileName,
-					increaseDepth: resolvedModule.IsExternalLibraryImport,
-					elideOnDepth:  isJsFileFromNodeModules,
+					fileName:              resolvedFileName,
+					increaseDepth:         resolvedModule.IsExternalLibraryImport,
+					elideOnDepth:          isJsFileFromNodeModules,
+					isFromExternalLibrary: isFromNodeModulesSearch,
```
Comment (jakebailey) [inline internal/compiler/fileloader.go]: Not just `resolvedModule.IsExternalLibraryImport`?

File: internal/compiler/fileloader.go [hunk 4]
```diff
@@ -301,7 +313,10 @@ func (p *fileLoader) resolveTripleslashPathReference(moduleName string, containi
 		referencedFileName = tspath.CombinePaths(basePath, moduleName)
 	}
 	return resolvedRef{
-		fileName: tspath.NormalizePath(referencedFileName),
+		fileName:              tspath.NormalizePath(referencedFileName),
+		increaseDepth:         false,
+		elideOnDepth:          false,
+		isFromExternalLibrary: false, // Triple-slash references are always local files
```
Comment (jakebailey) [inline internal/compiler/fileloader.go]: These are all defaulted to `false` if not present.

File: internal/compiler/program.go [hunk 5]
```diff
@@ -820,6 +831,16 @@ func (p *Program) getModeForTypeReferenceDirectiveInFile(ref *ast.FileReference,
...
+func (p *Program) IsSourceFileFromExternalLibrary(file *ast.SourceFile) bool {
+	if file == nil {
+		return false
+	}
+	isExternal, exists := p.sourceFilesFoundSearchingNodeModules.Load(file.Path())
+	return exists && isExternal
```
Comment (jakebailey) [inline internal/compiler/program.go]: I don't think this should have `Load`. It's just a `map`.

File: internal/compiler/fileloader.go [hunk 6]
```diff
@@ -50,6 +50,9 @@ type processedFiles struct {
 	importHelpersImportSpecifiers map[tspath.Path]*ast.Node
 	// List of present unsupported extensions
 	unsupportedExtensions []string
+	// Track which source files were found while searching node_modules
+	// Similar to TypeScript's sourceFilesFoundSearchingNodeModules map
+	sourceFilesFoundSearchingNodeModules map[tspath.Path]bool
```
Comment (jakebailey) [inline internal/compiler/fileloader.go]: Use `collections.Set[tspath.Path]` here.

File: internal/compiler/program.go [hunk 7]
```diff
@@ -203,6 +205,14 @@ func NewProgram(opts ProgramOptions) *Program {
 
 	p.processedFiles = processAllProgramFiles(p.opts, libs, p.singleThreaded())
 
+	// Populate sourceFilesFoundSearchingNodeModules from the processed files
+	// This mirrors the TypeScript implementation's tracking behavior
+	if p.processedFiles.sourceFilesFoundSearchingNodeModules != nil {
+		for path, isExternal := range p.processedFiles.sourceFilesFoundSearchingNodeModules {
+			p.sourceFilesFoundSearchingNodeModules.Store(path, isExternal)
+		}
+	}
```
Comment (jakebailey) [inline internal/compiler/program.go]: This should not be required, the info should already be on processedFiles and therefore be accessible.

File: testdata/baselines/reference/submodule/conformance/typingsLookup4.js.diff [hunk 8]
```diff
@@ -1,6 +1,19 @@
...
++"use strict";
++Object.defineProperty(exports, "__esModule", { value: true });
++exports.l = void 0;
++exports.l = 2;
++//// [index.js]
++"use strict";
++Object.defineProperty(exports, "__esModule", { value: true });
++exports.m = void 0;
++exports.m = 3;
  //// [a.js]
```
Comment (jakebailey) [inline testdata/baselines/reference/submodule/conformance/typingsLookup4.js.diff]: These files appearing indicates that there's still some sort of bug here.

**Comment by jakebailey** [comment]
I still have more stuff to push; there are other weird things here that need to be fixed before this is ready.

File: internal/compiler/parsetask.go [hunk 9]
```diff
@@ -98,14 +102,21 @@ func (t *parseTask) redirect(loader *fileLoader, fileName string) {
...
 
 func (t *parseTask) addSubTask(ref resolvedRef, isLib bool) {
 	normalizedFilePath := tspath.NormalizePath(ref.fileName)
-	subTask := &parseTask{normalizedFilePath: normalizedFilePath, isLib: isLib, increaseDepth: ref.increaseDepth, elideOnDepth: ref.elideOnDepth}
+	subTask := &parseTask{
+		normalizedFilePath:    normalizedFilePath,
+		isLib:                 isLib,
+		increaseDepth:         ref.increaseDepth,
+		elideOnDepth:          ref.elideOnDepth,
+		isFromExternalLibrary: ref.isFromExternalLibrary || t.isFromExternalLibrary, // Propagate external library status
```
Comment (sheetalkamat) [inline internal/compiler/parsetask.go]: Not enough and needs to be handled differently to make sure https://github.com/microsoft/TypeScript/blob/main/src/compiler/program.ts#L3620 part is working as well

Comment (jakebailey) [reply internal/compiler/parsetask.go]: The redoing is what the `start` block does with the depth, but we do need to reexamine things, yes.

Comment (sheetalkamat) [reply internal/compiler/parsetask.go]: But here we are propagating is from external import .. we would need to change those other tasks too ?

Comment (jakebailey) [reply internal/compiler/parsetask.go]: Yes, that's the super annoying thing I'm trying to fix now 😭

**Comment by jakebailey** [comment]
Okay, well that was annoying

File: testdata/baselines/reference/submodule/conformance/nodeModulesExportsSourceTs(module=node18).js.diff [hunk 10]
```diff
@@ -1,29 +1,37 @@
...
-     "exports": "./index.ts"
+@@= skipped -27, +27 lines =@@
  }
 
--//// [other.js]
+ //// [other.js]
 -export const x = null;
--//// [index.js]
--// esm format file
++"use strict";
```
Comment (jakebailey) [inline testdata/baselines/reference/submodule/conformance/nodeModulesExportsSourceTs(module=node18).js.diff]: This is broken because node18 is not implemented.

Comment (jakebailey) [reply testdata/baselines/reference/submodule/conformance/nodeModulesExportsSourceTs(module=node18).js.diff]: Hm, but #1070 should have done it. Need to recheck.

Comment (jakebailey) [reply testdata/baselines/reference/submodule/conformance/nodeModulesExportsSourceTs(module=node18).js.diff]: Ah, one liner.

**Review by weswigham — APPROVED** [review]
