### PR TITLE
Skip defaults when printing BindingName

### LINKED ISSUE #1012: panic: runtime error: slice bounds out of range
Starting from `7.0.0-dev.20250530.1` this issue start happening on my project.
I tracked down the offending [commit](https://github.com/microsoft/typescript-go/pull/791) (by locally building tsgo)

repro (thanks to @joshcartme ) https://github.com/joshcartme/tsgo-slice-bounds-repro. 

Update: It happens for me when a file using `React` types without importing React which was supported on 5.8 and previously on tsgo.
Example:
```
component: React.ComponentType<any>
```

Here is full output
```
> /Users/hrh/project/typescript-go/built/local/tsgo --noEmit --skipLibCheck --project tsconfig.json

panic: runtime error: slice bounds out of range [:59935] with length 1010

goroutine 1 [running]:
github.com/microsoft/typescript-go/internal/scanner.GetLineAndCharacterOfPosition({0x104f145a8, 0x140098a1348}, 0xea1f)
	/Users/hrh/project/typescript-go/internal/scanner/scanner.go:2322 +0x158
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).visitDeclarationSubtree(0x140ba05fb20, 0x14003dd1600)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:470 +0x808
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).visit(0x140002f1718?, 0x1048ea4cc?)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:143 +0x114
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitSlice(0x140bb73f500, {0x14003deb288, 0x2, 0x2})
	/Users/hrh/project/typescript-go/internal/ast/visitor.go:148 +0xa0
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitNodes(0x140bb73f500, 0x14004898128)
	/Users/hrh/project/typescript-go/internal/ast/visitor.go:99 +0x40
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).visitNodes(0x140002f1818?, 0x104b79aa8?)
	/Users/hrh/project/typescript-go/internal/ast/visitor.go:236 +0x44
github.com/microsoft/typescript-go/internal/ast.(*UnionTypeNode).VisitEachChild(0x14003dd1680, 0x140bb73f500)
	/Users/hrh/project/typescript-go/internal/ast/ast.go:6997 +0x30
github.com/microsoft/typescript-go/internal/ast.(*Node).VisitEachChild(...)
	/Users/hrh/project/typescript-go/internal/ast/ast.go:217
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitEachChild(...)
	/Users/hrh/project/typescript-go/internal/ast/visitor.go:191
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).visitDeclarationSubtree(0x140ba05fb20, 0x14003dd1680)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:493 +0xce8
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).visit(0x104b33700?, 0x140ba06db88?)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:143 +0x114
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).transformTypeAliasDeclaration(0x140ba05fb20, 0x14004049100)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:1122 +0x78
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).transformTopLevelDeclaration(0x140ba05fb20, 0x14004049100)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:1090 +0x468
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).visitDeclarationStatements(0x140ba05fb20, 0x14004049100)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:940 +0x4c
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).visit(0x140002f1bc8?, 0x104b80454?)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:118 +0xec
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitSlice(0x140bb73f500, {0x140023f5608, 0x106, 0x106})
	/Users/hrh/project/typescript-go/internal/ast/visitor.go:148 +0xa0
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitNodes(0x140bb73f500, 0x140041e7ce8)
	/Users/hrh/project/typescript-go/internal/ast/visitor.go:99 +0x40
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).transformModuleDeclaration(0x140ba05fb20, 0x14003a26090)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:1179 +0xb8
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).transformTopLevelDeclaration(0x140ba05fb20, 0x14003a26090)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:1096 +0x438
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).transformAndReplaceLatePaintedStatements(0x140ba05fb20, 0x140098b4500)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:235 +0xf4
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).transformSourceFile(0x140ba05fb20, 0x140098a1348)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:186 +0x40
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).visitSourceFile(0x140ba05fb20, 0x140098a1348)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:172 +0x174
github.com/microsoft/typescript-go/internal/transformers/declarations.(*DeclarationTransformer).visit(0x140ba05fb20?, 0x140845f24e0?)
	/Users/hrh/project/typescript-go/internal/transformers/declarations/transform.go:102 +0xc0
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitNode(0x1133319f8?, 0x140c9250c68?)
	/Users/hrh/project/typescript-go/internal/ast/visitor.go:51 +0x30
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitSourceFile(...)
	/Users/hrh/project/typescript-go/internal/ast/visitor.go:36
github.com/microsoft/typescript-go/internal/transformers.(*Transformer).TransformSourceFile(...)
	/Users/hrh/project/typescript-go/internal/transformers/transformer.go:42
github.com/microsoft/typescript-go/internal/compiler.getDeclarationDiagnostics({0x104f24c90, 0x140c9250c68}, {0x104f264f8, 0x140377529a0}, 0x140098a1348)
	/Users/hrh/project/typescript-go/internal/compiler/emitter.go:477 +0x134
github.com/microsoft/typescript-go/internal/compiler.(*Program).getDeclarationDiagnosticsForFile(0x1400049c540, {0x140000921a0?, 0x1403327d008?}, 0x140098a1348)
	/Users/hrh/project/typescript-go/internal/compiler/program.go:576 +0x84
github.com/microsoft/typescript-go/internal/compiler.(*Program).getDiagnosticsHelper(0x1400049c540, {0x104f15568, 0x1053ea660}, 0x0?, 0x0?, 0x1?, 0x140002f2390)
	/Users/hrh/project/typescript-go/internal/compiler/program.go:678 +0x1a0
github.com/microsoft/typescript-go/internal/compiler.(*Program).GetDeclarationDiagnostics(...)
	/Users/hrh/project/typescript-go/internal/compiler/program.go:467
github.com/microsoft/typescript-go/internal/execute.emitFilesAndReportErrors({0x104f19750, 0x140000c4a50}, 0x1400049c540, 0x14000092d00)
	/Users/hrh/project/typescript-go/internal/execute/tsc.go:277 +0x4b4
github.com/microsoft/typescript-go/internal/execute.performCompilation({0x104f19750, 0x140000c4a50}, 0x0, 0x14000192000, 0x14000092d00)
	/Users/hrh/project/typescript-go/internal/execute/tsc.go:207 +0x1a4
github.com/microsoft/typescript-go/internal/execute.executeCommandLineWorker({0x104f19750, 0x140000c4a50}, 0x0, 0x14000192090)
	/Users/hrh/project/typescript-go/internal/execute/tsc.go:135 +0x65c
github.com/microsoft/typescript-go/internal/execute.CommandLine({0x104f19750, 0x140000c4a50}, 0x0, {0x140000c4010, 0x4, 0x4})
	/Users/hrh/project/typescript-go/internal/execute/tsc.go:35 +0x1f4
main.runMain()
	/Users/hrh/project/typescript-go/cmd/tsgo/main.go:23 +0x120
main.main()
	/Users/hrh/project/typescript-go/cmd/tsgo/main.go:10 +0x1c
Completed with failure in 3985ms
```

### PR DESCRIPTION
**Pull request by muglug**
This should fix #1012 

This fills in a TODO to match code in checker.ts, and fixes a bunch of test discrepancies.

PR also adds more bounds checks to comment parsing to to match [the JS implementation](https://github.com/microsoft/TypeScript/blob/b504a1eed45e35b5f54694a1e0a09f35d0a5663c/src/compiler/scanner.ts#L640-L733).

`text.charCodeAt(pos)` returns `NaN` when the `pos` is out of range, which means the big `switch` falls through and returns, whereas calling `text[pos:]` panics in existing code when `pos` is out of range.

### CODE REVIEW

**Comment by jakebailey** [comment]
Can you add a repro to https://github.com/microsoft/typescript-go/tree/main/testdata/tests/cases/compiler?

**Comment by muglug** [comment]
Yes, though now I'm determined to track down the original bug (actually in the error printing step)

**Comment by muglug** [comment]
@microsoft-github-policy-service agree

File: internal/printer/printer.go [hunk 1]
```diff
@@ -2328,7 +2328,15 @@ func (p *Printer) emitBindingElement(node *ast.BindingElement) {
 	// Old parser used `OmittedExpression` as a substitute for `Elision`. New parser uses a `BindingElement` with nil members
 	if name := node.Name(); name != nil {
 		p.emitBindingName(name)
-		p.emitInitializer(node.Initializer, node.Name().End(), node.AsNode())
+		// Check if name is from the current source file to avoid cross-file position issues
+		var equalTokenPos int
+		if p.currentSourceFile != nil && ast.GetSourceFileOfNode(name) == p.currentSourceFile {
```
Comment (jakebailey) [inline internal/printer/printer.go]: This isn't correct, unfortunately. Source files can be transformed and therefore not have any parents set.

Comment (muglug) [reply internal/printer/printer.go]: Yeah that was a bad fix — how does tsgo handle printing of nodes when `p.currentSourceFile` is different?

Comment (jakebailey) [reply internal/printer/printer.go]: IIRC original node information is stored in the emit context, but I would go check to see what this code does in the original TS code to see if there's just a porting bug instead.

**Comment by jakebailey** [comment]
FWIW you probably want to retitle the PR 😄

**Comment by jakebailey** [comment]
> Also fixes a data race in LinkStore.

Where is that in the PR?

**Comment by muglug** [comment]
I removed it — I was able to repro the race locally, but then I added a missing switch that I had omitted and the race disappeared.

The race prevention code is pretty simple but also not necessary, at least for this PR (I believe).

File: internal/checker/nodebuilderimpl.go [hunk 2]
```diff
@@ -1486,8 +1486,56 @@ func (b *nodeBuilderImpl) parameterToParameterDeclarationName(parameterSymbol *a
...
+	case ast.IsIdentifier(name):
+		cloned := b.f.DeepCloneNode(name)
+		b.e.SetEmitFlags(cloned, printer.EFNoAsciiEscaping)
+		return cloned
+	case ast.IsQualifiedName(name):
+		cloned := b.f.DeepCloneNode(name.AsQualifiedName().Right)
+		b.e.SetEmitFlags(cloned, printer.EFNoAsciiEscaping)
+		return cloned
+	default:
+		return b.cloneBindingName(name)
```
Comment (jakebailey) [inline internal/checker/nodebuilderimpl.go]:
```suggestion
	switch name.Kind {
	case ast.KindIdentifier:
		cloned := b.f.DeepCloneNode(name)
		b.e.SetEmitFlags(cloned, printer.EFNoAsciiEscaping)
		return cloned
	case ast.KindQualifiedName:
		cloned := b.f.DeepCloneNode(name.AsQualifiedName().Right)
		b.e.SetEmitFlags(cloned, printer.EFNoAsciiEscaping)
		return cloned
	default:
		return b.cloneBindingName(name)
```

File: internal/checker/nodebuilderimpl.go [hunk 3]
```diff
@@ -1486,8 +1486,56 @@ func (b *nodeBuilderImpl) parameterToParameterDeclarationName(parameterSymbol *a
...
+	}
+}
+
+func (b *nodeBuilderImpl) cloneBindingName(node *ast.Node) *ast.Node {
+	if b.ctx.tracker != nil && ast.IsComputedPropertyName(node) && b.ch.isLateBindableName(node) {
```
Comment (jakebailey) [inline internal/checker/nodebuilderimpl.go]: Can `tracker` be `nil`? I don't see this condition checked anywhere else.

File: internal/checker/nodebuilderimpl.go [hunk 4]
```diff
@@ -1486,8 +1486,56 @@ func (b *nodeBuilderImpl) parameterToParameterDeclarationName(parameterSymbol *a
...
+
+	if !ast.NodeIsSynthesized(visited) {
+		visited = b.f.DeepCloneNode(visited)
+	}
+
+	b.e.SetEmitFlags(visited, printer.EFSingleLine|printer.EFNoAsciiEscaping)
+	return visited
+}
+
+func (b *nodeBuilderImpl) visitEachChildWorker(node *ast.Node, cbNode func(*ast.Node) *ast.Node) *ast.Node {
```
Comment (jakebailey) [inline internal/checker/nodebuilderimpl.go]: I'm not sure this is needed; `visitEachChildWorker` in the original code is actually `visitEachChild as visitEachChildWorker`, which is just the `VisitEachChild` method, right?

Comment (muglug) [reply internal/checker/nodebuilderimpl.go]: yeah — I've inlined this function

File: internal/checker/nodebuilderimpl.go [hunk 5]
```diff
@@ -1486,8 +1486,47 @@ func (b *nodeBuilderImpl) parameterToParameterDeclarationName(parameterSymbol *a
...
+		return b.cloneBindingName(name)
+	}
+}
+
+func (b *nodeBuilderImpl) cloneBindingName(node *ast.Node) *ast.Node {
+	if ast.IsComputedPropertyName(node) && b.ch.isLateBindableName(node) {
+		b.trackComputedName(node.Expression(), b.ctx.enclosingDeclaration)
+	}
+
+	visitor := ast.NewNodeVisitor(b.cloneBindingName, b.f, ast.NodeVisitorHooks{})
```
Comment (jakebailey) [inline internal/checker/nodebuilderimpl.go]: This visitor is an expensive resource; we should set it up in `newNodeBuilderImpl` as a field, e.g `cloneBindingNameVisitor`.

Comment (jakebailey) [reply internal/checker/nodebuilderimpl.go]: I would wait for #1001 to be merged beforehand, though, since that will conflict.

Basically, you'd just need to add the field to the struct, then do:

```
result.cloneBindingNameVisitor = ast.NewNodeVisitor(result.cloneBindingName, result.f, ast.NodeVisitorHooks{})
```

In the `new` func, then call that visitor here.

**Review by jakebailey — APPROVED** [review]
Great work, much appreciated!

**Comment by jakebailey** [comment]
Ugh, I guess the nil check is a thing? Hmmm

**Comment by jakebailey** [comment]
The context being nil I think is a bug in the PR, not something that needs a check. What I'm seeing in the debugger is that in the initial frame. `ctx` is set, but when we recurse, the next time it gets to the cloning function, it's nil.

**Comment by jakebailey** [comment]
Ugh, #1001 broke it, it's the thing intializeClosures was doing to "recapture the context", even though I haven't been able to figure out why that matters.

**Comment by jakebailey** [comment]
The problem was that `nodeBuilderImpl` was returned by value, so the bound funcs actually never worked in that func.

**Review by jakebailey — APPROVED** [review]
Approving but since I pushed last it I'll have to get someone else to +1 it

**Review by sheetalkamat — APPROVED** [review]

**Comment by muglug** [comment]
Thanks for your pointers!

**Comment by jakebailey** [comment]
Pun intended!

**Comment by scottbessler** [comment]
With this fix in place I'm still seeing a similar panic:
```
panic: runtime error: slice bounds out of range [20017:2169]

goroutine 3919 [running]:
github.com/microsoft/typescript-go/internal/scanner.SkipTriviaEx({0x14000150900, 0x879}, 0x1401f3d7a70?, 0xbc?)
        /usr/local/repos/typescript-go/internal/scanner/scanner.go:2100 +0x490
github.com/microsoft/typescript-go/internal/scanner.SkipTrivia(...)
        /usr/local/repos/typescript-go/internal/scanner/scanner.go:2085
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitSourceMapsBeforeNode(0x1402005fe00, 0x1401f3d7a70)
        /usr/local/repos/typescript-go/internal/printer/printer.go:5470 +0x118
github.com/microsoft/typescript-go/internal/printer.(*Printer).enterNode(0x1402005fe00, 0x1401f3d7a70)
        /usr/local/repos/typescript-go/internal/printer/printer.go:5694 +0x50
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitBindingIdentifier(0x1402005fe00, 0x1401f3d7a70)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1140 +0xd4
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitBindingName(0x1402005fe00?, 0x140214de230?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1191 +0x48
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitParameterName(...)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1413
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitParameter(0x1402005fe00, 0x140214de230)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1421 +0x84
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitParameterNode(0x1402005fe00?, 0x1401fca71f8?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1433 +0x34
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitListItems(0x1402005fe00, 0x1035271f0, 0x140214a87e0, {0x1400741fd38, 0x1, 0x12af4c098?}, 0xa10, 0x0, {0xffffffff, 0xffffffff})
        /usr/local/repos/typescript-go/internal/printer/printer.go:4676 +0x3b8
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitListRange(0x1402005fe00, 0x1035271f0, 0x140214a87e0, 0x14010b920c0, 0xa10, 0x14010b7b340?, 0x1401fca7308?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:4473 +0x324
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitList(0x1402005fe00, 0x1035271f0, 0x140214a87e0, 0x14010b920c0, 0xa10)
        /usr/local/repos/typescript-go/internal/printer/printer.go:4418 +0x8c
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitParameters(0x1402005fe00?, 0x140214a87e0?, 0x14010b920c0?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1485 +0x5c
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitFunctionType(0x1402005fe00, 0x140214a87e0)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1867 +0x17c
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitTypeNode(0x1402005fe00, 0x140214a87e0, 0x1?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:2230 +0x210
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitTypeNodePreservingExtends(...)
        /usr/local/repos/typescript-go/internal/printer/printer.go:2192
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitReturnType(0x1402005fe00, 0x140214a87e0)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1856 +0xe0
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitFunctionType(0x1402005fe00, 0x140214a8850)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1869 +0x1b0
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitTypeNode(0x1402005fe00, 0x140214a8850, 0x1fca7548?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:2230 +0x210
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitTypeNodePreservingExtends(...)
        /usr/local/repos/typescript-go/internal/printer/printer.go:2192
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitTypeNodeOutsideExtends(...)
        /usr/local/repos/typescript-go/internal/printer/printer.go:2186
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitTypeAnnotation(0x1402005fe00, 0x140214a8850)
        /usr/local/repos/typescript-go/internal/printer/printer.go:1469 +0x8c
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitVariableDeclaration(0x1402005fe00, 0x140214a51e0)
        /usr/local/repos/typescript-go/internal/printer/printer.go:3437 +0x64
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitVariableDeclarationNode(0x1402005fe00?, 0x1401fca75f8?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:3444 +0x34
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitListItems(0x1402005fe00, 0x103527238, 0x14010b92100, {0x1400741fe60, 0x1, 0x80?}, 0x210, 0x0, {0x68, 0xbc})
        /usr/local/repos/typescript-go/internal/printer/printer.go:4676 +0x3b8
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitListRange(0x1402005fe00, 0x103527238, 0x14010b92100, 0x14012fcdb20, 0x210, 0x10330b0a8?, 0x1?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:4473 +0x324
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitList(0x1402005fe00, 0x103527238, 0x14010b92100, 0x14012fcdb20, 0x210)
        /usr/local/repos/typescript-go/internal/printer/printer.go:4418 +0x8c
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitVariableDeclarationList(0x1402005fe00, 0x14010b92100)
        /usr/local/repos/typescript-go/internal/printer/printer.go:3464 +0x1fc
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitVariableStatement(0x1402005fe00, 0x14020b5d5e0)
        /usr/local/repos/typescript-go/internal/printer/printer.go:3152 +0x6c
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitStatement(0x1401f081180?, 0x1401fca7848?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:3903 +0x98
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitListItems(0x1402005fe00, 0x1035271f8, 0x14020fa7348, {0x14020fcaba0, 0xa, 0x102f9c998?}, 0x1, 0x0, {0x0, 0x878})
        /usr/local/repos/typescript-go/internal/printer/printer.go:4676 +0x3b8
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitListRange(0x1402005fe00, 0x1035271f8, 0x14020fa7348, 0x1401c30f1c0, 0x1, 0x14000b3f8c8?, 0x1401fca7938?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:4473 +0x324
github.com/microsoft/typescript-go/internal/printer.(*Printer).emitSourceFile(0x1402005fe00, 0x14020fa7348)
        /usr/local/repos/typescript-go/internal/printer/printer.go:4395 +0x1d8
github.com/microsoft/typescript-go/internal/printer.(*Printer).Write(0x1402005fe00, 0x14020fa7348, 0x14009364900?, {0x10353f890, 0x1401f081180}, 0x1?)
        /usr/local/repos/typescript-go/internal/printer/printer.go:4925 +0xcf4
github.com/microsoft/typescript-go/internal/compiler.(*emitter).printSourceFile(0x1401ee7f9e0, {0x14009364900, 0x56}, {0x14009364960, 0x5a}, 0x14020fa7348, 0x1402005fe00, 0x1)
        /usr/local/repos/typescript-go/internal/compiler/emitter.go:158 +0x1e8
github.com/microsoft/typescript-go/internal/compiler.(*emitter).emitDeclarationFile(0x1401ee7f9e0, 0x14000b3f8c8, {0x14009364900, 0x56}, {0x14009364960, 0x5a})
        /usr/local/repos/typescript-go/internal/compiler/emitter.go:127 +0x498
github.com/microsoft/typescript-go/internal/compiler.(*emitter).emit(0x1401ee7f9e0)
        /usr/local/repos/typescript-go/internal/compiler/emitter.go:43 +0x58
github.com/microsoft/typescript-go/internal/compiler.(*Program).Emit.func2()
        /usr/local/repos/typescript-go/internal/compiler/program.go:839 +0x140
github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue.func1()
        /usr/local/repos/typescript-go/internal/core/workgroup.go:39 +0x5c
created by github.com/microsoft/typescript-go/internal/core.(*parallelWorkGroup).Queue in goroutine 1
        /usr/local/repos/typescript-go/internal/core/workgroup.go:37 +0x84
```

I will try and track down a repro, but thought it would be useful to report straight away. `git bisect` points at the same commit being the source of the issue: 6fc5cb8.

**Comment by muglug** [comment]
yeah a repro is necessary to fix — happy to look when you have one

**Comment by muglug** [comment]
Another quick note that my PR deliberately did not add an out-of-range check at the top of `SkipTriviaEx` that exists (implicitly) in the original JS, because a panic there is a sign that logic elsewhere in the system is incorrect.
