### PR TITLE
Fix checks for disallowed property/accessor duplicate declarations

### LINKED ISSUE #3613: Behaviour difference: merging `interface`s with identically named getter/setter pair and field
Found from typechecking a project using `@mikro-orm+core@6.6.13`. Behaviour difference also occurs when using `declare class`.

## Steps to reproduce

issue.ts:

```typescript
interface EntityMetadata {
    get tableName(): string;
    set tableName(name: string);
}

interface EntityMetadata {
    tableName: string;
}
```

## Behavior with `typescript@6.0`

No error.

```
$ pnpm dlx --package=typescript@6 tsc --ignoreConfig issue.ts
```

## Behavior with `tsgo`

TS2300 (duplicate identifier) errors:

```
$ pnpm dlx --package=@typescript/native-preview@beta tsgo --ignoreConfig issue.ts
issue.ts:2:9 - error TS2300: Duplicate identifier 'tableName'.

2     get tableName(): string;
          ~~~~~~~~~

issue.ts:3:9 - error TS2300: Duplicate identifier 'tableName'.

3     set tableName(name: string);
          ~~~~~~~~~

issue.ts:7:5 - error TS2300: Duplicate identifier 'tableName'.

7     tableName: string;
      ~~~~~~~~~


Found 3 errors in the same file, starting at: issue.ts:2
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR the binder consistently permits accessor and property declarations to merge, and disallowed patterns are detected and reported by the checker. Specifically, we disallow duplicate property declarations in the same type declaration, and we disallow combinations of accessor and property declarations for the same name in the same type declaration.

Fixes #3613.

### CODE REVIEW

File: internal/binder/binder.go [hunk 1]
```diff
@@ -665,7 +665,7 @@ func (b *Binder) bind(node *ast.Node) bool {
 	case ast.KindCallSignature, ast.KindConstructSignature, ast.KindIndexSignature:
 		b.declareSymbolAndAddToSymbolTable(node, ast.SymbolFlagsSignature, ast.SymbolFlagsNone)
 	case ast.KindMethodDeclaration, ast.KindMethodSignature:
-		b.bindPropertyOrMethodOrAccessor(node, ast.SymbolFlagsMethod|getOptionalSymbolFlagForNode(node), core.IfElse(ast.IsObjectLiteralMethod(node), ast.SymbolFlagsPropertyExcludes, ast.SymbolFlagsMethodExcludes))
+		b.bindPropertyOrMethodOrAccessor(node, ast.SymbolFlagsMethod|getOptionalSymbolFlagForNode(node), core.IfElse(ast.IsObjectLiteralMethod(node), ast.SymbolFlagsValue, ast.SymbolFlagsMethodExcludes))
```
[the remark this answers is not in the document]
Comment (ahejlsberg) [reply internal/binder/binder.go:668]: The tests already show the effects of this change (i.e. method names must be unique in object literals).

File: testdata/baselines/reference/submoduleAccepted/conformance/objectLiteralErrors(target=es2015).errors.txt.diff [hunk 2]
```diff
@@ -0,0 +1,204 @@
+--- old.objectLiteralErrors(target=es2015).errors.txt
++++ new.objectLiteralErrors(target=es2015).errors.txt
+@@= skipped -15, +15 lines =@@
+ objectLiteralErrors.ts(17,23): error TS1117: An object literal cannot have multiple properties with the same name.
+ objectLiteralErrors.ts(18,22): error TS1117: An object literal cannot have multiple properties with the same name.
+ objectLiteralErrors.ts(19,25): error TS1117: An object literal cannot have multiple properties with the same name.
+-objectLiteralErrors.ts(22,12): error TS2300: Duplicate identifier 'a'.
```
Comment (jakebailey) [inline testdata/baselines/reference/submoduleAccepted/conformance/objectLiteralErrors(target=es2015).errors.txt.diff:7]: For completeness, do we also have a test which checks this in JS files, which may not be checked?

**Comment by jakebailey** [comment]
Probably the new diffs can be marked as accepted, since they are intentional?

File: testdata/baselines/reference/submoduleAccepted/conformance/objectLiteralErrors(target=es2015).errors.txt.diff (hunk 2 above)
Comment (ahejlsberg) [reply testdata/baselines/reference/submoduleAccepted/conformance/objectLiteralErrors(target=es2015).errors.txt.diff:7]: Not quite sure what you mean. Nothing special about JS here.

Comment (jakebailey) [reply testdata/baselines/reference/submoduleAccepted/conformance/objectLiteralErrors(target=es2015).errors.txt.diff:7]: I mean specifically that if more stuff goes into the checker, how is `checkJs=false` affected, if before it was a binder error.

**Review by jakebailey — APPROVED** [review]
Within what's in the PR I think this looks fine, but I think it'd be worth checking that this all works in allowJs without checkJs
