### PR TITLE
Check that all paths in module are valid for inclusion in module, fix one baseline

### LINKED ISSUE #482: Module cannot be pulled with go get
I get the following error with `go get github.com/microsoft/typescript-go/internal/parser@main`:
```
5a6d4ee7c645
go: github.com/microsoft/typescript-go/internal/parser@main: create zip: testdata/baselines/reference/tsc/commandLine/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js: malformed file path "testdata/baselines/reference/tsc/commandLine/show-help-with-ExitStatus.DiagnosticsPresent_OutputsSkipped-when-host-can't-provide-terminal-width.js": invalid char '\'
```

If I configure go.mod to use replace with a local checkout of typescript-go, I can't import the parser because it's in the internal directory.
```
      main.go:7:8: use of internal package github.com/microsoft/typescript-go/internal/parser not allowed

### PR DESCRIPTION
**Pull request by jakebailey**
All files within the module need to satisfy `CheckFilePath`: https://pkg.go.dev/golang.org/x/mod/module#CheckFilePath

This means no `'` characters, which this one test had.

Fixes #482

### CODE REVIEW

File: internal/execute/tsc_test.go [hunk 1]
```diff
@@ -24,7 +24,7 @@ func TestTsc(t *testing.T) {
 			commandLineArgs: nil,
 		},
 		{
-			subScenario:     "show help with ExitStatus.DiagnosticsPresent_OutputsSkipped when host can't provide terminal width",
+			subScenario:     "show help with ExitStatus.DiagnosticsPresent_OutputsSkipped when host cant provide terminal width",
```
Comment (RyanCavanaugh) [inline internal/execute/tsc_test.go]:
```suggestion
			subScenario:     "show help with ExitStatus.DiagnosticsPresent_OutputsSkipped when host cannot provide terminal width",
```

Comment (jakebailey) [reply internal/execute/tsc_test.go]: Way better, haha

**Review by RyanCavanaugh — APPROVED** [review]
