### PR TITLE
Consistently map reparsed JSDoc nodes in `GetReparsedNodeForNode`

### LINKED ISSUE #2490: Completions panic (nil pointer) in JSDoc union return type of method with params
```js
/**
 * @type {{
 *   (input: string): X|Y/*$*/
 * }}
 */
let x;
```

Request completions at `$`.

```
error] panic handling request textDocument/completion: runtime error: invalid memory address or nil pointer dereference
goroutine 1757 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x64
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x40001a0008, 0x401010ae70)
	github.com/microsoft/typescript-go/internal/lsp/server.go:743 +0x40
panic({0x7ff62b1b4980?, 0x7ff62bcd3ff0?})
	runtime/panic.go:783 +0x120
github.com/microsoft/typescript-go/internal/checker.(*Checker).getSignatureFromDeclaration(0x400fa7a008, 0x400400afc0)
	github.com/microsoft/typescript-go/internal/checker/checker.go:19268 +0x298
github.com/microsoft/typescript-go/internal/checker.(*Checker).TryGetThisTypeAtEx(0x400fa7a008, 0x4004ba3a00, 0x0, 0x7ff62afebd60?)
	github.com/microsoft/typescript-go/internal/checker/checker.go:11782 +0x130
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData.func17()
	github.com/microsoft/typescript-go/internal/ls/completions.go:1497 +0x4e0
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData.func18(...)
	github.com/microsoft/typescript-go/internal/ls/completions.go:1541
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData(0x400fa76000, {0x7ff62b673ec8, 0x400f35c090}, 0x400fa7a008, 0x4007c79508, 0x2b, 0x4000312f00)
	github.com/microsoft/typescript-go/internal/ls/completions.go:1574 +0x16e0
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionsAtPosition(0x400fa76000, {0x7ff62b673ec8, 0x400f35c090}, 0x4007c79508, 0x2b, 0x0)
	github.com/microsoft/typescript-go/internal/ls/completions.go:345 +0x284
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideCompletion(0x400fa76000, {0x7ff62b673ec8, 0x400f35c090}, {0x4005ee8018?, 0x400f35c090?}, {0x5ee8018?, 0x40?}, 0x40100b2000)
	github.com/microsoft/typescript-go/internal/ls/completions.go:45 +0xa0
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleCompletion(0x500f0f920?, {0x7ff62b673ec8?, 0x400f35c090?}, 0x4005ee8018?, 0x40084a1de8?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:1053 +0x3c
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceWithAutoImportsRequestHandler[...].28({0x7ff62b673ec8, 0x400f35c090}, 0x401010ae70)
	github.com/microsoft/typescript-go/internal/lsp/server.go:646 +0xf0
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x40001a0008, {0x7ff62b673f00?, 0x400def4000?}, 0x401010ae70)
	github.com/microsoft/typescript-go/internal/lsp/server.go:502 +0x148
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:404 +0x34
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 10
	github.com/microsoft/typescript-go/internal/lsp/server.go:424 +0x7a0
```

### PR DESCRIPTION
**Pull request by ahejlsberg**
With this PR we track reparsed clones of JSDoc nodes such that `ast.GetReparsedNodeForNode` can consistently map from JSDoc nodes to their reparsed clones (which are the ones that are assigned symbols by the binder). The PR changes the `checker.GetSymbolAtLocation` and `checker.TryGetThisTypeAtEx` functions to use `ast.GetReparsedNodeFromNode`.

Fixes #2490.

### CODE REVIEW

File: internal/ast/utilities.go [hunk 1]
```diff
@@ -4264,3 +4264,41 @@ func isArgumentOfElementAccessExpression(node *Node) bool {
 		node.Parent.Kind == KindElementAccessExpression &&
 		node.Parent.AsElementAccessExpression().ArgumentExpression == node
 }
+
+// If the given node is part of a subtree of JSDoc nodes that have been cloned into a reparsed construct,
+// return the corresponding reparsed clone in the subtree. Otherwise, just return the node.
+func GetReparsedNodeForNode(node *Node) *Node {
+	if node != nil && node.Flags&NodeFlagsJSDoc != 0 && node.Flags&NodeFlagsReparsed == 0 {
+		if file := GetSourceFileOfNode(node); file != nil && len(file.ReparsedClones) != 0 {
+			pos, found := slices.BinarySearchFunc(file.ReparsedClones, node, CompareNodePositions)
```
Comment (DanielRosenwasser) [inline internal/ast/utilities.go:4273]: Isn't it possible that you end up with multiple nodes with the same `pos` but different `end`s? With functions like `IndexOfNode`, it assumes a list of nodes that don't overlap, so binary search on `pos` is fine. But let's say you have something like this:


```
/**
 * @type {Foo<Bar>>}
 */
let someVar;
```

Both the identifier `Foo` and the type reference `Foo<Bar>>` have the same `pos`.

Comment (DanielRosenwasser) [reply internal/ast/utilities.go:4273]: I guess you are only storing the root node that gets cloned in here - so maybe you aren't hitting those issues.

Comment (ahejlsberg) [reply internal/ast/utilities.go:4273]: The reparsing logic ensures that the reparsed clones list only contains mutually exclusive nodes, so this isn't an issue.

File: internal/ast/ast.go [hunk 2]
```diff
@@ -11006,24 +11012,23 @@ func (node *SourceFile) GetOrCreateToken(
 	node.tokenCacheMu.Lock()
 	defer node.tokenCacheMu.Unlock()
 	loc := core.NewTextRange(pos, end)
-	if node.tokenCache == nil {
-		node.tokenCache = make(map[core.TextRange]*Node)
-	} else if token, ok := node.tokenCache[loc]; ok {
+	key := TokenCacheKey{Loc: loc, Parent: parent}
+	if token, ok := node.tokenCache[key]; ok {
```
Comment (DanielRosenwasser) [inline internal/ast/ast.go]: Do we know precisely what was happening that requires caching on the parent?

File: testdata/baselines/reference/fourslash/findAllReferences/findAllReferencesJsOverloadedFunctionParameter.baseline.jsonc [hunk 3]
```diff
@@ -1,12 +1,7 @@
 // === findAllReferences ===
 // === /foo.js ===
-// /**
-//  * @overload
-//  * @param {number} [|x|]
```
Comment (DanielRosenwasser) [inline testdata/baselines/reference/fourslash/findAllReferences/findAllReferencesJsOverloadedFunctionParameter.baseline.jsonc:5]: Not sure if this is a regression - what changed here?

File: internal/ast/ast.go (hunk 2 above)
Comment (ahejlsberg) [reply internal/ast/ast.go]: Yes, I'm realizing that the completions logic is asking for tokens in both JSDoc comments and their reparsed clones. Such nodes have the same location but different parents. I'm changing the logic to only ask for tokens in the original JSDoc nodes. That will then allow me to get rid of the parent in the cache key.

**Comment by DanielRosenwasser** [comment]
@copilot try again

File: testdata/baselines/reference/fourslash/findAllReferences/findAllReferencesJsOverloadedFunctionParameter.baseline.jsonc (hunk 3 above)
Comment (ahejlsberg) [reply testdata/baselines/reference/fourslash/findAllReferences/findAllReferencesJsOverloadedFunctionParameter.baseline.jsonc:5]: Each `@overload` is reparsed into a function signature and the `@param` declaration names are now being remapped to their reparsed clones. Therefore, `GetSymbolAtLocation` doesn't see them as references to the parameter in the function implementation. The new behavior is consistent with Strada (a baseline `.diff` file was in fact eliminated).

**Comment by ahejlsberg** [comment]
> Would you say that generally all exposed checker methods should guard on nodes and try to get the reparsed node?

Yes, if it possibly matters. The set of nodes that are possibly reparsed is fairly small (basically only declaration names and type nodes). For example, no need to remap expression nodes.
