### PR TITLE
Re-port isUsedInFunctionOrInstanceProperty

### LINKED ISSUE #1870: TS2448 Block-scoped variable used before its declaration
## Steps to reproduce

```
export function foo() {
  const _fn = () => {
    ;(() => numFilesSelected)()
  }

  const numFilesSelected = 1
}
```

## Behavior with `typescript@5.9`

No error.

## Behavior with `tsgo`

```
test.tsx:3:13 - error TS2448: Block-scoped variable 'numFilesSelected' used before its declaration.

3     ;(() => numFilesSelected)()
              ~~~~~~~~~~~~~~~~

  test.tsx:6:9 - 'numFilesSelected' is declared here.
    6   const numFilesSelected = 1
              ~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #1870

### CODE REVIEW

File: internal/checker/checker.go [hunk 1]
```diff
@@ -1905,46 +1905,64 @@ func (c *Checker) isBlockScopedNameDeclaredBeforeUse(declaration *ast.Node, usag
...
-					if ast.IsIdentifier(propName) || ast.IsPrivateIdentifier(propName) {
-						t := c.getTypeOfSymbol(c.getSymbolOfDeclaration(declaration))
-						staticBlocks := core.Filter(declaration.Parent.Members(), ast.IsClassStaticBlockDeclaration)
-						if c.isPropertyInitializedInStaticBlocks(propName, t, staticBlocks, declaration.Parent.Pos(), current.Pos()) {
-							return true
+
+		if current.Parent != nil && ast.IsPropertyDeclaration(current.Parent) {
+			propertyDeclaration := current.Parent
+			initializerOfProperty := propertyDeclaration.Initializer() == current
+			if initializerOfProperty {
```
Comment (DanielRosenwasser) [inline internal/checker/checker.go:1922]: Nit on naming and comparison order to make it more readable

```suggestion
			currentIsInitializer := current == propertyDeclaration.Initializer()
			if currentIsInitializer {
```

or if you flip the order, I'd argue you don't need a variable anyway

```suggestion
			if current == propertyDeclaration.Initializer() {
```

Comment (jakebailey) [reply internal/checker/checker.go:1922]: This is 1:1 ported so I don't really want to futz with it.
