### PR TITLE
fix autoimports crash in js files 

### LINKED ISSUE #2598: Auto-imports broken in JS files when user preferences are used
I built tsgo with

```
hereby build --race
```

I ran the crawler with the race detector on VS Code and I got the following crash.

```
panic handling request completionItem/resolve: completion list needs auto imports
goroutine 2396 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:26 +0x68
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0xc000269c08, {0xc0168f35d7?, 0xc0168f3628?}, 0xc013149e30)
        /workspaces/typescript-go/internal/lsp/server.go:776 +0x5d
panic({0x11f2040?, 0x1e995f0?})
        /usr/local/go/src/runtime/panic.go:783 +0x132
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getSymbolCompletionFromItemData(0xc01bc73700, {0x176a338, 0xc013556090}, 0xc01bff4008, 0xc0003ca008, 0x0, 0xc01317b840)
        /workspaces/typescript-go/internal/ls/completions.go:4932 +0xf06
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionItemDetails(0xc01bc73700, {0x176a338, 0xc013556090}, 0xc01ad58008, 0xc01bff4008, 0x0, 0xc0003ca008, 0xc013432140, 0xc01317b840)
        /workspaces/typescript-go/internal/ls/completions.go:4845 +0x13b
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ResolveCompletionItem(0xc01bc73700, {0x176a338, 0xc013556090}, 0xc013432140, 0xc01317b840)
        /workspaces/typescript-go/internal/ls/completions.go:4806 +0x15f
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleCompletionItemResolve(0xc000269c08, {0x176a338, 0xc013556090}, 0xc013432140, 0xc013149e30)
        /workspaces/typescript-go/internal/lsp/server.go:1106 +0x205
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerRequestHandler[...].37({0x176a338, 0xc013556090}, 0xc013149e30)
        /workspaces/typescript-go/internal/lsp/server.go:635 +0x3ff
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0xc000269c08, {0x176a370, 0xc00b5de230}, 0xc013149e30)
        /workspaces/typescript-go/internal/lsp/server.go:530 +0x2e2
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
        /workspaces/typescript-go/internal/lsp/server.go:413 +0x65
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 20
        /workspaces/typescript-go/internal/lsp/server.go:437 +0xa3c
```

This doesn't happen consistently.

Here's `replay.jsonl`

```jsonl
{"rootDirPlaceholder":"@PROJECT_ROOT@","serverArgs":["--lsp","--stdio"]}
{"kind":"request","method":"initialize","params":{"processId":5566,"capabilities":{"textDocument":{"completion":{"completionItem":{"snippetSupport":true,"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"commitCharactersSupport":true,"deprecatedSupport":true,"preselectSupport":true,"labelDetailsSupport":true,"documentationFormat":["markdown","plaintext"],"insertTextModeSupport":{"valueSet":[1,2]}},"contextSupport":true},"definition":{"linkSupport":true},"references":{},"documentSymbol":{"hierarchicalDocumentSymbolSupport":true,"labelSupport":true},"foldingRange":{"foldingRange":{"collapsedText":true}},"codeAction":{"disabledSupport":true,"dataSupport":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"hover":{"contentFormat":["markdown","plaintext"]},"diagnostic":{"relatedDocumentSupport":true},"declaration":{"linkSupport":true},"implementation":{"linkSupport":true},"typeDefinition":{"linkSupport":true},"rename":{}},"workspace":{"symbol":{}}},"rootUri":"@PROJECT_ROOT@"}}
{"kind":"notification","method":"initialized","params":{}}
{"kind":"notification","method":"textDocument/didOpen","params":{"textDocument":{"uri":"@PROJECT_ROOT@/gulpfile.mjs","languageId":"javascript","version":1,"text":"/*---------------------------------------------------------------------------------------------\n *  Copyright (c) Microsoft Corporation. All rights reserved.\n *  Licensed under the MIT License. See License.txt in the project root for license information.\n *--------------------------------------------------------------------------------------------*/\nimport './build/gulpfile.ts';\n"}}}
{"kind":"request","method":"textDocument/completion","params":{"textDocument":{"uri":"@PROJECT_ROOT@/gulpfile.mjs"},"position":{"line":0,"character":0},"context":{"triggerKind":1}}}
{"kind":"request","method":"completionItem/resolve","params":{"label":"PictureInPictureEvent","kind":6,"sortText":"15","commitCharacters":[".",",",";"],"data":{"fileName":"/workspaces/typescript-error-deltas/vscode/gulpfile.mjs","name":"PictureInPictureEvent"}}}
```

where `@PROJECT_ROOT@` was just `file:///workspaces/typescript-error-deltas/vscode`

### PR DESCRIPTION
**Pull request by iisaduan**
fixes #2598

also fixes miscapitalization parsing bug and adds parsing test

### CODE REVIEW

File: internal/ls/lsutil/configuration.go [hunk 1]
```diff
@@ -46,16 +46,26 @@ func (a *UserConfig) Merge(b *UserConfig) *UserConfig {
 }
 
 func (c *UserConfig) TS() *UserPreferences {
-	return c.ts
+	if c.ts != nil {
+		return c.ts
+	} else if c.js != nil {
+		return c.js
+	}
```
Comment (jakebailey) [inline internal/ls/lsutil/configuration.go:53]: Are these ever actually nil? IIRC VS Code sends these objects fully, so we will always have both, and the crash would still happen, right?

Comment (andrewbranch) [reply internal/ls/lsutil/configuration.go:53]: If true, that would cause an issue with the fallback logic, but the actual crash fix is in snapshot.go.

Comment (iisaduan) [reply internal/ls/lsutil/configuration.go:53]: They only send them both fully if anything in that is specified. Otherwise it sends `nil`, which doesnt get parsed

Comment (iisaduan) [reply internal/ls/lsutil/configuration.go:53]: For example, if only `"typescript.quotePreference": true` was the only specified thing, then vscode would send `nil` for both "js/ts" and "javascript"

Comment (jakebailey) [reply internal/ls/lsutil/configuration.go:53]: This is not the behavior I've seen in the past from VS Code's LSP client.

I have nothing set:

```
2026-01-29 16:48:15.431 [trace] Received request 'workspace/configuration - (ts1)'.
Params: {
    "items": [
        {
            "section": "js/ts"
        },
        {
            "section": "typescript"
        },
        {
            "section": "javascript"
        }
    ]
}
2026-01-29 16:48:15.431 [trace] Sending response 'workspace/configuration - (ts1)'. Processing request took 2ms
Result: [
    {
        "implicitProjectConfig": {
            "module": "ESNext",
            "target": "ES2024",
            "checkJs": false,
            "experimentalDecorators": false,
            "strictNullChecks": true,
            "strictFunctionTypes": true,
            "strict": true
        },
        "hover": {
            "maximumLength": 500
        }
    },
    {
        "tsdk": "",
        "disableAutomaticTypeAcquisition": false,
        "enablePromptUseWorkspaceTsdk": false,
        "referencesCodeLens": {
            "enabled": false,
            "showOnAllFunctions": false
        },
        "implementationsCodeLens": {
            "enabled": false,
            "showOnInterfaceMethods": false,
            "showOnAllClassMethods": false
        },
        "experimental": {
            "useTsgo": true
        },
        "reportStyleChecksAsWarnings": true,
        "validate": {
            "enable": true
        },
        "tsc": {
            "autoDetect": "off"
        },
        "locale": "auto",
        "suggestionActions": {
            "enabled": true
        },
        "updateImportsOnFileMove": {
            "enabled": "prompt"
        },
        "autoClosingTags": true,
        "workspaceSymbols": {
            "scope": "allOpenProjects",
            "excludeLibrarySymbols": true
        },
        "preferGoToSourceDefinition": false,
        "tsserver": {
            "enableRegionDiagnostics": true,
            "nodePath": "",
            "web": {
                "projectWideIntellisense": {
                    "enabled": true,
                    "suppressSemanticErrors": false
                },
                "typeAcquisition": {
                    "enabled": true
                }
            },
            "useSyntaxServer": "auto",
            "maxTsServerMemory": 3072,
            "experimental": {
                "enableProjectDiagnostics": false
            },
            "watchOptions": "vscode",
            "enableTracing": false,
            "log": "off",
            "pluginPaths": []
        },
        "updateImportsOnPaste": {
            "enabled": true
        },
        "suggest": {
            "enabled": true,
            "autoImports": true,
            "completeFunctionCalls": false,
            "paths": true,
            "completeJSDocs": true,
            "jsdoc": {
                "generateReturns": true
            },
            "includeAutomaticOptionalChainCompletions": true,
            "includeCompletionsForImportStatements": true,
            "classMemberSnippets": {
                "enabled": true
            },
            "objectLiteralMethodSnippets": {
                "enabled": true
            }
        },
        "preferences": {
            "quoteStyle": "auto",
            "importModuleSpecifier": "shortest",
            "importModuleSpecifierEnding": "auto",
            "jsxAttributeCompletionStyle": "auto",
            "includePackageJsonAutoImports": "auto",
            "autoImportFileExcludePatterns": [],
            "autoImportSpecifierExcludeRegexes": [],
            "preferTypeOnlyAutoImports": false,
            "useAliasesForRenames": true,
            "renameMatchingJsxTags": true,
            "organizeImports": {}
        },
        "format": {
            "enable": true,
            "insertSpaceAfterCommaDelimiter": true,
            "insertSpaceAfterConstructor": false,
            "insertSpaceAfterSemicolonInForStatements": true,
            "insertSpaceBeforeAndAfterBinaryOperators": true,
            "insertSpaceAfterKeywordsInControlFlowStatements": true,
            "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
            "insertSpaceBeforeFunctionParenthesis": false,
            "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
            "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
            "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true,
            "insertSpaceAfterOpeningAndBeforeClosingEmptyBraces": true,
            "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
            "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
            "insertSpaceAfterTypeAssertion": false,
            "placeOpenBraceOnNewLineForFunctions": false,
            "placeOpenBraceOnNewLineForControlBlocks": false,
            "semicolons": "ignore",
            "indentSwitchCase": true
        },
        "inlayHints": {
            "parameterNames": {
                "enabled": "none",
                "suppressWhenArgumentMatchesName": true
            },
            "parameterTypes": {
                "enabled": false
            },
            "variableTypes": {
                "enabled": false,
                "suppressWhenTypeMatchesName": true
            },
            "propertyDeclarationTypes": {
                "enabled": false
            },
            "functionLikeReturnTypes": {
                "enabled": false
            },
            "enumMemberValues": {
                "enabled": false
            }
        },
        "npm": "",
        "check": {
            "npmIsInstalled": true
        },
        "native-preview": {
            "trace": {
                "server": "verbose"
            },
            "pprofDir": "",
            "tsdk": "",
            "goMemLimit": ""
        }
    },
    {
        "referencesCodeLens": {
            "enabled": false,
            "showOnAllFunctions": false
        },
        "validate": {
            "enable": true
        },
        "suggestionActions": {
            "enabled": true
        },
        "updateImportsOnFileMove": {
            "enabled": "prompt"
        },
        "autoClosingTags": true,
        "preferGoToSourceDefinition": false,
        "updateImportsOnPaste": {
            "enabled": true
        },
        "suggest": {
            "enabled": true,
            "autoImports": true,
            "names": true,
            "completeFunctionCalls": false,
            "paths": true,
            "completeJSDocs": true,
            "jsdoc": {
                "generateReturns": true
            },
            "includeAutomaticOptionalChainCompletions": true,
            "includeCompletionsForImportStatements": true,
            "classMemberSnippets": {
                "enabled": true
            }
        },
        "preferences": {
            "quoteStyle": "auto",
            "importModuleSpecifier": "shortest",
            "importModuleSpecifierEnding": "auto",
            "jsxAttributeCompletionStyle": "auto",
            "autoImportFileExcludePatterns": [],
            "autoImportSpecifierExcludeRegexes": [],
            "useAliasesForRenames": true,
            "renameMatchingJsxTags": true,
            "organizeImports": {}
        },
        "format": {
            "enable": true,
            "insertSpaceAfterCommaDelimiter": true,
            "insertSpaceAfterConstructor": false,
            "insertSpaceAfterSemicolonInForStatements": true,
            "insertSpaceBeforeAndAfterBinaryOperators": true,
            "insertSpaceAfterKeywordsInControlFlowStatements": true,
            "insertSpaceAfterFunctionKeywordForAnonymousFunctions": true,
            "insertSpaceBeforeFunctionParenthesis": false,
            "insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis": false,
            "insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets": false,
            "insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces": true,
            "insertSpaceAfterOpeningAndBeforeClosingEmptyBraces": true,
            "insertSpaceAfterOpeningAndBeforeClosingTemplateStringBraces": false,
            "insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces": false,
            "placeOpenBraceOnNewLineForFunctions": false,
            "placeOpenBraceOnNewLineForControlBlocks": false,
            "semicolons": "ignore",
            "indentSwitchCase": true
        },
        "inlayHints": {
            "parameterNames": {
                "enabled": "none",
                "suppressWhenArgumentMatchesName": true
            },
            "parameterTypes": {
                "enabled": false
            },
            "variableTypes": {
                "enabled": false,
                "suppressWhenTypeMatchesName": true
            },
            "propertyDeclarationTypes": {
                "enabled": false
            },
            "functionLikeReturnTypes": {
                "enabled": false
            }
        }
    }
]
```

Comment (iisaduan) [reply internal/ls/lsutil/configuration.go:53]: Oh this is weird. When I test it in the preview, the logs always say they're receiving `nil`

Comment (andrewbranch) [reply internal/ls/lsutil/configuration.go:53]: Regardless, would it be better to do fallbacks by individual preference? I think my intuition would be

- In a JS file, use the JS preference value ?? the TS preference value
- In a TS file, use the TS preference value

It feels to me like if you say `typescript.somepreference` you might be talking about both TS files and JS files since `typescript` refers to the editor extension / language server. But if you say `javascript.somepreference` you're probably just talking about JS?

Comment (andrewbranch) [reply internal/ls/lsutil/configuration.go:53]: Also again +10000000 for just nixing the `javascript.` preferences 😅

Comment (jakebailey) [reply internal/ls/lsutil/configuration.go:53]: By individual preference would be fine, but the client doesn't tell us that something was unset by the user and that it defaulted it, unless we use the vscode config introspection API and DIY it

Comment (jakebailey) [reply internal/ls/lsutil/configuration.go:53]: Yeah. I'd frankly much rather apply a client side hack for VS Code, only respect `typescript.` on the server side, and tell every other client "sorry, you know better than the average user"

Comment (jakebailey) [reply internal/ls/lsutil/configuration.go:53]: In lieu of that, though, I am happy with whatever PR we have that stops the crashing and then we address it later.

Comment (iisaduan) [reply internal/ls/lsutil/configuration.go:53]: Figured it out-- the send all the defaults behavior is provided by vscode.typescript-language-features, and it was disabled. But as Andrew mentioned, either way, the autoimports shouldn't crash anymore
