### PR TITLE
Port verifyCompilerOptions, error on things removed from this repo

### LINKED ISSUE #807: Inherited `baseUrl` is not respected
```json5
// @filename: src/tsconfig.json
{
  "extends": "../configs/tsconfig.base.json",
  "compilerOptions": {
    "target": "esnext",
    "module": "nodenext",
    "outDir": "../dist",
    "strict": true,
  },
  "include": ["**/*"],
}
```

```json5
// @filename: configs/tsconfig.base.json
{
    "compilerOptions": {
        "baseUrl": "../src",
        "paths": {
            "@/*": ["*"]
        }
    }
}
```

```ts
// @filename: a.ts
export const foo = 123;
```

```ts
// @filename: b.ts
import { foo } from "@/a.js";

foo + foo;
```

```
b.ts:1:21 - error TS2307: Cannot find module '@/a.js' or its corresponding type declarations.

1 import { foo } from "@/a.js";
                      ~~~~~~~~


Found 1 error in b.ts:1

Files:              84
Lines:           41514
Identifiers:     45336
Symbols:         40210
Types:           22379
Instantiations:  10412
Memory used:    43739K
Memory allocs:  326267
Parse time:     0.029s
Bind time:      0.007s
Check time:     0.110s
Emit time:      0.007s
Total time:     0.152s
```

### LINKED ISSUE #1376: "Cannot find module" when switching from `tsc` to `tsgo`
Reproduction: https://github.com/JakobJingleheimer/tsgo-specifier-resolution-failure

Setup:

```sh
cd ./package/foo
npm ci
```

Works:

```sh
npx tsc
```

Doesn't work:

```sh
npx tsgo
```

Error:

```
src/main.ts:1:21 - error TS2307: Cannot find module 'helpers/add.ts' or its corresponding type declarations.

1 import { add } from 'helpers/add.ts';
```

Extra info:

This was encountered in a next.js app, and the repro should be sufficiently representative of the original code.

### PR DESCRIPTION
**Pull request by jakebailey**
This ports most of `verifyCompilerOptions`, along with new checks that complain about `baseUrl` and `outFile`. `baseUrl` has a "fancy" error:

```
~/work/TypeScript-go/built/local/tsgo
tsconfig.json:4:5 - error TS5102: Option 'baseUrl' has been removed. Please remove it from your configuration.
  Use '"paths": {"*": "./src/*"}' instead.

4     "baseUrl": "./src",
      ~~~~~~~~~

Found 1 error in tsconfig.json:4
```

It also removes all of the options previously deprecated in 5.0 and "removed" in 5.5. Now they are just unsupported options, with no references in the code.

Probably easiest to view this PR with filters: https://github.com/microsoft/typescript-go/pull/1381/files?file-filters%5B%5D=.diff&file-filters%5B%5D=.go

Closes #1376
Closes #807
For #1247

### CODE REVIEW

**Comment by JakobJingleheimer** [comment]
Nice! I might remove the `Please remove it from your configuration.` from the message; IMO it just adds words.

This is nicely succinct and the instruction is clear.
```
tsconfig.json:4:5 - error TS5102: Option 'baseUrl' has been removed. Use '"paths": {"*": "./src/*"}' instead.
```

**Comment by jakebailey** [comment]
This is the format we've previously used for deprecations; I could do what you suggest but I'd have to create custom diagnostics not in the repo (which is fine, but sort of weird).

File: internal/compiler/program.go [hunk 1]
```diff
@@ -331,8 +342,479 @@ func (p *Program) GetSuggestionDiagnostics(ctx context.Context, sourceFile *ast.
...
+	if options.JsxImportSource != "" {
+		if options.Jsx == core.JsxEmitReact {
+			createDiagnosticForOptionName(diagnostics.Option_0_cannot_be_specified_when_option_jsx_is_1, "jsxImportSource", tsoptions.InverseJsxOptionMap.GetOrZero(options.Jsx))
+		}
+	}
+
+	moduleKind := options.GetEmitModuleKind()
+
+	if options.AllowImportingTsExtensions.IsTrue() && !(options.NoEmit.IsTrue() || options.EmitDeclarationOnly.IsTrue() || options.RewriteRelativeImportExtensions.IsTrue()) {
+		createOptionValueDiagnostic("allowImportingTsExtensions", diagnostics.Option_allowImportingTsExtensions_can_only_be_used_when_either_noEmit_or_emitDeclarationOnly_is_set)
```
Comment (RyanCavanaugh) [inline internal/compiler/program.go:725]: This is also a Strada bug - the message here should mention `RewriteRelativeImportExtensions` as a third out

File: internal/compiler/program.go [hunk 2]
```diff
@@ -331,8 +342,479 @@ func (p *Program) GetSuggestionDiagnostics(ctx context.Context, sourceFile *ast.
...
+		moduleResolutionName := moduleResolution.String()
+		createOptionValueDiagnostic("module", diagnostics.Option_module_must_be_set_to_0_when_option_moduleResolution_is_set_to_1, moduleResolutionName, moduleResolutionName)
+	}
+
+	// If the emit is enabled make sure that every output file is unique and not overwriting any of the input files
+	// if !options.NoEmit.IsTrue() && !options.SuppressOutputPathCheck.IsTrue() {
+	// 	var emitFilesSeen collections.Set[string]
+
+	// 	// Verify that all the emit files are unique and don't overwrite input files
+	// 	verifyEmitFilePath := func(emitFileName string) {
```
Comment (RyanCavanaugh) [inline internal/compiler/program.go]: Comment on why this block is commented out

**Review by RyanCavanaugh — APPROVED** [review]

File: internal/compiler/program.go (hunk 2 above)
Comment (jakebailey) [reply internal/compiler/program.go]: Rechecking this now; I forgot what broke.

Comment (jakebailey) [reply internal/compiler/program.go]: Fixed. improved some 82 baselines.

**Comment by hamidrezahanafi** [comment]
hey @jakebailey this change specifically removing baseUrl broke everything in our app. Many libraries like https://github.com/swc-project/swc is using `baseUrl` from `tsconfig` to figure out their base directory. 
I understand the need to remove since there is no usages but this will really make it hard to move to typescript go
Also, with the newest version for type checking, I still get conflicting errors like
```
error TS5090: Non-relative paths are not allowed when 'baseUrl' is not set. Did you forget a leading './'?
```
But the baseUrl is now removed, also I still get this error with multiple extended `tsconfigs` with absolute paths

**Comment by jakebailey** [comment]
Please file a new issue rather than replying here.

Removing `baseUrl` should be very straightforward no matter what as the option is entirely covered by other options.

That being said, the error message I put in this PR isn't entirely optimal, and there still remains messages that mention it which shouldn't. So, it'd be good to know how you're hitting that too. (Just not as a comment on a merged PR)

**Comment by jakebailey** [comment]
I'll note that if you weren't broken before this PR, it meant you could simply remove the option everywhere, since we were silently ignoring the option.
