### PR TITLE
Fix unknown extension crash in completions

### LINKED ISSUE #2669: Completions crash for unrecognized ambiently-defined file extensions
There might be a simpler repro but I believe this one only shows up when using some non-relative paths.

```ts
// @filename: src/some-file.ruhroh
/* This is just a test file that needs to exist. */

// @filename: package.json
{
    "imports": {
        "#/*": "./src/*"
    }
}

// @filename: src/globals.d.ts
declare module "*.ruhroh";

// @filename: src/a.mts
import "#//*$*/"

// @filename: tsconfig.json
{
    "compilerOptions": {
        "module": "preserve",
        "moduleResolution": "bundler",
        "rootDir": "src"
    },
    "include": ["src"]
}
```

Request completions at `/*$*/`.

```
Unexpected extension: .ruhroh
goroutine 14016 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x64
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x4000182e08, {0x7ff628c437c0?, 0x40036af6c0?}, 0x4006d404b0)
	github.com/microsoft/typescript-go/internal/lsp/server.go:783 +0x40
panic({0x7ff629318b00?, 0x4000548290?})
	runtime/panic.go:783 +0x120
github.com/microsoft/typescript-go/internal/ls.kindModifiersFromExtension({0x400ba638f1?, 0x7ff628c419cc?})
	github.com/microsoft/typescript-go/internal/ls/string_completions.go:1945 +0x2e8
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).convertPathCompletions.func1(...)
	github.com/microsoft/typescript-go/internal/ls/string_completions.go:216
github.com/microsoft/typescript-go/internal/core.Map[...](...)
	github.com/microsoft/typescript-go/internal/core/core.go:58
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).convertPathCompletions(0x4004550e00, {0x7ff629826e08, 0x400e9ee570}, {0x400320bf20, 0x3, 0x400e9eeb10?}, 0x400bb6ca88, 0xa)
	github.com/microsoft/typescript-go/internal/ls/string_completions.go:200 +0x23c
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).convertStringLiteralCompletions(0x4004550e00, {0x7ff629826e08, 0x400e9ee570}, 0x400e9eeb10, 0x4000214510, 0x400bb6ca88, 0xa, 0x4001981308, 0x40077a1508)
	github.com/microsoft/typescript-go/internal/ls/string_completions.go:106 +0x344
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getStringLiteralCompletions(0x4004550e00, {0x7ff629826e08, 0x400e9ee570}, 0x400bb6ca88, 0xa, 0x4000214510, 0x4001981308, 0x40077a1508)
	github.com/microsoft/typescript-go/internal/ls/string_completions.go:76 +0xc4
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionsAtPosition(0x4004550e00, {0x7ff629826e08, 0x400e9ee570}, 0x400bb6ca88, 0xa, 0x0)
	github.com/microsoft/typescript-go/internal/ls/completions.go:321 +0x19c
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideCompletion(0x4004550e00, {0x7ff629826e08, 0x400e9ee4b0}, {0x400c831d00?, 0x400e9ee4b0?}, {0xc831d00?, 0x40?}, 0x400c026bf0)
	github.com/microsoft/typescript-go/internal/ls/completions.go:47 +0x204
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleCompletion(0x4003ab5df8?, {0x7ff629826e08?, 0x400e9ee4b0?}, 0x400c831d00?, 0x20b011f05a0?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:1111 +0x3c
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceWithAutoImportsRequestHandler[...].28({0x7ff629826e08, 0x400e9ee4b0}, 0x4006d404b0)
	github.com/microsoft/typescript-go/internal/lsp/server.go:688 +0xf4
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x4000182e08, {0x7ff629826e40?, 0x400c0b7680?}, 0x4006d404b0)
	github.com/microsoft/typescript-go/internal/lsp/server.go:533 +0xc8
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:412 +0x34
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 10
	github.com/microsoft/typescript-go/internal/lsp/server.go:436 +0x7d8

```

### PR DESCRIPTION
**Pull request by gabritto**
Fixes #2669.

I updated the path completions code to add extensions in more cases compared to Strada (#2610), so now we may include unsupported extensions in path completions, but we shouldn't crash on them.

### CODE REVIEW

File: internal/fourslash/tests/completionsPathUnknownExtension_test.go [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+	f, done := fourslash.NewFourslash(t, nil /*capabilities*/, content)
+	defer done()
+	f.VerifyCompletions(t, "$", &fourslash.CompletionsExpectedList{
+		IsIncomplete: false,
+		ItemDefaults: &fourslash.CompletionsExpectedItemDefaults{
+			CommitCharacters: &[]string{},
+			EditRange:        Ignored,
+		},
+		Items: &fourslash.CompletionsExpectedItems{
+			Includes: []fourslash.CompletionsExpectedItem{},
```
Comment (DanielRosenwasser) [inline internal/fourslash/tests/completionsPathUnknownExtension_test.go]: Do we want to verify that the completions includes the file that previously caused the crash?
