### PR TITLE
Fix document highlights crashes on missing tokens/nodes

### LINKED ISSUE #2670: Document highlights crash when missing `catch` and `finally` clauses
```ts
try/**/ {

}
```

Get document highlights on `try`

```
[error] panic handling request textDocument/documentHighlight: runtime error: invalid memory address or nil pointer dereference
goroutine 557 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x64
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x4000182e08, {0x7ff628c437c0?, 0x40019f6a80?}, 0x40025f4c90)
	github.com/microsoft/typescript-go/internal/lsp/server.go:783 +0x40
panic({0x7ff6293588c0?, 0x7ff629ea4000?})
	runtime/panic.go:783 +0x120
github.com/microsoft/typescript-go/internal/ls.getTryCatchFinallyOccurrences(0x4002894360, 0x40013e2388)
	github.com/microsoft/typescript-go/internal/ls/documenthighlights.go:415 +0x17c
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).useParent(0x4000131680, 0x4002894360, 0x0?, 0x7ff6296eb940, 0x40013e2388)
	github.com/microsoft/typescript-go/internal/ls/documenthighlights.go:149 +0x50
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getSyntacticDocumentHighlights(0x4000131680, 0x7ff629826e08?, 0x40013e2388)
	github.com/microsoft/typescript-go/internal/ls/documenthighlights.go:113 +0x1cc
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideDocumentHighlights(0x4000131680, {0x7ff629826e08, 0x4002776240}, {0x40002a2340?, 0x37?}, {0x28bd7f84?, 0x7ff6?})
	github.com/microsoft/typescript-go/internal/ls/documenthighlights.go:46 +0x394
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleDocumentHighlight(0x30?, {0x7ff629826e08?, 0x4002776240?}, 0x40002a2340?, 0x40019e7de8?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:1178 +0x38
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceDocumentRequestHandler[...].21({0x7ff629826e08, 0x4002776240}, 0x40025f4c90)
	github.com/microsoft/typescript-go/internal/lsp/server.go:665 +0xe4
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x4000182e08, {0x7ff629826e40?, 0x4002173540?}, 0x40025f4c90)
	github.com/microsoft/typescript-go/internal/lsp/server.go:533 +0xc8
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:412 +0x34
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 10
	github.com/microsoft/typescript-go/internal/lsp/server.go:436 +0x7d8
```

### PR DESCRIPTION
**Pull request by DanielRosenwasser**
Fixes #2670.

### CODE REVIEW

**Review by johnfav03 — APPROVED** [review]

File: internal/ls/documenthighlights.go [hunk 1]
```diff
@@ -399,20 +411,18 @@ func getTryCatchFinallyOccurrences(node *ast.Node, sourceFile *ast.SourceFile) [
 
 	var keywords []*ast.Node
 	token := lsutil.GetFirstToken(node, sourceFile)
-	if token.Kind == ast.KindTryKeyword {
```
Comment (gabritto) [inline internal/ls/documenthighlights.go:402]: This seems to be a porting oopsie because the original `pushKeywordIf` dealt with `nil` and the Go version got rid of it and those occurrences weren't handling `nil`. I see we have other occurrences of `pushKeywordIf` in Strada. Do we need to also go and fix other occurrences other than those ones in this PR?
