### PR TITLE
Finish implementing sourceFileMayBeEmitted, JSON emit

### LINKED ISSUE #660: JSON file includes do not change lowest common ancestor for outDir
Example project to reproduce the issue: [repro.zip](https://github.com/user-attachments/files/19317861/repro.zip)

Result when running `tsgo` here:
```
build\
  index.js
```

Expected result / what `tsc` outputs:
```
build\
  static\
    data.json
  src\
    index.js
```

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #660

I'm not happy with the emit change, but I don't know what the right fix is. Strada did parenthesizing completely differently.

### CODE REVIEW

File: internal/printer/printer.go [hunk 1]
```diff
@@ -3175,7 +3175,10 @@ func (p *Printer) emitEmptyStatement(node *ast.EmptyStatement, isEmbeddedStateme
 func (p *Printer) emitExpressionStatement(node *ast.ExpressionStatement) {
 	state := p.enterNode(node.AsNode())
 
-	if isImmediatelyInvokedFunctionExpressionOrArrowFunction(node.Expression) {
+	if p.currentSourceFile != nil && p.currentSourceFile.ScriptKind == core.ScriptKindJSON {
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/printer/printer.go:3178]: Ah yes, it's that simple

File: internal/compiler/emitter.go [hunk 2]
```diff
@@ -323,8 +340,19 @@ func sourceFileMayBeEmitted(sourceFile *ast.SourceFile, host printer.EmitHost, f
 		return true
 	}
 
-	// !!! Should JSON input files be emitted
-	return false
```
Comment (sheetalkamat) [inline internal/compiler/emitter.go:399]:
```
// Json file is not emitted if outDir is not specified
    if (!options.outDir) return false;
```

this one is missing ?

**Review by sheetalkamat — CHANGES_REQUESTED** [review]

File: internal/compiler/emitter.go (hunk 2 above)
Comment (jakebailey) [reply internal/compiler/emitter.go:399]: Good catch, I missed that one. Probably misread it as `outFile`
