### PR TITLE
fix(checker): add nil guard for thisType in getThisType

### LINKED ISSUE #3087: panic handling request textDocument/documentHighlight: runtime error: invalid memory address or nil pointer dereference
## Stack trace

```
goroutine 3410384 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x1a115f6e0e08, 0x1a12efbd23c0)
	github.com/microsoft/typescript-go/internal/lsp/server.go:877 +0x47
panic({0xce5180?, 0x1a53880?})
	runtime/panic.go:860 +0x13a
github.com/microsoft/typescript-go/internal/checker.(*Checker).getSymbolAtLocation(0x1a11fcc93908, 0x1a124714c868, 0x1)
	github.com/microsoft/typescript-go/internal/checker/checker.go:30611 +0xc1c
github.com/microsoft/typescript-go/internal/checker.(*Checker).GetSymbolAtLocation(0x1a11fcc93908, 0x1a12c67aa100?)
	github.com/microsoft/typescript-go/internal/checker/checker.go:30524 +0x2d
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getReferencedSymbolsForNode(0x1a12bf886000, {0x10aad58, 0x1a1314ce6060}, 0x45c, 0x1a124714c868, 0x1a122b4b0908, {0x1a12c67aa100, 0x1, 0x1}, {0x0, ...})
	github.com/microsoft/typescript-go/internal/ls/findallreferences.go:977 +0x597
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getSemanticDocumentHighlights(0x1a12bf886000, {0x10aad58, 0x1a1314ce6060}, 0x45c, 0x1a124714c868, 0x1a122b4b0908, 0x1a126cb06008)
	github.com/microsoft/typescript-go/internal/ls/documenthighlights.go:54 +0xf0
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideDocumentHighlights(0x1a12bf886000, {0x10aad58, 0x1a1314ce6060}, {0x1a1328e9e500?, 0x420fb7?}, {0x3fa015d8?, 0x7fa4?})
	github.com/microsoft/typescript-go/internal/ls/documenthighlights.go:44 +0x3c5
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleDocumentHighlight(0x42bab6?, {0x10aad58?, 0x1a1314ce6060?}, 0x4219cf?, 0x7fa488825108?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:1268 +0x35
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceDocumentRequestHandler[...].21.1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:748 +0x9c
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:611 +0x68
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func3()
	github.com/microsoft/typescript-go/internal/lsp/server.go:488 +0x2c
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 11
	github.com/microsoft/typescript-go/internal/lsp/server.go:487 +0x4ac

```

## Steps to reproduce

1. open code

```ts
interface X {
  f(): typeof this;
}
```

### PR DESCRIPTION
**Pull request by Zzzen**
fix #3087

### CODE REVIEW

File: internal/fourslash/tests/documentHighlightTypeofThis_test.go [hunk 1]
```diff
@@ -0,0 +1,23 @@
+package fourslash_test
```
Comment (gabritto) [inline internal/fourslash/tests/documentHighlightTypeofThis_test.go:1]: This test needs to be moved to `internal/fourslash/tests`. `gen` is for tests automatically translated from our TS tests.

File: testdata/tests/cases/compiler/thisTypeInvalidContexts.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
+// @strict: true
```
Comment (gabritto) [inline testdata/tests/cases/compiler/thisTypeInvalidContexts.ts]: I don't know that we need all of those new compiler tests. We already have tests like `thisTypeErrors` that test whether the compiler errors on `this` in many situations. I'd stick to just the fourslash test for this PR.

**Comment by Zzzen** [comment]
lol yeah that assertion is definitely too optimistic 😬

Quick q: any idea why Strada doesn't show a crash popup for this? Just wondering if it's caught/swallowed somewhere higher up.

**Comment by jakebailey** [comment]
Strada didn't report errors anywhere to anyone 😄 

Right now, we do the loudest thing possible and actually let the VS Code LSP client show an error rather than silencing it.
