### PR TITLE
Don't request auto imports in untitled files

### LINKED ISSUE #2550: Crash for auto-imports from untitled file to saved tsx file
1. Open up `TypeScript/tests/cases/conformance/jsx/tsxStatelessFunctionComponentOverload6.tsx`
2. Create a new buffer as a JS file.
3. Request completions.

You can get away with paring the file down to just

```
export function f() {}
```

and still get errors

```
[error] panic handling request textDocument/completion: runtime error: invalid memory address or nil pointer dereference
goroutine 4011 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x5e
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0xc0001d8e08, {0x10f1768, 0xc011cfec00}, 0xc011cfeb40)
	github.com/microsoft/typescript-go/internal/lsp/server.go:773 +0x5d
panic({0xc2ed00?, 0x177cbb0?})
	runtime/panic.go:783 +0x132
github.com/microsoft/typescript-go/internal/collections.(*SyncMap[...]).Load(0x110aa40?, {0xc00011dd57, 0xc00044e900?})
	github.com/microsoft/typescript-go/internal/collections/syncmap.go:15 +0x18
github.com/microsoft/typescript-go/internal/ls/autoimport.(*View).GetModuleSpecifier(0xc00c451680, 0xc00faaa9c0, {{0x0, 0x0}, {0xe41311, 0x4}, {0x17d7c00, 0x0, 0x0}})
	github.com/microsoft/typescript-go/internal/ls/autoimport/specifiers.go:46 +0x165
github.com/microsoft/typescript-go/internal/ls/autoimport.(*View).GetFixes(0xc00c451680, {0x10f1768, 0xc01037a090}, 0xc00faaa9c0, 0x0, 0x0, 0xc006d92dd8)
	github.com/microsoft/typescript-go/internal/ls/autoimport/fix.go:560 +0x206
github.com/microsoft/typescript-go/internal/ls/autoimport.(*View).GetCompletions(0xc00c451680, {0x10f1768, 0xc01037a090}, {0x0, 0x0}, {0x0, 0x1e}, 0x0, 0x0)
	github.com/microsoft/typescript-go/internal/ls/autoimport/view.go:232 +0xb17
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData.func9()
	github.com/microsoft/typescript-go/internal/ls/completions.go:1105 +0x1ca
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData.func17()
	github.com/microsoft/typescript-go/internal/ls/completions.go:1514 +0x5f7
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData.func18(...)
	github.com/microsoft/typescript-go/internal/ls/completions.go:1544
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionData(0xc013302580, {0x10f1768, 0xc01037a090}, 0xc00f53f908, 0xc000024608, 0x1e, 0xc001f7b400)
	github.com/microsoft/typescript-go/internal/ls/completions.go:1577 +0x1ed4
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionsAtPosition(0xc013302580, {0x10f1768, 0xc01037a090}, 0xc000024608, 0x1e, 0x0)
	github.com/microsoft/typescript-go/internal/ls/completions.go:346 +0x35f
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideCompletion(0xc013302580, {0x10f1768, 0xc011cfec00}, {0xc007a36a38?, 0xc00f98bd60?}, {0x4fdc04?, 0x0?}, 0xc0002473a0)
	github.com/microsoft/typescript-go/internal/ls/completions.go:46 +0x11c
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleCompletion(0xc00047a000?, {0x10f1768?, 0xc011cfec00?}, 0xc007a36a38?, 0x13?)
	github.com/microsoft/typescript-go/internal/lsp/server.go:1088 +0x39
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceWithAutoImportsRequestHandler[...].28({0x10f1768, 0xc011cfec00}, 0xc011cfeb40)
	github.com/microsoft/typescript-go/internal/lsp/server.go:687 +0x2c4
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0xc0001d8e08, {0x10f17a0?, 0xc01006ba40?}, 0xc011cfeb40)
	github.com/microsoft/typescript-go/internal/lsp/server.go:527 +0x1d0
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:414 +0x45
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 19
	github.com/microsoft/typescript-go/internal/lsp/server.go:434 +0x9ca
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #2550

### CODE REVIEW

File: internal/fourslash/tests/exhaustiveCaseCompletionsUntitled_test.go [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+	const content = `// @newline: LF
+// @filename: /home/src/project/enums.ts
+export enum Status {
+    Active,
+    Inactive,
+    Pending,
+}
+
+// @filename: ^/untitled/ts-nul-authority/Untitled-1.ts
+declare const s: import("/home/src/project/enums").Status;
```
Comment (DanielRosenwasser) [inline internal/fourslash/tests/exhaustiveCaseCompletionsUntitled_test.go]: The fact that the path can be referenced as an absolute path - I mean, you probably don't want this as an auto-import, right?

**Comment by andrewbranch** [comment]
I’m pretty sure they mostly don’t work, but we don’t bail out early like this. We probably compute them and then filter them out because they have absolute paths.
