### PR TITLE
Support auto-import completion fourslash tests, fix bugs

### LINKED ISSUE #1873: Crash in auto-import completions
## Stack trace

```
panic handling request completionItem/resolve runtime error: invalid memory address or nil pointer dereference goroutine 1355 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:26 +0x64
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x4000000f00, 0x400a336450)
	github.com/microsoft/typescript-go/internal/lsp/server.go:542 +0x44
panic({0x7ff62d3bf340?, 0x7ff62dcef4c0?})
	runtime/panic.go:783 +0x120
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getAutoImportSymbolFromCompletionEntryData(0x4009b63b38?, 0x4007a27908, {0x40031a0ee0, 0xd}, 0x4006711dc0)
	github.com/microsoft/typescript-go/internal/ls/completions.go:5256 +0x2d8
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getSymbolCompletionFromItemData(0x4009ce4180, {0x7ff62d71eb90, 0x400718c9b0}, 0x4007a27908, 0x4007150f08, 0x4, 0x4009cacac0, 0x7ff62cd27f84?, 0x4009b63d90)
	github.com/microsoft/typescript-go/internal/ls/completions.go:5158 +0xbc
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionItemDetails(0x4009ce4180, {0x7ff62d71eb90, 0x400718c9b0}, 0x0?, 0x4, 0x4007150f08, 0x400a352460, 0x4009cacac0, 0x40001cae70, 0x4009b63d90)
	github.com/microsoft/typescript-go/internal/ls/completions.go:5070 +0xc0
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ResolveCompletionItem(0x4009ce4180, {0x7ff62d71eb90, 0x400718c9b0}, 0x400a352460, 0x4009cacac0, 0x40001cae70, 0x4009b63d90)
	github.com/microsoft/typescript-go/internal/ls/completions.go:5028 +0x78
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleCompletionItemResolve(0x4000000f00, {0x7ff62d71eb90, 0x400718c9b0}, 0x400a352460, 0x400a336450)
	github.com/microsoft/typescript-go/internal/lsp/server.go:807 +0x10c
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerRequestHandler[...].26({0x7ff62d71eb90, 0x400718c9b0}, 0x400a336450)
	github.com/microsoft/typescript-go/internal/lsp/server.go:504 +0xc0
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x4000000f00, {0x7ff62d71eb90, 0x400718c9b0}, 0x400a336450)
	github.com/microsoft/typescript-go/internal/lsp/server.go:425 +0xf4
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	github.com/microsoft/typescript-go/internal/lsp/server.go:330 +0x34
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 10
	github.com/microsoft/typescript-go/internal/lsp/server.go:350 +0x6f8
```

## Steps to reproduce

1. Open new anonymous buffer.
2. Type in `res`
3. Type in the letter `u` (buffer contents are now `resu`)
4. Get crash

### LINKED ISSUE #1890: Crash getting auto-import completion details in zero-length file
## Stack trace

```
panic handling request completionItem/resolve runtime error: index out of range [0] with length 0 goroutine 1063 [running]:
runtime/debug.Stack()
	/Users/andrew/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.darwin-arm64/src/runtime/debug/stack.go:26 +0x64
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x14000208000, 0x14008bd26c0)
	/Users/andrew/Developer/microsoft/typescript-go/internal/lsp/server.go:542 +0x44
panic({0x1030dfa80?, 0x140020624b0?})
	/Users/andrew/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.25.0.darwin-arm64/src/runtime/panic.go:783 +0x120
github.com/microsoft/typescript-go/internal/ls.(*changeTracker).insertAtTopOfFile(0x1400952e780, 0x1400417fb08, {0x14008f9db48, 0x1, 0x1}, 0x1)
	/Users/andrew/Developer/microsoft/typescript-go/internal/ls/changetracker.go:291 +0x148
github.com/microsoft/typescript-go/internal/ls.(*changeTracker).insertImports(0x1400952e780, 0x1400417fb08, {0x14008f9db48, 0x1, 0x1}, 0x1, 0x0?)
	/Users/andrew/Developer/microsoft/typescript-go/internal/ls/autoimportfixes.go:237 +0xd8
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).codeActionForFixWorker(0x14006821b30, 0x1400952e780, 0x1400417fb08, {0x1400951a6b0, 0xd}, 0x14008f68680, 0x0, 0x1400003bd90)
	/Users/andrew/Developer/microsoft/typescript-go/internal/ls/autoimports.go:1451 +0x3a0
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).codeActionForFix(0x14006821b30, {0x103228d90?, 0x1400952e730?}, 0x1400417fb08, {0x1400951a6b0, 0xd}, 0x14008f68680, 0x0, 0x1400003bd90)
	/Users/andrew/Developer/microsoft/typescript-go/internal/ls/autoimports.go:1396 +0x78
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getImportCompletionAction(0x14006821b30, {0x103228d90, 0x1400952e730}, 0x14005211908, 0x1400808aea0?, 0x14006821cb0?, 0x1400417fb08, 0x0, {{0x1400951a6b0, 0xd}, ...}, ...)
	/Users/andrew/Developer/microsoft/typescript-go/internal/ls/autoimports.go:396 +0xf8
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionItemActions(0x14006821b30, {0x103228d90, 0x1400952e730}, 0x14005211908, 0x1400417fb08, 0x0, 0x14005f7d300, 0x14005f7d380, 0x1400062dd90)
	/Users/andrew/Developer/microsoft/typescript-go/internal/ls/completions.go:5355 +0x348
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getCompletionItemDetails(0x14006821b30, {0x103228d90, 0x1400952e730}, 0x8?, 0x0, 0x1400417fb08, 0x14008737400, 0x14005f7d300, 0x1400023bf50, 0x1400062dd90)
	/Users/andrew/Developer/microsoft/typescript-go/internal/ls/completions.go:5101 +0x45c
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ResolveCompletionItem(0x14006821b30, {0x103228d90, 0x1400952e730}, 0x14008737400, 0x14005f7d300, 0x1400023bf50, 0x1400062dd90)
	/Users/andrew/Developer/microsoft/typescript-go/internal/ls/completions.go:5028 +0x78
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleCompletionItemResolve(0x14000208000, {0x103228d90, 0x1400952e730}, 0x14008737400, 0x14008bd26c0)
	/Users/andrew/Developer/microsoft/typescript-go/internal/lsp/server.go:807 +0x10c
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerRequestHandler[...].26({0x103228d90, 0x1400952e730}, 0x14008bd26c0)
	/Users/andrew/Developer/microsoft/typescript-go/internal/lsp/server.go:504 +0xc0
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification(0x14000208000, {0x103228d90, 0x1400952e730}, 0x14008bd26c0)
	/Users/andrew/Developer/microsoft/typescript-go/internal/lsp/server.go:425 +0xf4
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func1()
	/Users/andrew/Developer/microsoft/typescript-go/internal/lsp/server.go:330 +0x34
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 35
	/Users/andrew/Developer/microsoft/typescript-go/internal/lsp/server.go:350 +0x6f8
```

### PR DESCRIPTION
**Pull request by andrewbranch**
Fixes #1873
Fixes #1890

### CODE REVIEW

File: internal/ls/changetracker.go [hunk 1]
```diff
@@ -165,6 +165,12 @@ func (ct *changeTracker) insertNodesAfter(sourceFile *ast.SourceFile, after *ast
 	ct.insertNodesAt(sourceFile, endPosition, newNodes, ct.getInsertNodeAfterOptions(sourceFile, after))
 }
 
+func (ct *changeTracker) insertNodeBefore(sourceFile *ast.SourceFile, before *ast.Node, newNode *ast.Node, blankLineBetween bool) {
+	// TODO: use getAdjustedStartPosition when implemented
```
Comment (jakebailey) [inline internal/ls/changetracker.go]: This I think was just implemented

File: internal/ls/organizeimports.go [hunk 2]
```diff
@@ -126,3 +127,287 @@ func isIndexFileName(fileName string) bool {
...
+		return 0
+	}
+
+	low := 0
+	high := len(sortedImports) - 1
+
+	for low <= high {
+		middle := low + ((high - low) >> 1)
+		midKey := sortedImports[middle]
+		switch comparer(midKey, newImport) {
```
Comment (jakebailey) [inline internal/ls/organizeimports.go]: I think this is a pure port, but I am always suspicious of code which exactly checks these comparison constants.

File: internal/ls/organizeimports.go [hunk 3]
```diff
@@ -126,3 +127,287 @@ func isIndexFileName(fileName string) bool {
...
+			}
+		}
+		moduleSpecifiersByGroup = append(moduleSpecifiersByGroup, moduleNames)
+	}
+	return detectCaseSensitivityBySort(moduleSpecifiersByGroup, comparersToTest)
+}
+
+func detectCaseSensitivityBySort(originalGroups [][]string, comparersToTest []func(a, b string) stringutil.Comparison) caseSensitivityDetectionResult {
+	var bestComparer func(a, b string) stringutil.Comparison
+	bestDiff := int(^uint(0) >> 1) // max int
```
Comment (jakebailey) [inline internal/ls/organizeimports.go]: Can probably just do `math.MaxInt`.

Comment (andrewbranch) [reply internal/ls/organizeimports.go]: Hah, the organizeImports helpers were a pure agent mode contribution and I didn't catch this

File: internal/ls/organizeimports.go [hunk 4]
```diff
@@ -126,3 +128,269 @@ func isIndexFileName(fileName string) bool {
...
+	// Get the list of comparers to test based on preferences
+	var comparersToTest []func(a, b string) int
+	if preferences != nil && !preferences.OrganizeImportsIgnoreCase.IsUnknown() {
+		// If case sensitivity is explicitly specified, only test that one
+		comparersToTest = []func(a, b string) int{
+			getOrganizeImportsOrdinalStringComparer(preferences.OrganizeImportsIgnoreCase.IsTrue()),
+		}
+	} else {
+		// Otherwise, test both case-insensitive and case-sensitive
+		comparersToTest = []func(a, b string) int{
```
Comment (jakebailey) [inline internal/ls/organizeimports.go]: Probably a change for the future, but I suspect we can preallocate some of these lists and reuse them given they appear to be a pure function on preferences. Not sure if this is hot code, though.

File: internal/ls/organizeimports.go [hunk 5]
```diff
@@ -126,3 +128,269 @@ func isIndexFileName(fileName string) bool {
...
+			getOrganizeImportsOrdinalStringComparer(preferences.OrganizeImportsIgnoreCase.IsTrue()),
+		}
+	} else {
+		// Otherwise, test both
+		comparersToTest = []func(a, b string) int{
+			getOrganizeImportsOrdinalStringComparer(true),  // case-insensitive first
+			getOrganizeImportsOrdinalStringComparer(false), // case-sensitive second
+		}
+	}
```
Comment (jakebailey) [inline internal/ls/organizeimports.go]: Is this identical to the code above?
