### PR TITLE
Fix getReferencedSymbolsForSymbol, implement getReferencesAtExportSpecifier

### LINKED ISSUE #2204: [bug] TSGO fails to follow re-exports when finding references
### Extension Version

 0.20251203.1

### VS Code Version

1.106.3 (Universal)

### Operating system Version

MacOS

### Steps to reproduce

Attempt to use find refs against `symbolA` in https://github.com/mjames-c/tsgo-playground

### Issue

TSGO can follow re-exports of symbols when a user uses find refs. Re-exports are pretty common in the Canva code base so having this would be pretty huge for us!

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #2204

- `getReferencesAtExportSpecifier` had not been ported.
- `getReferencedSymbolsForSymbol` had a condition backwards.

Finding the latter involved debugging a panic; in this PR is also a fix to fourslash to actually print out an error message instead of "nil response".

### CODE REVIEW

File: internal/ls/findallreferences.go [hunk 1]
```diff
@@ -1528,14 +1528,12 @@ func getReferencedSymbolsForSymbol(originalSymbol *ast.Symbol, node *ast.Node, s
 	state := newState(sourceFiles, sourceFilesSet, node, checker /*, cancellationToken*/, searchMeaning, options)
 
 	var exportSpecifier *ast.Node
-	if !isForRenameWithPrefixAndSuffixText(options) || len(symbol.Declarations) == 0 {
+	if isForRenameWithPrefixAndSuffixText(options) && len(symbol.Declarations) != 0 {
```
Comment (gabritto) [inline internal/ls/findallreferences.go:1531]: Not specific to this PR, but maybe we want to rename this function since the actual user preference is `useAliasesForRenames`?

Comment (jakebailey) [reply internal/ls/findallreferences.go:1531]: It was called `isForRenameWithPrefixAndSuffixText` in Strada, we are just seemingly inconsistent all around...

Comment (gabritto) [reply internal/ls/findallreferences.go:1531]: I know, that's what I meant. Strada used `providePrefixAndSuffixTextForRename` as the preference name and related functions, but it was called `useAliasesForRenames` in vscode, and now in Corsa we confusingly have both terms.

Comment (jakebailey) [reply internal/ls/findallreferences.go:1531]: Yeah. Probably better fixed in another PR. #2272 at least lets us choose whichever name we want.
