### PR TITLE
Block renames in keywords/stdlib, add prepareRename

### LINKED ISSUE #2229: Should not allow renaming keywords
TS-go will allow triggering rename anywhere in the file, including on parens and keywords. When you press enter it will then either try doing a rename or say `no result`

Instead we should fail the rename early. Here's what happens in TS 6

Image

I believe this warning comes from the `prepareRename` call

### LINKED ISSUE #2230: Should not allow renaming parts of the standard library
Similar to #2229 but we should also make sure you can't try to rename standard library functions like `setTimeout`

### PR DESCRIPTION
**Pull request by jakebailey**
Fixes #2229
Fixes #2230

We were lacking `prepareRename`. For clients without `prepareRename`, we still precheck in the actual rename call.

This also ports more fourslash so we can test more of this.

image

image

image

### CODE REVIEW

File: internal/lsp/server.go [hunk 1]
```diff
@@ -1169,6 +1172,19 @@ func (s *Server) handleHover(ctx context.Context, ls *ls.LanguageService, params
 	return ls.ProvideHover(ctx, params.TextDocument.Uri, params.Position)
 }
 
+func (s *Server) handlePrepareRename(ctx context.Context, languageService *ls.LanguageService, params *lsproto.PrepareRenameParams) (lsproto.PrepareRenameResponse, error) {
+	info := languageService.GetRenameInfo(ctx, params.TextDocument.Uri, params.Position)
+	if !info.CanRename {
+		return lsproto.PrepareRenameResponse{}, nil
+	}
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/lsp/server.go:1190]: Yeah, turns out LSP does not expose this. Commented these out for now

File: internal/ls/rename.go [hunk 2]
```diff
@@ -0,0 +1,363 @@
...
+	for i := len(components) - 1; i >= 0; i-- {
+		if components[i] == "node_modules" {
+			nodeModulesIdx = i
+			break
+		}
+	}
+	if nodeModulesIdx == -1 {
+		return nil
+	}
+	end := min(nodeModulesIdx+2, len(components))
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/ls/rename.go]: this is a pure port, but maybe

File: internal/ls/rename.go [hunk 3]
```diff
@@ -0,0 +1,363 @@
...
+
+	node := astnav.GetTouchingPropertyName(sourceFile, pos)
+	node = getAdjustedLocation(node, true /*forRename*/, sourceFile)
+
+	if isNodeEligibleForRename(node) {
+		if renameInfo, ok := l.getRenameInfoForNode(ctx, node, sourceFile, program); ok {
+			return renameInfo
+		}
+	}
+	return getRenameInfoError(ctx, diagnostics.You_cannot_rename_this_element)
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/ls/rename.go:57]: This is still a gap, we are missing a bunch of string stuff

File: internal/fourslash/_scripts/tsconfig.json [hunk 4]
```diff
@@ -4,6 +4,7 @@
         "noEmit": true,
         "module": "nodenext",
         "allowImportingTsExtensions": true,
-        "noFallthroughCasesInSwitch": true
+        "noFallthroughCasesInSwitch": true,
+        "types": ["node"]
```
Comment (gabritto) [inline internal/fourslash/_scripts/tsconfig.json:8]: Why do we need this?

File: internal/ls/rename.go [hunk 5]
```diff
@@ -0,0 +1,351 @@
...
+func (l *LanguageService) getRenameInfoForNode(ctx context.Context, node *ast.Node, sourceFile *ast.SourceFile, program *compiler.Program) (RenameInfo, bool) {
+	ch, done := program.GetTypeChecker(ctx)
+	defer done()
+
+	symbol := ch.GetSymbolAtLocation(node)
+	if symbol == nil {
+		if ast.IsStringLiteralLike(node) {
+			// Allow renaming of string literal types with contextual string literal types
+			typ := getContextualTypeFromParent(node, ch, checker.ContextFlagsNone)
+			if typ != nil && (typ.Flags()&checker.TypeFlagsStringLiteral != 0 ||
```
Comment (gabritto) [inline internal/ls/rename.go]: Personal nit, but I find it more readable to use `typ.IsStringLiteral()`, `typ.IsUnion()`, etc.

File: internal/fourslash/_scripts/tsconfig.json (hunk 4 above)
Comment (jakebailey) [reply internal/fourslash/_scripts/tsconfig.json:8]: The scripts don't compile anymore, since we started defaulting to `[]`. A drive by but annoying when looking at the converter.

File: internal/ls/rename.go (hunk 5 above)
Comment (jakebailey) [reply internal/ls/rename.go]: Yeah, this was just auto-completed, but the original code does use methods.

Comment (jakebailey) [reply internal/ls/rename.go]: Yeah, this was just auto-completed, but the original code does use methods.

File: internal/ls/rename.go [hunk 6]
```diff
@@ -0,0 +1,363 @@
...
+
+// wouldRenameInOtherNodeModules checks if renaming the symbol would affect node_modules.
+func wouldRenameInOtherNodeModules(originalFile *ast.SourceFile, symbol *ast.Symbol, ch *checker.Checker, preferences *lsutil.UserPreferences) *diagnostics.Message {
+	sym := symbol
+	if !preferences.UseAliasesForRename.IsTrue() && sym.Flags&ast.SymbolFlagsAlias != 0 {
+		importSpecifier := core.Find(sym.Declarations, ast.IsImportSpecifier)
+		if importSpecifier != nil && importSpecifier.AsImportSpecifier().PropertyName == nil {
+			sym = ch.GetAliasedSymbol(sym)
+		}
+	}
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/ls/rename.go:190]: That's not how truthy works

File: internal/ls/rename.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/ls/rename.go:57]: Now fixed, actually

File: internal/lsp/server.go [hunk 7]
```diff
@@ -550,6 +550,12 @@ func (s *Server) sendResult(id *jsonrpc.ID, result any) error {
 	})
 }
 
+// requestFailedError is an error with LSP RequestFailed (-32803) code and a clean user-facing message.
+type requestFailedError string
+
+func (e requestFailedError) Error() string { return string(e) }
+func (e requestFailedError) Unwrap() error { return lsproto.ErrorCodeRequestFailed }
+
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/lsp/server.go]: Yep, that the logging was the next thing I was going to fix.

File: internal/ls/rename.go [hunk 8]
```diff
@@ -0,0 +1,352 @@
...
+	for i := len(components) - 1; i >= 0; i-- {
+		if components[i] == "node_modules" {
+			nodeModulesIdx = i
+			break
+		}
+	}
+	if nodeModulesIdx == -1 {
+		return nil
+	}
+	end := min(nodeModulesIdx+2, len(components))
```
[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/ls/rename.go]: This is still preexisting

[the remark this answers is not in the document]
Comment (jakebailey) [reply internal/ls/rename.go]: we have a better func for this anyway, yay!

File: testdata/baselines/reference/submodule/fourslash/findRenameLocations/jsdocTypedefTagRename01.baseline.jsonc.diff [hunk 9]
```diff
@@ -37,10 +37,13 @@
...
 -// [|NumberLikeRENAME|] = 10;
+-// 
+-// /** @type {/*RENAME*/[|NumberLikeRENAME|]} */
++// var NumberLike;
++// 
 +// NumberLike = 10;
- // 
- // /** @type {/*RENAME*/[|NumberLikeRENAME|]} */
++// 
++// /** @type {/*RENAME*/NumberLike} */
```
Comment (gabritto) [inline testdata/baselines/reference/submodule/fourslash/findRenameLocations/jsdocTypedefTagRename01.baseline.jsonc.diff:48]: Why did this change? Is it that we don't create types in JS for variables anymore and require `typeof`?

File: testdata/baselines/reference/submodule/fourslash/findRenameLocations/renameDefaultImport.baseline.jsonc.diff [hunk 10]
```diff
@@ -0,0 +1,21 @@
+--- old.renameDefaultImport.baseline.jsonc
++++ new.renameDefaultImport.baseline.jsonc
+@@= skipped -0, +0 lines =@@
+ // === findRenameLocations ===
```
Comment (gabritto) [inline testdata/baselines/reference/submodule/fourslash/findRenameLocations/renameDefaultImport.baseline.jsonc.diff:4]: Note for future: this looks like a diff just in file sort order, I probably missed it when adding rename diffs, but we already do file sorting for find all refs diffs, so could fix it the same way.

File: testdata/baselines/reference/submodule/fourslash/findRenameLocations/renameNumericalIndex.baseline.jsonc.diff [hunk 11]
```diff
@@ -3,16 +3,14 @@
 @@= skipped -0, +0 lines =@@
  // === findRenameLocations ===
  // === /renameNumericalIndex.ts ===
--// const foo = { /*RENAME*/[|0RENAME|]: true };
+ // const foo = { /*RENAME*/[|0RENAME|]: true };
 -// foo[/*START PREFIX*/"[|0RENAME|]"/*END SUFFIX*/];
```
Comment (gabritto) [inline testdata/baselines/reference/submodule/fourslash/findRenameLocations/renameNumericalIndex.baseline.jsonc.diff:7]: Do you know what we're missing that causes this?

File: internal/fourslash/fourslash.go [hunk 12]
```diff
@@ -3640,36 +3640,69 @@ func (f *FourslashTest) verifyBaselineRename(
...
-		NewName:  "?",
 	}
 
 	prefix := f.getCurrentPositionPrefix()
-	result := sendRequest(t, f, lsproto.TextDocumentRenameInfo, params)
-	if result.WorkspaceEdit != nil {
-		t.Fatalf(prefix+"Expected rename to fail, but got changes: %s", cmp.Diff(result.WorkspaceEdit, nil))
+	f.baselineState(t)
+	f.baselineRequestOrNotification(t, lsproto.TextDocumentPrepareRenameInfo.Method, params)
+	resMsg, result, _ := lsptestutil.SendRequest(t, f.client, lsproto.TextDocumentPrepareRenameInfo, params)
```
Comment (gabritto) [inline internal/fourslash/fourslash.go:3686]: What was going wrong with using `sendRequest` and letting it handle baseline state?

File: internal/lsp/server.go [hunk 13]
```diff
@@ -550,6 +550,11 @@ func (s *Server) sendResult(id *jsonrpc.ID, result any) error {
 	})
 }
 
+type userFacingRequestFailedError string
```
Comment (gabritto) [inline internal/lsp/server.go:553]: Do we have plans to actually surface this at some point?

File: testdata/baselines/reference/submodule/fourslash/findRenameLocations/jsdocTypedefTagRename01.baseline.jsonc.diff (hunk 9 above)
Comment (jakebailey) [reply testdata/baselines/reference/submodule/fourslash/findRenameLocations/jsdocTypedefTagRename01.baseline.jsonc.diff:48]: Rather, we don't let you do a `typedef` and not give a name, as in we don't infer it from the var below: https://github.com/microsoft/typescript-go/blob/main/CHANGES.md#:~:text=Identifier%2Dnamed%20typedefs

It's possible there are more places that could be deleted.

File: testdata/baselines/reference/submodule/fourslash/findRenameLocations/renameDefaultImport.baseline.jsonc.diff (hunk 10 above)
Comment (jakebailey) [reply testdata/baselines/reference/submodule/fourslash/findRenameLocations/renameDefaultImport.baseline.jsonc.diff:4]: Yep, I noticed this too but didn't want to stack more on.

File: internal/fourslash/fourslash.go (hunk 12 above)
Comment (jakebailey) [reply internal/fourslash/fourslash.go:3686]: This is actually the first case we have where we _expect_ an error to come back. Not many LSP calls actually want you to return an error. This could probably be done more clearly, though, if you want me to look harder.

Comment (jakebailey) [reply internal/fourslash/fourslash.go:3686]: Actaully, this is the only place in the LSP that does this! https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#:~:text=Clients%20should%20show%20the%20information%20in%20their%20user%20interface.

File: internal/lsp/server.go (hunk 13 above)
Comment (jakebailey) [reply internal/lsp/server.go:553]: That's what's in my PR screenshots, actually. To go with: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#:~:text=Clients%20should%20show%20the%20information%20in%20their%20user%20interface.

File: internal/fourslash/fourslash.go (hunk 12 above)
Comment (jakebailey) [reply internal/fourslash/fourslash.go:3686]: Er, well. this is the failed case, so not exactly what I'm describing, however normally a failed request fails the test.

File: testdata/baselines/reference/submodule/fourslash/findRenameLocations/renameNumericalIndex.baseline.jsonc.diff (hunk 11 above)
Comment (jakebailey) [reply testdata/baselines/reference/submodule/fourslash/findRenameLocations/renameNumericalIndex.baseline.jsonc.diff:7]: The `START PREFIX` thing? that's some fourslash thing that I think is not ported.

File: internal/lsp/server.go (hunk 13 above)
Comment (gabritto) [reply internal/lsp/server.go:553]: Ah, I missed the updated PR description. Nice!
