### PR TITLE
Don't panic on failed send in recover

### LINKED ISSUE #2828: "panic: Debug failure. False expression: Token end is child end" in CI
Unclear which test did this.

```
panic: Debug failure. False expression: Token end is child end [recovered]
	panic: context canceled

goroutine 81766 [running]:
github.com/microsoft/typescript-go/internal/lsp.(*Server).recover(0x12d7edc0d508, {0x7ff69d951325?, 0x12d7ea0525a0?}, 0x12d7ed3b93b0)
	D:/a/typescript-go/typescript-go/internal/lsp/server.go:857 +0x472
panic({0x7ff69eee2480?, 0x12d7ee31f4f0?})
	C:/Users/runneradmin/AppData/Local/microsoft-go/go1.26.0-1/src/runtime/panic.go:860 +0x13a
github.com/microsoft/typescript-go/internal/debug.Fail(...)
	D:/a/typescript-go/typescript-go/internal/debug/shared.go:14
github.com/microsoft/typescript-go/internal/debug.Assert(...)
	D:/a/typescript-go/typescript-go/internal/debug/debug.go:18
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).processChildNode(0x12d7ee3d8e10, 0x12d7f293cd10, 0x1?, 0x0?, 0x1800000000000c?, 0x12d7f1da8820, 0xffffffffffffffff, 0x12d7f293cd10, 0x12d7f1212360, 0x8, ...)
	D:/a/typescript-go/typescript-go/internal/format/span.go:405 +0x139f
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).execute.func1(0x12d7f1da8820)
	D:/a/typescript-go/typescript-go/internal/format/span.go:231 +0x78
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitNode(0x7ff69e54ca59?, 0x12d7f32a0000?)
	D:/a/typescript-go/typescript-go/internal/ast/visitor.go:51 +0x7c
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).visitNode(0x250ceb409e0?, 0x30?)
	D:/a/typescript-go/typescript-go/internal/ast/visitor.go:198 +0x6d
github.com/microsoft/typescript-go/internal/ast.(*PropertyAccessExpression).VisitEachChild(0x12d7f293cd10, 0x12d7f31d99e0)
	D:/a/typescript-go/typescript-go/internal/ast/ast.go:6833 +0x52
github.com/microsoft/typescript-go/internal/ast.(*Node).VisitEachChild(...)
	D:/a/typescript-go/typescript-go/internal/ast/ast.go:255
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).executeProcessNodeVisitor(0x12d7ee3d8e10, 0x0?, 0x0?, 0x0?, 0x0?)
	D:/a/typescript-go/typescript-go/internal/format/span.go:527 +0xfa
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).processNode(0x12d7ee3d8e10, 0x12d7f293cd10, 0x12d7ee8992c0, 0x8, 0x8, 0x0, 0x4)
	D:/a/typescript-go/typescript-go/internal/format/span.go:624 +0x1d5
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).processChildNode(0x12d7ee3d8e10, 0x12d7ee8992c0, 0x0?, 0xc?, 0x1?, 0x12d7f293cd10, 0xffffffffffffffff, 0x12d7ee8992c0, 0x12d7f1212330, 0x8, ...)
	D:/a/typescript-go/typescript-go/internal/format/span.go:417 +0x1234
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).execute.func1(0x12d7f293cd10)
	D:/a/typescript-go/typescript-go/internal/format/span.go:231 +0x78
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitNode(0x12d7ec9cb498?, 0x7ff69d988605?)
	D:/a/typescript-go/typescript-go/internal/ast/visitor.go:51 +0x7c
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).visitNode(0x5000000000006?, 0x250f44e0be8?)
	D:/a/typescript-go/typescript-go/internal/ast/visitor.go:198 +0x6d
github.com/microsoft/typescript-go/internal/ast.(*CallExpression).VisitEachChild(0x12d7ee8992c0, 0x12d7f31d99e0)
	D:/a/typescript-go/typescript-go/internal/ast/ast.go:6949 +0x52
github.com/microsoft/typescript-go/internal/ast.(*Node).VisitEachChild(...)
	D:/a/typescript-go/typescript-go/internal/ast/ast.go:255
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).executeProcessNodeVisitor(0x12d7ee3d8e10, 0x0?, 0x0?, 0x0?, 0x0?)
	D:/a/typescript-go/typescript-go/internal/format/span.go:527 +0xfa
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).processNode(0x12d7ee3d8e10, 0x12d7ee8992c0, 0x12d7f1cda800, 0x8, 0x8, 0x0, 0x4)
	D:/a/typescript-go/typescript-go/internal/format/span.go:624 +0x1d5
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).processChildNode(0x12d7ee3d8e10, 0x12d7f1cda800, 0x12d7ec9cb7e8?, 0x1?, 0x0?, 0x12d7ee8992c0, 0xffffffffffffffff, 0x12d7f1cda800, 0x12d7f1212300, 0x8, ...)
	D:/a/typescript-go/typescript-go/internal/format/span.go:417 +0x1234
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).execute.func1(0x12d7ee8992c0)
	D:/a/typescript-go/typescript-go/internal/format/span.go:231 +0x78
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).VisitNode(0x250ceb409e0?, 0x30?)
	D:/a/typescript-go/typescript-go/internal/ast/visitor.go:51 +0x7c
github.com/microsoft/typescript-go/internal/ast.(*NodeVisitor).visitNode(0x12d7ec9cb880?, 0x7ff69d9885e5?)
	D:/a/typescript-go/typescript-go/internal/ast/visitor.go:198 +0x6d
github.com/microsoft/typescript-go/internal/ast.(*ExpressionStatement).VisitEachChild(0x12d7f1cda800, 0x12d7f31d99e0)
	D:/a/typescript-go/typescript-go/internal/ast/ast.go:3707 +0x4e
github.com/microsoft/typescript-go/internal/ast.(*Node).VisitEachChild(...)
	D:/a/typescript-go/typescript-go/internal/ast/ast.go:255
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).executeProcessNodeVisitor(0x12d7ee3d8e10, 0x98?, 0x7ff69f092440?, 0x1?, 0x0?)
	D:/a/typescript-go/typescript-go/internal/format/span.go:527 +0xfa
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).processNode(0x12d7ee3d8e10, 0x12d7f1cda800, 0x12d7f1cda800, 0x8, 0x8, 0x0, 0x4)
	D:/a/typescript-go/typescript-go/internal/format/span.go:624 +0x1d5
github.com/microsoft/typescript-go/internal/format.(*formatSpanWorker).execute(0x12d7ee3d8e10, 0x7ff69d9885e5?)
	D:/a/typescript-go/typescript-go/internal/format/span.go:252 +0x7a8
github.com/microsoft/typescript-go/internal/format.newFormattingScanner({0x12d7ee500a50, 0xa7}, 0x0, 0xa0, 0xa7, 0x12d7ee3d8e10)
	D:/a/typescript-go/typescript-go/internal/format/scanner.go:57 +0x43e
github.com/microsoft/typescript-go/internal/format.FormatSpan({0x7ff69f9c3368, 0x12d7f1212030}, {0xa0, 0xa7}, 0x12d7f0f7e708, 0x3)
	D:/a/typescript-go/typescript-go/internal/format/api.go:63 +0x394
github.com/microsoft/typescript-go/internal/format.formatNodeLines({0x7ff69f9c3368, 0x12d7f1212030}, 0x12d7f0f7e708, 0x12d7f1cda800, 0x3)
	D:/a/typescript-go/typescript-go/internal/format/api.go:107 +0x125
github.com/microsoft/typescript-go/internal/format.FormatOnSemicolon({0x7ff69f9c3368, 0x12d7f1212030}, 0x12d7f0f7e708, 0x0?)
	D:/a/typescript-go/typescript-go/internal/format/api.go:148 +0x72
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).getFormattingEditsAfterKeystroke(0x12d7eeeb2138?, {0x7ff69f9c3368?, 0x12d7ed3b94d0?}, 0x12d7f0f7e708, 0x12d7eeeddd48?, 0xa7, {0x12d7ef20d978, 0x1})
	D:/a/typescript-go/typescript-go/internal/ls/format.go:111 +0x138
github.com/microsoft/typescript-go/internal/ls.(*LanguageService).ProvideFormatDocumentOnType(0x12d7f06f39c0, {0x7ff69f9c3368, 0x12d7ed3b94d0}, {0x12d7eec14900?, 0x0?}, 0x12d7f1754280, {0xf05bde10?, 0x12d7?}, {0x12d7ef20d978, 0x1})
	D:/a/typescript-go/typescript-go/internal/ls/format.go:65 +0x267
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleDocumentOnTypeFormat(0x7ff69d90d91b?, {0x7ff69f9c3368?, 0x12d7ed3b94d0?}, 0x12d7e8c13808?, 0x12d7e8c13d98?)
	D:/a/typescript-go/typescript-go/internal/lsp/server.go:1210 +0x71
github.com/microsoft/typescript-go/internal/lsp.init.func1.registerLanguageServiceDocumentRequestHandler[...].19.1()
	D:/a/typescript-go/typescript-go/internal/lsp/server.go:716 +0xb6
github.com/microsoft/typescript-go/internal/lsp.(*Server).handleRequestOrNotification.func1()
	D:/a/typescript-go/typescript-go/internal/lsp/server.go:579 +0xa7
github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop.func3()
	D:/a/typescript-go/typescript-go/internal/lsp/server.go:454 +0x36
created by github.com/microsoft/typescript-go/internal/lsp.(*Server).dispatchLoop in goroutine 81635
	D:/a/typescript-go/typescript-go/internal/lsp/server.go:453 +0x5a5
FAIL	github.com/microsoft/typescript-go/internal/fourslash/tests/gen	5.538s
```

https://github.com/microsoft/typescript-go/actions/runs/22158439436/job/64068630976

### PR DESCRIPTION
**Pull request by jakebailey**
These functions cannot fail except during cancellation, in which case we want to return anyway.

Just ignore these errors. They are best case.

Then, unskip the now passing tests.

Fixes #2828 (pretty sure it's a test which fails for another reason, and then breaks while exiting on cancel)

### CODE REVIEW

File: internal/lsp/server.go [hunk 1]
```diff
@@ -834,14 +834,15 @@ func (s *Server) getLanguageServiceAndCrossProjectOrchestrator(ctx context.Conte
...
 		s.logger.Errorf("panic handling request %s: %v\n%s", req.Method, r, string(stack))
 		if req.ID != nil {
 			err := s.sendError(req.ID, fmt.Errorf("%w: panic handling request %s: %v", lsproto.ErrorCodeInternalError, req.Method, r))
 			if err != nil {
-				panic(err)
+				s.logger.Errorf("error sending error response: %v", err)
+				return
 			}
 
 			err = sendNotification(s, lsproto.TelemetryEventInfo, lsproto.TelemetryEvent{
```
Comment (jakebailey) [inline internal/lsp/server.go]: Both are just channel sends. They cannot fail except in cancellation, in which case the whole thing is shutting down and we should just keep returning.

Comment (jakebailey) [reply internal/lsp/server.go]: In fact, I should just have no logs. It'll just say "cancelled".

File: internal/lsp/server.go [hunk 2]
```diff
@@ -834,17 +834,16 @@ func (s *Server) getLanguageServiceAndCrossProjectOrchestrator(ctx context.Conte
 	return defaultLs, orchestrator, err
 }
 
-func (s *Server) recover(ctx context.Context, req *lsproto.RequestMessage) {
+func (s *Server) recover(req *lsproto.RequestMessage) {
```
Comment (DanielRosenwasser) [inline internal/lsp/server.go:837]: Why was `ctx` ever needed? I don't see where it was used.

Comment (jakebailey) [reply internal/lsp/server.go:837]: Before `backgroundCtx` existed. I think this was just missed in the refactor (probably my fault)

**Review by DanielRosenwasser — APPROVED** [review]
