### PR TITLE
fix(3410): preserve type arguments in hover for qualified names

### LINKED ISSUE #3410: Type serializer omits type arguments of outer functions
## Steps to reproduce

Hover on `box` in the following example:

```ts
function makeBox<T>(x: T) {
    class Box {
        value = x
    }
    return new Box()
}

let box = makeBox("hello")
```

## Behavior with `typescript@6.0`

Hovering on `box` displays:

```ts
let box: makeBox<string>.Box
```

## Behavior with `tsgo`

Hovering on `box` displays:

```ts
let box: makeBox.Box
```

Notice the missing type arguments. This similarly affects baselines in our test suites.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #3410

### CODE REVIEW

**Review by weswigham — COMMENTED** [review]
This is *technically* an abuse of the AST - `ExpressionWithTypeArguments` is only naturally parsed in the context of class `extends` clauses, however it's probably fine for making hover match up better, and AFAIK nothing in the emit pipeline relies on `ExpressionWithTypeArguments` only appearing in class `extends` positions (I would feel better about this with a strong type system, but alas).

Instantiation expression type arguments normally live exclusively on the `TypeQuery` itself, which is something we need to double check isn't being doubled up on here; if we go to put an `ExpressionWithTypeArguments` into a `TypeQuery` in the node builder, we *probably* should swap the type arguments up into the type query. I'll also be surprised if you don't need to update failing fourslash tests.

File: internal/nodebuilder/types.go [hunk 1]
```diff
@@ -43,6 +43,7 @@ const (
 	FlagsUseTypeOfFunction                   Flags = 1 << 12
 	FlagsOmitParameterModifiers              Flags = 1 << 13
 	FlagsUseAliasDefinedOutsideCurrentScope  Flags = 1 << 14
+	FlagsUseInstantiationExpressions         Flags = 1 << 31
```
Comment (weswigham) [inline internal/nodebuilder/types.go]: ...why is 31 between 14 and 28?

File: internal/ast/precedence.go [hunk 2]
```diff
@@ -698,6 +698,7 @@ func GetTypeNodePrecedence(n *TypeNode) TypePrecedence {
 		KindLiteralType,
 		KindTypePredicate,
 		KindTypeReference,
+		KindExpressionWithTypeArguments,
```
Comment (weswigham) [inline internal/ast/precedence.go:701]: Presumably this is to prevent auto-parenthesizing `(foo<T>).bar`, which has never mattered before since previously these nodes would only appear in heritage clauses.

File: internal/nodebuilder/types.go (hunk 1 above)
Comment (a-tarasyuk) [reply internal/nodebuilder/types.go]: @weswigham I’ve updated it by lowering the value and positioning it after `1 << 29`.

**Comment by ahejlsberg** [comment]
> This is *technically* an abuse of the AST - `ExpressionWithTypeArguments` is only naturally parsed in the context of class `extends` clauses

That used to be the case, but these days we parse `ExpressionWithTypeArguments` for instantiation expressions, so they can definitely occur in regular expressions.

**Comment by weswigham** [comment]
Expressions, yes, not usually arbitrary expressions within type nodes, though - only at the end of a `typeof` query. `declare const x: typeof Something<string>.Other` does not parse (yet is what we're emitting here), but `declare const x: typeof Something<string>` does.

File: internal/checker/nodebuilderimpl.go [hunk 3]
```diff
@@ -3449,3 +3425,98 @@ func (b *NodeBuilderImpl) newIdentifier(text string, symbol *ast.Symbol) *ast.No
...
+		typeArguments = expr.TypeArguments
+	}
+
+	var names []*ast.IdentifierNode
+	node := expr.Expression
+
+	for {
+		if ast.IsExpressionWithTypeArguments(node) {
+			exprWithTypeArgs := node.AsExpressionWithTypeArguments()
+			if exprWithTypeArgs.TypeArguments != nil && len(exprWithTypeArgs.TypeArguments.Nodes) > 0 {
```
Comment (weswigham) [inline internal/checker/nodebuilderimpl.go]:
```suggestion
			if len(typeArguments) == 0 && exprWithTypeArgs.TypeArguments != nil && len(exprWithTypeArgs.TypeArguments.Nodes) > 0 {
```

Otherwise this is going to hoist any inner type arguments to the outer position on the type query, which is wrong. But if I'm honest, all this is probably overkill, since we probably don't need to strip the inner ones anyway (the caller requested them, after all). I'm pretty sure you don't need any kinda loop, and a simple `return b.f.NewTypeQueryNode(expr.Expression(), expr.TypeArguments)` should suffice? Unless I'm mistaken for some reason?

Comment (a-tarasyuk) [reply internal/checker/nodebuilderimpl.go]: @weswigham You're right. I missed that this path should preserve only the trailing type arguments in the type query, and overcomplicated it by handling a nested case like `a<number>.b.c<string>` that isn't reachable here. Thanks for pointing that out.

**Review by weswigham — APPROVED** [review]
